# Subtask 2: Taiji MBHB Parameter Estimation

This notebook implements UCAS 2026 Task 5 subtask 2 by migrating the official
Triangle-BBH Example 4 workflow into this repository and then adding the required
asymmetric 5-day window experiment.

Baseline source: `external/Triangle-BBH/Examples/4_TDC_Verification_MBHB_Search_and_Estimation(CPU).ipynb`.

Implemented requirements:

1. Reproduce official Example 4 as the baseline.
2. Record and explain TDI loading, FFT, MBHB waveform generation, F-statistics search, Fisher analysis, heterodyned likelihood, and Bayesian sampling.
3. Change the data window from the official symmetric 5-day window, `tc - 2.5 days` to `tc + 2.5 days`, to the task-required asymmetric window, `tc - 4 days` to `tc + 1 day`.
4. Rebuild all data-dependent objects for the modified window and rerun the same inference chain.
5. Save figures and summaries under `figures/task5_subtask2/` and `results/task5_subtask2/`.

Heavy search and sampling cells are controlled by runtime switches so the notebook can be opened safely.

## 0. Execution Checklist

- [ ] Configure `0_2_MBHB_TDIXYZ.h5` and `0_2_MBHB_parameters.h5`.
- [ ] Load TDC II TDI XYZ data and injected parameters.
- [ ] Convert XYZ to A/E/T and keep A/E channels with the official sign convention.
- [ ] Build official baseline window: `tc - 2.5 days` to `tc + 2.5 days`.
- [ ] Reproduce Example 4 FFT, PSD, frequency cut, covariance, model setup, F-statistics search, Fisher analysis, likelihood, and sampler.
- [ ] Build task-required window: `tc - 4 days` to `tc + 1 day`.
- [ ] Rebuild time-domain data, FFT, PSD, covariance, waveform response, likelihood, and sampler for the modified window.
- [ ] Compare posterior medians and 90% credible intervals.
- [ ] Update README with final figures and quantitative conclusions.

## 1. Environment and Reproducibility

In [1]:
from __future__ import annotations

import json
import os
import platform
import subprocess
import sys
from pathlib import Path

os.environ.setdefault("OMP_NUM_THREADS", "1")
os.environ.setdefault("OPENBLAS_NUM_THREADS", "1")
os.environ.setdefault("MKL_NUM_THREADS", "1")
os.environ.setdefault("NUMEXPR_NUM_THREADS", "1")
os.environ.setdefault("VECLIB_MAXIMUM_THREADS", "1")

REPO_ROOT = Path.cwd().resolve()
if REPO_ROOT.name == "notebooks":
    REPO_ROOT = REPO_ROOT.parent
os.environ.setdefault("MPLCONFIGDIR", str(REPO_ROOT / ".cache" / "matplotlib"))

TRIANGLE_BBH_DIR = REPO_ROOT / "external" / "Triangle-BBH"
TRIANGLE_SIM_DIR = REPO_ROOT / "external" / "Triangle-Simulator"
FIGURE_DIR = REPO_ROOT / "figures" / "task5_subtask2"
RESULT_DIR = REPO_ROOT / "results" / "task5_subtask2"
FIGURE_DIR.mkdir(parents=True, exist_ok=True)
RESULT_DIR.mkdir(parents=True, exist_ok=True)
(REPO_ROOT / ".cache" / "matplotlib").mkdir(parents=True, exist_ok=True)

def git_commit(path: Path) -> str:
    if not path.exists():
        return "missing"
    try:
        return subprocess.check_output(
            ["git", "-C", str(path), "rev-parse", "--short", "HEAD"],
            text=True,
            stderr=subprocess.DEVNULL,
        ).strip()
    except Exception as exc:
        return f"unavailable: {exc}"

print("Python:", sys.version)
print("Platform:", platform.platform())
print("Repo root:", REPO_ROOT)
print("Triangle-BBH commit:", git_commit(TRIANGLE_BBH_DIR))
print("Triangle-Simulator commit:", git_commit(TRIANGLE_SIM_DIR))

Python: 3.12.13 (main, Mar  3 2026, 15:01:35) [MSC v.1944 64 bit (AMD64)]
Platform: Windows-11-10.0.26200-SP0
Repo root: C:\Users\雷畅\Documents\Codex\2026-05-19\files-mentioned-by-the-user-2026\task5-lisa-taiji
Triangle-BBH commit: unavailable: Command '['git', '-C', 'C:\\Users\\雷畅\\Documents\\Codex\\2026-05-19\\files-mentioned-by-the-user-2026\\task5-lisa-taiji\\external\\Triangle-BBH', 'rev-parse', '--short', 'HEAD']' returned non-zero exit status 128.
Triangle-Simulator commit: unavailable: Command '['git', '-C', 'C:\\Users\\雷畅\\Documents\\Codex\\2026-05-19\\files-mentioned-by-the-user-2026\\task5-lisa-taiji\\external\\Triangle-Simulator', 'rev-parse', '--short', 'HEAD']' returned non-zero exit status 128.

## 2. Runtime Switches and Paths

Official data links from Example 4:

- TDI data: https://zenodo.org/records/15469724/files/0_2_MBHB_TDIXYZ.h5?download=1
- parameters: https://zenodo.org/records/15532090/files/0_2_MBHB_parameters.h5?download=1

In [2]:
RUN_BASELINE_SEARCH = False
RUN_BASELINE_SAMPLER = True
RUN_FIVE_DAY_SEARCH = False
RUN_FIVE_DAY_SAMPLER = True
USE_CACHED_SEARCH_RESULTS = True
USE_SMOKE_TEST_SAMPLER = True
USE_SMOKE_TEST_SEARCH = True
FISHER_PRIOR_SIGMA = 10.0 if USE_SMOKE_TEST_SEARCH else 5.0

FMIN = 0.5e-4
FMAX = 1e-2
OFFICIAL_SEARCH_MAXITER = 1000
SMOKE_TEST_SEARCH_MAXITER = 100
DE_WORKERS = 1 if os.name == "nt" else -1
OFFICIAL_SAMPLER_SETTINGS = dict(sampler="nessai", nlive=1200, stopping=0.1)
SMOKE_TEST_SAMPLER_SETTINGS = dict(sampler="dynesty", nlive=80, dlogz=10.0, maxcall=1000, walks=5)
SAMPLER_POOL = 1 if os.name == "nt" else os.cpu_count()

CANDIDATE_TDC_ROOTS = [
    REPO_ROOT / "data" / "tdc",
    Path(r"E:\BaiduNetdiskDownload"),
    Path(r"E:\BaiduNetdiskDownload\TDCData"),
]

def find_first_existing(filename: str) -> Path | None:
    for root in CANDIDATE_TDC_ROOTS:
        candidate = root / filename
        if candidate.exists():
            return candidate
    return None

DATA_DIR = find_first_existing("0_2_MBHB_TDIXYZ.h5") or (REPO_ROOT / "data" / "tdc" / "0_2_MBHB_TDIXYZ.h5")
PARAM_DIR = find_first_existing("0_2_MBHB_parameters.h5") or (REPO_ROOT / "data" / "tdc" / "0_2_MBHB_parameters.h5")
ORBIT_DIR = TRIANGLE_SIM_DIR / "OrbitData" / "MicroSateOrbitEclipticTCB"

print("DATA_DIR:", DATA_DIR, DATA_DIR.exists())
print("PARAM_DIR:", PARAM_DIR, PARAM_DIR.exists())
print("ORBIT_DIR:", ORBIT_DIR, ORBIT_DIR.exists())
print("DE_WORKERS:", DE_WORKERS)
print("SAMPLER_POOL:", SAMPLER_POOL)
print("FISHER_PRIOR_SIGMA:", FISHER_PRIOR_SIGMA)

DATA_DIR: C:\Users\雷畅\Documents\Codex\2026-05-19\files-mentioned-by-the-user-2026\task5-lisa-taiji\data\tdc\0_2_MBHB_TDIXYZ.h5 True
PARAM_DIR: C:\Users\雷畅\Documents\Codex\2026-05-19\files-mentioned-by-the-user-2026\task5-lisa-taiji\data\tdc\0_2_MBHB_parameters.h5 True
ORBIT_DIR: C:\Users\雷畅\Documents\Codex\2026-05-19\files-mentioned-by-the-user-2026\task5-lisa-taiji\external\Triangle-Simulator\OrbitData\MicroSateOrbitEclipticTCB True
DE_WORKERS: 1
SAMPLER_POOL: 1
FISHER_PRIOR_SIGMA: 10.0

## 3. Imports Matching Official Example 4

In [3]:
import bilby
import h5py
import matplotlib
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from scipy.interpolate import CubicSpline
from scipy.optimize import differential_evolution
from tqdm import tqdm

if not hasattr(np, "int"):
    np.int = int
if not hasattr(np, "float"):
    np.float = float

matplotlib.rcParams["text.usetex"] = False

from Triangle.Constants import *
from Triangle.Orbit import *
from Triangle.Noise import *
from Triangle.FFTTools import *
from Triangle.TDI import *
from Triangle.Data import *

from Triangle_BBH.Waveform import *
from Triangle_BBH.Response import *
from Triangle_BBH.Utils import *
from Triangle_BBH.Fisher import *

try:
    import nessai  # noqa: F401
    HAS_NESSAI = True
except Exception as exc:
    HAS_NESSAI = False
    print("NESSAI unavailable:", repr(exc))

plt.rcParams.update({"figure.dpi": 130, "savefig.dpi": 220, "axes.grid": True, "grid.alpha": 0.25})
print("Imports OK")
print("bilby:", getattr(bilby, "__version__", "unknown"))
print("NESSAI available:", HAS_NESSAI)
print("bilby samplers:", sorted(bilby.core.sampler.IMPLEMENTED_SAMPLERS.keys()))

no cupy
no cupy
no BBHx waveform
Imports OK
bilby: 1.0.0: release
NESSAI available: True
bilby samplers: ['cpnest', 'dynamic_dynesty', 'dynesty', 'emcee', 'fake_sampler', 'kombine', 'nestle', 'ptemcee', 'ptmcmcsampler', 'pymc3', 'pymultinest', 'pypolychord', 'ultranest']

C:\Users\雷畅\AppData\Local\Temp\ipykernel_40700\2900546392.py:18: RuntimeWarning: Skipping Triangle.GW: missing optional dependency lal
  from Triangle.Constants import *
C:\Users\雷畅\AppData\Local\Temp\ipykernel_40700\2900546392.py:18: RuntimeWarning: Skipping Triangle.Glitch: missing optional dependency lal
  from Triangle.Constants import *
C:\Users\雷畅\AppData\Local\Temp\ipykernel_40700\2900546392.py:18: RuntimeWarning: Skipping Triangle.Interferometer: missing optional dependency lal
  from Triangle.Constants import *

## 4. Utility Functions

In [4]:
def save_current_figure(filename: str) -> Path:
    path = FIGURE_DIR / filename
    plt.tight_layout()
    plt.savefig(path, bbox_inches="tight")
    print(f"Saved: {path.relative_to(REPO_ROOT)}")
    return path

def require_file(path: Path, label: str) -> None:
    if not path.exists():
        raise FileNotFoundError(f"{label} not found: {path}")

def print_h5_tree(path: Path, max_items: int = 80) -> None:
    require_file(path, "HDF5 file")
    count = 0
    with h5py.File(path, "r") as h5:
        def visitor(name, obj):
            nonlocal count
            if count >= max_items:
                return
            if isinstance(obj, h5py.Dataset):
                print(f"DATASET /{name}: shape={obj.shape}, dtype={obj.dtype}")
            else:
                print(f"GROUP   /{name}")
            count += 1
        h5.visititems(visitor)
    if count >= max_items:
        print(f"... stopped after {max_items} items")

def save_json(obj, filename: str) -> Path:
    path = RESULT_DIR / filename
    with path.open("w", encoding="utf-8") as f:
        json.dump(obj, f, indent=2, ensure_ascii=False, default=str)
    print(f"Saved: {path.relative_to(REPO_ROOT)}")
    return path

def save_parameter_dict(param_dict: dict, filename: str) -> Path:
    clean = {k: (float(v) if np.isscalar(v) and v is not None else v) for k, v in param_dict.items()}
    return save_json(clean, filename)

def posterior_summary(samples: pd.DataFrame, parameters: list[str]) -> pd.DataFrame:
    rows = []
    for p in parameters:
        if p not in samples:
            continue
        q05, q50, q95 = np.percentile(samples[p], [5, 50, 95])
        rows.append(dict(parameter=p, median=q50, ci90_low=q05, ci90_high=q95, ci90_width=q95-q05))
    return pd.DataFrame(rows)

def is_valid_hdf5(path: Path) -> bool:
    if not path.exists():
        return False
    try:
        with h5py.File(path, "r"):
            return True
    except OSError as exc:
        print(f"Invalid or incomplete HDF5 file: {path}")
        print("h5py error:", exc)
        return False

## 5. Inspect and Load TDC Data

In [5]:
DATA_FILE_OK = is_valid_hdf5(DATA_DIR)
PARAM_FILE_OK = is_valid_hdf5(PARAM_DIR)

if DATA_FILE_OK:
    print("Data file tree:")
    print_h5_tree(DATA_DIR)
else:
    print("Data file is not present or is incomplete:", DATA_DIR)

if PARAM_FILE_OK:
    print("\nParameter file tree:")
    print_h5_tree(PARAM_DIR)
else:
    print("Parameter file is not present or is incomplete:", PARAM_DIR)

Data file tree:
GROUP   /XYZ
DATASET /XYZ/X2: shape=(259200,), dtype=float64
DATASET /XYZ/Y2: shape=(259200,), dtype=float64
DATASET /XYZ/Z2: shape=(259200,), dtype=float64
DATASET /time: shape=(259200,), dtype=float64

Parameter file tree:
DATASET /chirp_mass: shape=(1,), dtype=float64
DATASET /coalescence_phase: shape=(1,), dtype=float64
DATASET /coalescence_time: shape=(1,), dtype=float64
DATASET /inclination: shape=(1,), dtype=float64
DATASET /latitude: shape=(1,), dtype=float64
DATASET /longitude: shape=(1,), dtype=float64
DATASET /luminosity_distance: shape=(1,), dtype=float64
DATASET /mass_ratio: shape=(1,), dtype=float64
DATASET /psi: shape=(1,), dtype=float64
DATASET /spin_1z: shape=(1,), dtype=float64
DATASET /spin_2z: shape=(1,), dtype=float64

In [6]:
read_dict = None
injected_parameters = None

if DATA_FILE_OK and PARAM_FILE_OK:
    with h5py.File(DATA_DIR, "r") as h5file:
        read_dict = read_dict_from_h5(h5file["/"])
    with h5py.File(PARAM_DIR, "r") as h5file:
        injected_parameters = read_dict_from_h5(h5file["/"])
    print("read_dict keys:", read_dict.keys())
    print("injected_parameters keys:", injected_parameters.keys())
else:
    print("Skipping data load because one or both TDC files are missing or incomplete.")

read_dict keys: dict_keys(['XYZ', 'time'])
injected_parameters keys: dict_keys(['chirp_mass', 'coalescence_phase', 'coalescence_time', 'inclination', 'latitude', 'longitude', 'luminosity_distance', 'mass_ratio', 'psi', 'spin_1z', 'spin_2z'])

## 6. Convert TDI XYZ to A/E Channels

This follows official Example 4: construct A/E/T, drop T, and apply the minus sign because the Michelson TDI-2.0 convention differs from Triangle-Simulator by a minus sign.

In [7]:
full_time = None
full_channels_td = None
full_A2_td = None
full_E2_td = None
channel_names = ["A2", "E2"]

if read_dict is not None:
    full_time = np.asarray(read_dict["time"])
    full_A2_td, full_E2_td, _ = AETfromXYZ(read_dict["XYZ"]["X2"], read_dict["XYZ"]["Y2"], read_dict["XYZ"]["Z2"])
    full_channels_td = -np.array([full_A2_td, full_E2_td])
    full_dt = float(full_time[1] - full_time[0])
    print("full_time shape:", full_time.shape)
    print("full_channels_td shape:", full_channels_td.shape)
    print("dt:", full_dt, "s")
else:
    print("No TDC data loaded yet.")

full_time shape: (259200,)
full_channels_td shape: (2, 259200)
dt: 10.0 s

## 7. Window Builder Shared by Baseline and Modified Run

Official Example 4 uses `abs(data_time / DAY - tc) < 2.5`. The task-required run uses `tc - 4 days` to `tc + 1 day`. The function below rebuilds FFT, PSD, frequency cut, covariance, and inverse covariance for each window.

In [8]:
def get_tc_day(params: dict) -> float:
    return float(params["coalescence_time"])

def get_window_bounds(tc_day: float, mode: str) -> tuple[float, float]:
    if mode == "official_baseline":
        return tc_day - 2.5, tc_day + 2.5
    if mode == "task_five_day":
        return tc_day - 4.0, tc_day + 1.0
    raise ValueError(f"Unknown mode: {mode}")

def build_window_data(label: str, mode: str, psd_mode: str = "before") -> dict:
    if full_time is None or full_channels_td is None or injected_parameters is None:
        raise RuntimeError("Load TDC data and injected parameters first.")
    tc_day = get_tc_day(injected_parameters)
    start_day, end_day = get_window_bounds(tc_day, mode)
    mask = (full_time / DAY >= start_day) & (full_time / DAY <= end_day)
    if mask.sum() < 16:
        raise ValueError(f"{label}: selected window has too few samples: {mask.sum()}")
    data_time = full_time[mask]
    data_channels_td = full_channels_td[:, mask]
    dt = float(data_time[1] - data_time[0])
    Tobs = len(data_time) * dt

    data_channels_fd = []
    for i in range(len(data_channels_td)):
        ff, xf = FFT_window(data_array=data_channels_td[i], fsample=1.0/dt, window_type="tukey", window_args_dict=dict(alpha=1000.0/Tobs))
        data_channels_fd.append(xf)
    data_channels_fd = np.array(data_channels_fd) * np.exp(-TWOPI * 1.j * ff * data_time[0])
    data_frequency = ff

    if psd_mode == "before":
        psd_mask = full_time < data_time[0]
    elif psd_mode == "outside":
        psd_mask = (full_time < data_time[0]) | (full_time > data_time[-1])
    else:
        raise ValueError("psd_mode must be 'before' or 'outside'")
    if psd_mask.sum() < 16:
        raise ValueError(f"{label}: not enough silent samples for PSD: {psd_mask.sum()}")

    ff_psd, A2_PSD = PSD_window(data_array=full_A2_td[psd_mask], fsample=1.0/dt, window_type="hann", nbin=20)
    _, E2_PSD = PSD_window(data_array=full_E2_td[psd_mask], fsample=1.0/dt, window_type="hann", nbin=20)
    psd_channels = np.array([CubicSpline(ff_psd, A2_PSD, extrapolate=True)(data_frequency), CubicSpline(ff_psd, E2_PSD, extrapolate=True)(data_frequency)])

    freq_idx = np.where((data_frequency >= FMIN) & (data_frequency <= FMAX))[0]
    data_frequency = data_frequency[freq_idx]
    data_channels_fd = data_channels_fd[:, freq_idx]
    psd_channels = psd_channels[:, freq_idx]

    CovMat = np.array([[psd_channels[0], np.zeros_like(data_frequency)], [np.zeros_like(data_frequency), psd_channels[1]]]) / 4.0 * Tobs
    InvCovMat = np.linalg.inv(np.transpose(CovMat, (2, 0, 1)))
    return dict(label=label, mode=mode, tc_day=tc_day, start_day=start_day, end_day=end_day, data_time=data_time, data_channels_td=data_channels_td, dt=dt, Tobs=Tobs, data_frequency=data_frequency, data_channels_fd=data_channels_fd, psd_channels=psd_channels, CovMat=CovMat, InvCovMat=InvCovMat, psd_mode=psd_mode, psd_samples=int(psd_mask.sum()))

def print_window_summary(window: dict) -> None:
    print(f"[{window['label']}]")
    print("mode:", window["mode"])
    print("tc_day:", window["tc_day"])
    print("start_day/end_day:", window["start_day"], window["end_day"])
    print("duration_days:", (window["data_time"][-1] - window["data_time"][0]) / DAY)
    print("dt:", window["dt"])
    print("Tobs:", window["Tobs"])
    print("df median:", np.median(np.diff(window["data_frequency"])))
    print("expected 1/Tobs:", 1.0 / window["Tobs"])
    print("data_td:", window["data_channels_td"].shape)
    print("data_fd:", window["data_channels_fd"].shape)
    print("InvCovMat:", window["InvCovMat"].shape)
    print("PSD mode/samples:", window["psd_mode"], window["psd_samples"])

## 8. Build and Plot Official Baseline Window

In [9]:
baseline_window = None
if read_dict is not None:
    baseline_window = build_window_data("baseline_example4", "official_baseline", psd_mode="before")
    print_window_summary(baseline_window)
else:
    print("Skipping baseline window because data is not loaded.")

[baseline_example4]

mode: official_baseline
tc_day: 25.0
start_day/end_day: 22.5 27.5
duration_days: 5.0
dt: 10.0
Tobs: 432010.0
df median: 2.3147612323790034e-06
expected 1/Tobs: 2.31476123237888e-06
data_td: (2, 43201)
data_fd: (2, 4299)
InvCovMat: (4299, 2, 2)
PSD mode/samples: before 194400

In [10]:
def plot_window_timeseries(window: dict, filename: str) -> None:
    plt.figure(figsize=(10, 4))
    for i, name in enumerate(channel_names):
        plt.plot(window["data_time"] / DAY, window["data_channels_td"][i], lw=0.8, label=name)
    plt.axvline(window["tc_day"], color="k", ls="--", lw=1.0, label="coalescence")
    plt.xlabel("Time (day)")
    plt.ylabel("TDI")
    plt.title(window["label"])
    plt.legend()
    save_current_figure(filename)

def plot_window_frequency(window: dict, filename: str) -> None:
    plt.figure(figsize=(10, 4))
    for i, name in enumerate(channel_names):
        plt.loglog(window["data_frequency"], np.abs(window["data_channels_fd"][i]), label=f"{name} data")
        plt.loglog(window["data_frequency"], np.sqrt(window["psd_channels"][i] * window["Tobs"] / 2.0), ls="--", label=f"{name} noise level")
    plt.xlabel("Frequency (Hz)")
    plt.ylabel("TDI (1/Hz)")
    plt.title(window["label"])
    plt.legend(ncol=2)
    save_current_figure(filename)

if baseline_window is not None:
    plot_window_timeseries(baseline_window, "01_baseline_timeseries.png")
    plot_window_frequency(baseline_window, "02_baseline_frequency_psd.png")
else:
    print("Baseline plots skipped.")

Saved: figures\task5_subtask2\01_baseline_timeseries.png

Saved: figures\task5_subtask2\02_baseline_frequency_psd.png

## 9. Model Setup Shared by Both Runs

In [11]:
orbit = None
WFG = None
FDTDI = None

if ORBIT_DIR.exists() and (baseline_window is not None or DATA_DIR.exists() or PARAM_DIR.exists()):
    orbit = Orbit(OrbitDir=str(ORBIT_DIR))
    WFG = WaveformGeneratorFRef(mode="primary")
    FDTDI = FDTDIResponseGeneratorFRef(orbit_class=orbit, waveform_generator=WFG)
    print("Orbit, WF4Py waveform generator, and FDTDI response generator initialized.")
else:
    print("Model setup skipped because orbit path or data files are unavailable.")

def build_response_kwargs(window: dict, interpolation_method="cubic") -> dict:
    return dict(fmin=FMIN, fmax=FMAX, fref=1e-3, modes=[(2, 2)], tmin=window["data_time"][0]/DAY, tmax=window["data_time"][-1]/DAY, tref_at_constellation=True, TDIGeneration="2nd", optimal_combination=True, drop_T=True, interpolation_method=interpolation_method)

Orbit, WF4Py waveform generator, and FDTDI response generator initialized.

## 10. F-statistics Search and Waveform Reconstruction

This migrates official Example 4 cells 18--30.

In [12]:
def build_intrinsic_priors(response_kwargs_direct: dict) -> np.ndarray:
    return np.array([[5.0, 7.0], [0.01, 0.99], [-0.9, 0.9], [-0.9, 0.9], [response_kwargs_direct["tmin"], response_kwargs_direct["tmax"]], [0.0, TWOPI], [-1.0, 1.0]])

def run_fstat_search(window: dict, maxiter: int | None = None, popsize_factor: int = 5) -> dict:
    if FDTDI is None:
        raise RuntimeError("Initialize FDTDI before running F-statistics search.")
    if maxiter is None:
        maxiter = SMOKE_TEST_SEARCH_MAXITER if USE_SMOKE_TEST_SEARCH else OFFICIAL_SEARCH_MAXITER
    response_kwargs_interp = build_response_kwargs(window, interpolation_method="cubic")
    response_kwargs_direct = response_kwargs_interp.copy()
    response_kwargs_direct["interpolation_method"] = None
    intrinsic_param_priors = build_intrinsic_priors(response_kwargs_direct)
    Fstat = FstatisticsFref(response_generator=FDTDI, frequency=window["data_frequency"], data=window["data_channels_fd"], invserse_covariance_matrix=window["InvCovMat"], response_parameters=response_kwargs_interp, use_gpu=False)

    def cost_function(norm_int_params):
        try:
            int_params = norm_int_params * (intrinsic_param_priors[:, 1] - intrinsic_param_priors[:, 0]) + intrinsic_param_priors[:, 0]
            return -Fstat.calculate_Fstat(intrinsic_parameters=Fstat.IntParamArr2ParamDict(int_params))
        except np.linalg.LinAlgError:
            return np.inf

    n_dim_int = 7
    bounds = np.array([np.zeros(n_dim_int), np.ones(n_dim_int)]).T
    DE_result = differential_evolution(func=cost_function, bounds=bounds, x0=None, strategy="best1exp", maxiter=maxiter, popsize=popsize_factor*n_dim_int, tol=1e-6, atol=1e-8, mutation=(0.4, 0.95), recombination=0.7, disp=True, polish=False, workers=DE_WORKERS)
    searched_int_params = Fstat.IntParamArr2ParamDict(DE_result.x * (intrinsic_param_priors[:, 1] - intrinsic_param_priors[:, 0]) + intrinsic_param_priors[:, 0])
    searched_a = Fstat.calculate_Fstat(intrinsic_parameters=searched_int_params, return_a=True)
    searched_parameters = dict(searched_int_params, **Fstat.a_to_extrinsic(searched_a))
    searched_wf = FDTDI.Response(searched_parameters, window["data_frequency"], **response_kwargs_interp)
    searched_parameters_reflected = get_reflected_parameter_dict_Fref(searched_params=searched_parameters, orbit=orbit)
    searched_wf_reflected = FDTDI.Response(parameters=searched_parameters_reflected, freqs=window["data_frequency"], **response_kwargs_interp)
    save_parameter_dict(searched_parameters, f"{window['label']}_searched_parameters.json")
    save_parameter_dict(searched_parameters_reflected, f"{window['label']}_searched_parameters_reflected.json")
    return dict(Fstat=Fstat, DE_result=DE_result, searched_parameters=searched_parameters, searched_parameters_reflected=searched_parameters_reflected, searched_wf=searched_wf, searched_wf_reflected=searched_wf_reflected, response_kwargs_interp=response_kwargs_interp, response_kwargs_direct=response_kwargs_direct, intrinsic_param_priors=intrinsic_param_priors)

def plot_reconstruction(window: dict, search: dict, reflected: bool, filename: str) -> None:
    wf_key = "searched_wf_reflected" if reflected else "searched_wf"
    title = "reflected" if reflected else "direct"
    plt.figure(figsize=(12, 5))
    for i, name in enumerate(channel_names):
        plt.subplot(1, 2, i+1)
        plt.loglog(window["data_frequency"], np.abs(window["data_channels_fd"][i]), label=f"{name} data", color=BLUE, lw=3, alpha=0.5)
        plt.loglog(window["data_frequency"], np.abs(search[wf_key][i]), label=f"{name} reconstructed", color=RED, lw=1, ls="--")
        plt.loglog(window["data_frequency"], np.abs(window["data_channels_fd"][i] - search[wf_key][i]), label=f"{name} residual", color="grey", lw=1)
        plt.xlabel("Frequency (Hz)")
        plt.ylabel("TDI (1/Hz)")
        plt.ylim(1e-21, 1e-16)
        plt.legend(loc="upper left")
    plt.suptitle(f"{window['label']} reconstruction ({title})")
    save_current_figure(filename)

class CachedFisherErrors:
    def __init__(self, param_errors: dict[str, float]):
        self.param_errors = param_errors

def load_search_from_cache(window: dict) -> tuple[dict, CachedFisherErrors] | tuple[None, None]:
    param_path = RESULT_DIR / f"{window['label']}_searched_parameters.json"
    reflected_path = RESULT_DIR / f"{window['label']}_searched_parameters_reflected.json"
    fisher_path = RESULT_DIR / f"{window['label']}_fisher_errors.csv"
    if not (param_path.exists() and reflected_path.exists() and fisher_path.exists()):
        print(f"No cached search package found for {window['label']}.")
        return None, None
    if FDTDI is None:
        raise RuntimeError("Initialize FDTDI before loading cached search waveforms.")
    searched_parameters = json.loads(param_path.read_text(encoding="utf-8"))
    searched_parameters_reflected = json.loads(reflected_path.read_text(encoding="utf-8"))
    response_kwargs_interp = build_response_kwargs(window, interpolation_method="cubic")
    response_kwargs_direct = response_kwargs_interp.copy()
    response_kwargs_direct["interpolation_method"] = None
    searched_wf = FDTDI.Response(searched_parameters, window["data_frequency"], **response_kwargs_interp)
    searched_wf_reflected = FDTDI.Response(parameters=searched_parameters_reflected, freqs=window["data_frequency"], **response_kwargs_interp)
    fisher_errors = pd.read_csv(fisher_path).set_index("parameter")["fim_error"].to_dict()
    intrinsic_param_priors = build_intrinsic_priors(response_kwargs_direct)
    search = dict(Fstat=None, DE_result=None, searched_parameters=searched_parameters, searched_parameters_reflected=searched_parameters_reflected, searched_wf=searched_wf, searched_wf_reflected=searched_wf_reflected, response_kwargs_interp=response_kwargs_interp, response_kwargs_direct=response_kwargs_direct, intrinsic_param_priors=intrinsic_param_priors)
    print(f"Loaded cached search package for {window['label']} from {RESULT_DIR}.")
    return search, CachedFisherErrors(fisher_errors)

In [13]:
baseline_search = None
if RUN_BASELINE_SEARCH:
    baseline_search = run_fstat_search(baseline_window)
    plot_reconstruction(baseline_window, baseline_search, reflected=False, filename="03_baseline_reconstruction_direct.png")
    plot_reconstruction(baseline_window, baseline_search, reflected=True, filename="04_baseline_reconstruction_reflected.png")
elif USE_CACHED_SEARCH_RESULTS:
    baseline_search, baseline_FIM = load_search_from_cache(baseline_window)
else:
    print("RUN_BASELINE_SEARCH=False. Official baseline search code is present but not executed.")

Loaded cached search package for baseline_example4 from C:\Users\雷畅\Documents\Codex\2026-05-19\files-mentioned-by-the-user-2026\task5-lisa-taiji\results\task5_subtask2.

## 11. Fisher Analysis

This migrates official Example 4 cells 31--36.

In [14]:
def run_fisher_analysis(window: dict, search: dict) -> MultiChannelFisher:
    def fisher_waveform_wrapper(param_dict, frequencies):
        return FDTDI.Response(parameters=param_dict, freqs=np.array(frequencies), **search["response_kwargs_interp"])
    analyze_param_step_dict = {"chirp_mass": -10.0, "mass_ratio": -0.01, "spin_1z": -0.01, "spin_2z": -0.01, "reference_time": -0.001, "reference_phase": -0.01, "luminosity_distance": -10.0, "inclination": -0.01, "longitude": -0.01, "latitude": -0.01, "psi": -0.01}
    FIM = MultiChannelFisher(waveform_generator=fisher_waveform_wrapper, param_dict=search["searched_parameters"], analyze_param_step_dict=analyze_param_step_dict, frequency=window["data_frequency"], inverse_covariance=window["InvCovMat"], verbose=0)
    FIM.auto_test_step()
    FIM.calculate_Fisher()
    FIM.calculate_errors()
    pd.DataFrame([{"parameter": k, "fim_error": v} for k, v in FIM.param_errors.items()]).to_csv(RESULT_DIR / f"{window['label']}_fisher_errors.csv", index=False)
    return FIM

def compare_search_to_injection(window: dict, search: dict, FIM) -> pd.DataFrame:
    injected_parameters_fref = injected_parameters.copy()
    injected_parameters_fref.pop("coalescence_time", None)
    injected_parameters_fref.pop("coalescence_phase", None)
    injected_parameters_fref["reference_time"] = None
    injected_parameters_fref["reference_phase"] = None
    rows = []
    for key, truth in injected_parameters_fref.items():
        if truth is None or key not in search["searched_parameters"]:
            continue
        rows.append(dict(parameter=key, injected=truth, searched=search["searched_parameters"][key], searched_abs_error=abs(truth-search["searched_parameters"][key]), reflected=search["searched_parameters_reflected"].get(key), reflected_abs_error=abs(truth-search["searched_parameters_reflected"][key]) if key in search["searched_parameters_reflected"] else np.nan, fim_error=FIM.param_errors.get(key, np.nan)))
    df = pd.DataFrame(rows)
    df.to_csv(RESULT_DIR / f"{window['label']}_search_vs_injection.csv", index=False)
    return df

baseline_FIM = globals().get("baseline_FIM")
baseline_search_comparison = None
if baseline_search is not None:
    if baseline_FIM is None:
        baseline_FIM = run_fisher_analysis(baseline_window, baseline_search)
    baseline_search_comparison = compare_search_to_injection(baseline_window, baseline_search, baseline_FIM)
    display(baseline_search_comparison)
else:
    print("Fisher analysis waiting for baseline_search.")

,parameter,injected,searched,searched_abs_error,reflected,reflected_abs_error,fim_error
0,chirp_mass,3.000000e+06,2.997328e+06,2672.121838,2.997328e+06,2672.121838,2473.417768
1,inclination,1.256637e+00,1.884832e+00,0.628195,1.256761e+00,0.000124,0.002214
2,latitude,5.235988e-01,-7.790984e-01,1.302697,2.044097e-01,0.319189,0.259237
3,longitude,4.712389e+00,2.281439e+00,2.430950,4.649006e+00,0.063383,0.269679
4,luminosity_distance,4.768947e+04,4.434061e+04,3348.864207,4.434061e+04,3348.864207,4036.791194
5,mass_ratio,2.500000e-01,2.483229e-01,0.001677,2.483229e-01,0.001677,0.001272
6,psi,9.424778e-01,1.791783e+00,0.849305,9.537324e-01,0.011255,0.178509
7,spin_1z,4.000000e-01,4.068031e-01,0.006803,4.068031e-01,0.006803,0.007696
8,spin_2z,6.000000e-01,5.641753e-01,0.035825,5.641753e-01,0.035825,0.035738

## 12. Heterodyned Likelihood, Priors, and Nested Sampling

This migrates official Example 4 cells 37--47. The default sampler is NESSAI.

In [15]:
class BilbyLikelihoodWrapper(bilby.Likelihood):
    def __init__(self, like_object, like_type="heterodyned"):
        super().__init__(parameters={"chirp_mass": None, "mass_ratio": None, "spin_1z": None, "spin_2z": None, "reference_time": None, "reference_phase": None, "luminosity_distance": None, "inclination": None, "longitude": None, "latitude": None, "psi": None})
        self.like_object = like_object
        self.like_type = like_type
    def log_likelihood(self):
        parameter_array = ParamDict2ParamArrFref(self.parameters)
        if self.like_type == "heterodyned":
            return self.like_object.het_log_like(parameter_array=parameter_array)
        return self.like_object.full_log_like(parameter_array=parameter_array)

def build_likelihood(window: dict, search: dict) -> Likelihood:
    Like = Likelihood(response_generator=FDTDI, frequency=window["data_frequency"], data=window["data_channels_fd"], invserse_covariance_matrix=window["InvCovMat"], response_parameters=search["response_kwargs_direct"], Fref_waveform=True, use_gpu=False)
    Like.prepare_het_log_like(base_parameters=ParamDict2ParamArrFref(search["searched_parameters"]))
    return Like

def build_priors(search: dict, FIM) -> bilby.core.prior.PriorDict:
    sp, pe = search["searched_parameters"], FIM.param_errors
    priors = bilby.core.prior.PriorDict()
    nsig = FISHER_PRIOR_SIGMA
    priors["chirp_mass"] = bilby.prior.Uniform(sp["chirp_mass"]-nsig*pe["chirp_mass"], sp["chirp_mass"]+nsig*pe["chirp_mass"], name="chirp_mass", latex_label="$\\mathcal{M}_c$")
    priors["mass_ratio"] = bilby.prior.Uniform(max(0.1, sp["mass_ratio"]-nsig*pe["mass_ratio"]), min(0.99, sp["mass_ratio"]+nsig*pe["mass_ratio"]), name="mass_ratio", latex_label="$q$")
    priors["spin_1z"] = bilby.prior.Uniform(max(-0.9, sp["spin_1z"]-nsig*pe["spin_1z"]), min(0.9, sp["spin_1z"]+nsig*pe["spin_1z"]), name="spin_1z", latex_label="$\\chi_{z1}$")
    priors["spin_2z"] = bilby.prior.Uniform(max(-0.9, sp["spin_2z"]-nsig*pe["spin_2z"]), min(0.9, sp["spin_2z"]+nsig*pe["spin_2z"]), name="spin_2z", latex_label="$\\chi_{z2}$")
    priors["reference_time"] = bilby.prior.Uniform(sp["reference_time"]-nsig*pe["reference_time"], sp["reference_time"]+nsig*pe["reference_time"], name="reference_time", latex_label="$t_\\mathrm{ref}$")
    priors["reference_phase"] = bilby.prior.Uniform(0.0, TWOPI, name="reference_phase", latex_label="$\\varphi_\\mathrm{ref}$", boundary="periodic")
    priors["luminosity_distance"] = bilby.prior.Uniform(max(6e3, sp["luminosity_distance"]-nsig*pe["luminosity_distance"]), min(1e5, sp["luminosity_distance"]+nsig*pe["luminosity_distance"]), name="luminosity_distance", latex_label="$d_L$")
    priors["inclination"] = bilby.prior.Sine(minimum=0.0, maximum=PI, name="inclination", latex_label="$\\iota$")
    priors["longitude"] = bilby.prior.Uniform(0.0, TWOPI, name="longitude", latex_label="$\\lambda$", boundary="periodic")
    priors["latitude"] = bilby.prior.Cosine(minimum=-PI/2.0, maximum=PI/2.0, name="latitude", latex_label="$\\beta$")
    priors["psi"] = bilby.prior.Uniform(0.0, PI, name="psi", latex_label="$\\psi$", boundary="periodic")
    return priors

def build_injected_parameters_fref() -> dict:
    injected_parameters_fref = injected_parameters.copy()
    injected_parameters_fref.pop("coalescence_time", None)
    injected_parameters_fref.pop("coalescence_phase", None)
    injected_parameters_fref["reference_time"] = None
    injected_parameters_fref["reference_phase"] = None
    return injected_parameters_fref

PARAMETERS_TO_COMPARE = ["chirp_mass", "mass_ratio", "spin_1z", "spin_2z", "reference_time", "reference_phase", "luminosity_distance", "inclination", "longitude", "latitude", "psi"]

def run_nested_sampler(window: dict, search: dict, FIM, label: str, smoke_test: bool = True):
    if not smoke_test and "nessai" not in bilby.core.sampler.IMPLEMENTED_SAMPLERS:
        raise RuntimeError("This local bilby version does not support NESSAI. Use a Linux/conda environment with a newer bilby for the official sampler.")
    Like = build_likelihood(window, search)
    settings = SMOKE_TEST_SAMPLER_SETTINGS if smoke_test else OFFICIAL_SAMPLER_SETTINGS
    result = bilby.run_sampler(likelihood=BilbyLikelihoodWrapper(Like), priors=build_priors(search, FIM), npool=SAMPLER_POOL, injection_parameters=build_injected_parameters_fref(), outdir=str(RESULT_DIR / f"{label}_samples"), label=label, plot=False, resume=True, **settings)
    try:
        result.plot_corner(save=True)
    except Exception as exc:
        print(f"Corner plot skipped for {label}: {exc}")
    summary = posterior_summary(result.posterior, PARAMETERS_TO_COMPARE)
    summary.to_csv(RESULT_DIR / f"{label}_posterior_summary.csv", index=False)
    return result, summary

baseline_result = None
baseline_summary = None
if RUN_BASELINE_SAMPLER:
    baseline_result, baseline_summary = run_nested_sampler(baseline_window, baseline_search, baseline_FIM, label="baseline_example4", smoke_test=USE_SMOKE_TEST_SAMPLER)
else:
    print("RUN_BASELINE_SAMPLER=False. Sampler code is present but not executed.")

12:06 bilby INFO    : Running for label 'baseline_example4', output will be saved to 'C:\Users\雷畅\Documents\Codex\2026-05-19\files-mentioned-by-the-user-2026\task5-lisa-taiji\results\task5_subtask2\baseline_example4_samples'

12:06 bilby INFO    : Search parameters:

12:06 bilby INFO    :   chirp_mass = Uniform(minimum=2972593.700484618, maximum=3022062.055840342, name='chirp_mass', latex_label='$\\mathcal{M}_c$', unit=None, boundary=None)

12:06 bilby INFO    :   mass_ratio = Uniform(minimum=0.23560763338475593, maximum=0.2610381756694719, name='mass_ratio', latex_label='$q$', unit=None, boundary=None)

12:06 bilby INFO    :   spin_1z = Uniform(minimum=0.3298441350776202, maximum=0.4837619784724463, name='spin_1z', latex_label='$\\chi_{z1}$', unit=None, boundary=None)

12:06 bilby INFO    :   spin_2z = Uniform(minimum=0.20679689469386742, maximum=0.9, name='spin_2z', latex_label='$\\chi_{z2}$', unit=None, boundary=None)

12:06 bilby INFO    :   reference_time = Uniform(minimum=24.997526882905554, maximum=24.997692593308805, name='reference_time', latex_label='$t_\\mathrm{ref}$', unit=None, boundary=None)

12:06 bilby INFO    :   reference_phase = Uniform(minimum=0.0, maximum=6.283185307179586, name='reference_phase', latex_label='$\\varphi_\\mathrm{ref}$', unit=None, boundary='periodic')

12:06 bilby INFO    :   luminosity_distance = Uniform(minimum=6000.0, maximum=84708.5224613367, name='luminosity_distance', latex_label='$d_L$', unit=None, boundary=None)

12:06 bilby INFO    :   inclination = Sine(name='inclination', latex_label='$\\iota$', unit=None, minimum=0.0, maximum=3.141592653589793, boundary=None)

12:06 bilby INFO    :   longitude = Uniform(minimum=0.0, maximum=6.283185307179586, name='longitude', latex_label='$\\lambda$', unit=None, boundary='periodic')

12:06 bilby INFO    :   latitude = Cosine(name='latitude', latex_label='$\\beta$', unit=None, minimum=-1.5707963267948966, maximum=1.5707963267948966, boundary=None)

12:06 bilby INFO    :   psi = Uniform(minimum=0.0, maximum=3.141592653589793, name='psi', latex_label='$\\psi$', unit=None, boundary='periodic')

12:06 bilby INFO    : Single likelihood evaluation took 1.119e-02 s

0it [00:00, ?it/s]

12:06 bilby INFO    : Using sampler Dynesty with kwargs {'bound': 'multi', 'sample': 'rwalk', 'verbose': True, 'periodic': None, 'reflective': None, 'check_point_delta_t': 600, 'nlive': 80, 'first_update': None, 'walks': 5, 'npdim': None, 'rstate': None, 'queue_size': 1, 'pool': None, 'use_pool': None, 'live_points': None, 'logl_args': None, 'logl_kwargs': None, 'ptform_args': None, 'ptform_kwargs': None, 'enlarge': 1.5, 'bootstrap': None, 'vol_dec': 0.5, 'vol_check': 8.0, 'facc': 0.2, 'slices': 5, 'update_interval': 48, 'print_func': <bound method Dynesty._print_func of <bilby.core.sampler.dynesty.Dynesty object at 0x00000176BC8AB7D0>>, 'dlogz': 10.0, 'maxiter': None, 'maxcall': 1000, 'logl_max': inf, 'add_live': True, 'print_progress': True, 'save_bounds': False, 'n_effective': None, 'maxmcmc': 5000, 'nact': 5}

12:06 bilby INFO    : Checkpoint every check_point_delta_t = 600s

12:06 bilby INFO    : Using dynesty version 1.0.1

12:06 bilby INFO    : Generating initial points from the prior

12:06 bilby INFO    : Using the bilby-implemented rwalk sample method with ACT estimated walks

12:06 bilby INFO    : Reading resume file C:\Users\雷畅\Documents\Codex\2026-05-19\files-mentioned-by-the-user-2026\task5-lisa-taiji\results\task5_subtask2\baseline_example4_samples/baseline_example4_resume.pickle

12:06 bilby INFO    : Resume file successfully loaded.

2818it [00:02, 1396.99it/s, bound:1231 nc:  1 ncall:7.7e+04 eff:3.7% logz=594000.31+/-0.93 dlogz:9.938>10]

12:07 bilby INFO    : Written checkpoint file C:\Users\雷畅\Documents\Codex\2026-05-19\files-mentioned-by-the-user-2026\task5-lisa-taiji\results\task5_subtask2\baseline_example4_samples/baseline_example4_resume.pickle

C:\Users\雷畅\Documents\Codex\2026-05-19\files-mentioned-by-the-user-2026\task5-lisa-taiji\.venv-tdc\Lib\site-packages\dynesty\plotting.py:179: RuntimeWarning: overflow encountered in exp
  data = [nlive, np.exp(logl), np.exp(logwt), np.exp(logz)]
C:\Users\雷畅\Documents\Codex\2026-05-19\files-mentioned-by-the-user-2026\task5-lisa-taiji\.venv-tdc\Lib\site-packages\dynesty\plotting.py:203: RuntimeWarning: overflow encountered in exp
  zspan = (0., 1.05 * np.exp(logz[-1] + 3. * logzerr[-1]))

12:07 bilby WARNING : Axis limits cannot be NaN or Inf

12:07 bilby WARNING : Failed to create dynesty run plot at checkpoint

2818it [00:10, 266.07it/s, bound:1231 nc:  1 ncall:7.7e+04 eff:3.8% logz=594006.26+/-1.38 dlogz:0.516>10]

12:07 bilby INFO    : Sampling time: 0:05:39.134335

12:07 bilby INFO    : Summary of results:
nsamples: 2898
ln_noise_evidence:    nan
ln_evidence: 594006.256 +/-  1.378
ln_bayes_factor:    nan +/-  1.378

Corner plot skipped for baseline_example4: latex was not able to process the following string:
b'lp'

Here is the full command invocation and its output:

latex -interaction=nonstopmode -halt-on-error -no-shell-escape file.tex




It seems that this is a fresh TeX installation.
Please finish the setup before proceeding.
For more information, visit:
https://miktex.org/howto/install-miktex-win

## 13. Build Task-Required 5-Day Window

In [16]:
five_day_window = None
if read_dict is not None:
    five_day_window = build_window_data("task_five_day", "task_five_day", psd_mode="before")
    print_window_summary(five_day_window)
    plot_window_timeseries(five_day_window, "05_five_day_timeseries.png")
    plot_window_frequency(five_day_window, "06_five_day_frequency_psd.png")
else:
    print("Skipping 5-day window because data is not loaded.")

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

[task_five_day]
mode: task_five_day
tc_day: 25.0
start_day/end_day: 21.0 26.0
duration_days: 5.0
dt: 10.0
Tobs: 432010.0
df median: 2.3147612323790034e-06
expected 1/Tobs: 2.31476123237888e-06
data_td: (2, 43201)
data_fd: (2, 4299)
InvCovMat: (4299, 2, 2)
PSD mode/samples: before 181440

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Font family ['serif'] not found. Falling back to DejaVu Sans.

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

Saved: figures\task5_subtask2\05_five_day_timeseries.png

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

Saved: figures\task5_subtask2\06_five_day_frequency_psd.png

## 14. Run Search, Fisher, Likelihood, and Sampler on the 5-Day Window

In [17]:
five_day_search = None
five_day_FIM = None
five_day_search_comparison = None
if RUN_FIVE_DAY_SEARCH:
    five_day_search = run_fstat_search(five_day_window)
    plot_reconstruction(five_day_window, five_day_search, reflected=False, filename="07_five_day_reconstruction_direct.png")
    plot_reconstruction(five_day_window, five_day_search, reflected=True, filename="08_five_day_reconstruction_reflected.png")
    five_day_FIM = run_fisher_analysis(five_day_window, five_day_search)
    five_day_search_comparison = compare_search_to_injection(five_day_window, five_day_search, five_day_FIM)
    display(five_day_search_comparison)
elif USE_CACHED_SEARCH_RESULTS:
    five_day_search, five_day_FIM = load_search_from_cache(five_day_window)
    if five_day_search is not None:
        five_day_search_comparison = compare_search_to_injection(five_day_window, five_day_search, five_day_FIM)
        display(five_day_search_comparison)
else:
    print("RUN_FIVE_DAY_SEARCH=False. Modified-window search code is present but not executed.")

five_day_result = None
five_day_summary = None
if RUN_FIVE_DAY_SAMPLER:
    five_day_result, five_day_summary = run_nested_sampler(five_day_window, five_day_search, five_day_FIM, label="task_five_day", smoke_test=USE_SMOKE_TEST_SAMPLER)
else:
    print("RUN_FIVE_DAY_SAMPLER=False. Modified-window sampler code is present but not executed.")

Loaded cached search package for task_five_day from C:\Users\雷畅\Documents\Codex\2026-05-19\files-mentioned-by-the-user-2026\task5-lisa-taiji\results\task5_subtask2.

,parameter,injected,searched,searched_abs_error,reflected,reflected_abs_error,fim_error
0,chirp_mass,3.000000e+06,2.988490e+06,11509.851758,2.988490e+06,11509.851758,2125.604981
1,inclination,1.256637e+00,1.882945e+00,0.626308,1.258647e+00,0.002010,0.011928
2,latitude,5.235988e-01,9.959564e-02,0.424003,1.125718e+00,0.602119,0.206405
3,longitude,4.712389e+00,1.687008e+00,3.025381,5.307218e+00,0.594829,0.172382
4,luminosity_distance,4.768947e+04,3.906251e+04,8626.966055,3.906251e+04,8626.966055,6224.242637
5,mass_ratio,2.500000e-01,2.462632e-01,0.003737,2.462632e-01,0.003737,0.001197
6,psi,9.424778e-01,2.095197e+00,1.152719,1.337087e+00,0.394609,0.027849
7,spin_1z,4.000000e-01,4.062726e-01,0.006273,4.062726e-01,0.006273,0.007547
8,spin_2z,6.000000e-01,5.658009e-01,0.034199,5.658009e-01,0.034199,0.034998

12:07 bilby INFO    : Running for label 'task_five_day', output will be saved to 'C:\Users\雷畅\Documents\Codex\2026-05-19\files-mentioned-by-the-user-2026\task5-lisa-taiji\results\task5_subtask2\task_five_day_samples'

12:07 bilby INFO    : Search parameters:

12:07 bilby INFO    :   chirp_mass = Uniform(minimum=2967234.098433216, maximum=3009746.1980512487, name='chirp_mass', latex_label='$\\mathcal{M}_c$', unit=None, boundary=None)

12:07 bilby INFO    :   mass_ratio = Uniform(minimum=0.2342883529550013, maximum=0.2582380903321793, name='mass_ratio', latex_label='$q$', unit=None, boundary=None)

12:07 bilby INFO    :   spin_1z = Uniform(minimum=0.3307984309856085, maximum=0.4817467744941805, name='spin_1z', latex_label='$\\chi_{z1}$', unit=None, boundary=None)

12:07 bilby INFO    :   spin_2z = Uniform(minimum=0.21582265746425394, maximum=0.9, name='spin_2z', latex_label='$\\chi_{z2}$', unit=None, boundary=None)

12:07 bilby INFO    :   reference_time = Uniform(minimum=24.997522899515427, maximum=24.997683278340897, name='reference_time', latex_label='$t_\\mathrm{ref}$', unit=None, boundary=None)

12:07 bilby INFO    :   reference_phase = Uniform(minimum=0.0, maximum=6.283185307179586, name='reference_phase', latex_label='$\\varphi_\\mathrm{ref}$', unit=None, boundary='periodic')

12:07 bilby INFO    :   luminosity_distance = Uniform(minimum=6000.0, maximum=100000.0, name='luminosity_distance', latex_label='$d_L$', unit=None, boundary=None)

12:07 bilby INFO    :   inclination = Sine(name='inclination', latex_label='$\\iota$', unit=None, minimum=0.0, maximum=3.141592653589793, boundary=None)

12:07 bilby INFO    :   longitude = Uniform(minimum=0.0, maximum=6.283185307179586, name='longitude', latex_label='$\\lambda$', unit=None, boundary='periodic')

12:07 bilby INFO    :   latitude = Cosine(name='latitude', latex_label='$\\beta$', unit=None, minimum=-1.5707963267948966, maximum=1.5707963267948966, boundary=None)

12:07 bilby INFO    :   psi = Uniform(minimum=0.0, maximum=3.141592653589793, name='psi', latex_label='$\\psi$', unit=None, boundary='periodic')

12:07 bilby INFO    : Single likelihood evaluation took 3.056e-03 s

0it [00:00, ?it/s]

12:07 bilby INFO    : Using sampler Dynesty with kwargs {'bound': 'multi', 'sample': 'rwalk', 'verbose': True, 'periodic': None, 'reflective': None, 'check_point_delta_t': 600, 'nlive': 80, 'first_update': None, 'walks': 5, 'npdim': None, 'rstate': None, 'queue_size': 1, 'pool': None, 'use_pool': None, 'live_points': None, 'logl_args': None, 'logl_kwargs': None, 'ptform_args': None, 'ptform_kwargs': None, 'enlarge': 1.5, 'bootstrap': None, 'vol_dec': 0.5, 'vol_check': 8.0, 'facc': 0.2, 'slices': 5, 'update_interval': 48, 'print_func': <bound method Dynesty._print_func of <bilby.core.sampler.dynesty.Dynesty object at 0x00000176CF84B500>>, 'dlogz': 10.0, 'maxiter': None, 'maxcall': 1000, 'logl_max': inf, 'add_live': True, 'print_progress': True, 'save_bounds': False, 'n_effective': None, 'maxmcmc': 5000, 'nact': 5}

12:07 bilby INFO    : Checkpoint every check_point_delta_t = 600s

12:07 bilby INFO    : Using dynesty version 1.0.1

12:07 bilby INFO    : Generating initial points from the prior

12:07 bilby INFO    : Using the bilby-implemented rwalk sample method with ACT estimated walks

12:07 bilby INFO    : Resume file C:\Users\雷畅\Documents\Codex\2026-05-19\files-mentioned-by-the-user-2026\task5-lisa-taiji\results\task5_subtask2\task_five_day_samples/task_five_day_resume.pickle does not exist.

1it [00:00,  1.91it/s, bound:0 nc:  1 ncall:8.1e+01 eff:1.2% logz=-inf+/-0.36 dlogz:inf>10]

26it [00:00, 54.97it/s, bound:0 nc:  1 ncall:1.1e+02 eff:23.9% logz=-907004.38+/-0.37 dlogz:inf>10]

50it [00:00, 97.45it/s, bound:0 nc:  2 ncall:1.4e+02 eff:35.0% logz=-406196.01+/-0.38 dlogz:877096.075>10]

69it [00:00, 117.28it/s, bound:0 nc:  1 ncall:1.8e+02 eff:38.3% logz=-274389.80+/-0.38 dlogz:747389.298>10]

87it [00:00, 120.13it/s, bound:0 nc:  3 ncall:2.3e+02 eff:38.3% logz=-156499.18+/-0.39 dlogz:644978.944>10]

104it [00:01, 124.45it/s, bound:0 nc:  3 ncall:2.7e+02 eff:38.7% logz=-80291.12+/-0.40 dlogz:570063.687>10]

120it [00:01, 111.99it/s, bound:0 nc:  4 ncall:3.3e+02 eff:36.8% logz=-13604.63+/-0.40 dlogz:503134.850>10]

134it [00:01, 101.55it/s, bound:0 nc:  4 ncall:3.8e+02 eff:35.2% logz=22683.44+/-0.41 dlogz:464948.556>10]

146it [00:01, 84.02it/s, bound:0 nc: 14 ncall:4.5e+02 eff:32.3% logz=49707.67+/-0.41 dlogz:436286.501>10]

156it [00:01, 73.40it/s, bound:0 nc: 11 ncall:5.2e+02 eff:30.2% logz=78254.43+/-0.42 dlogz:408120.351>10]

165it [00:02, 70.58it/s, bound:0 nc:  8 ncall:5.7e+02 eff:29.1% logz=105296.50+/-0.42 dlogz:387447.922>10]

173it [00:02, 70.28it/s, bound:0 nc:  3 ncall:6.1e+02 eff:28.5% logz=127664.28+/-0.42 dlogz:364103.361>10]

181it [00:02, 61.81it/s, bound:0 nc:  3 ncall:6.7e+02 eff:27.1% logz=151245.89+/-0.43 dlogz:342167.103>10]

188it [00:02, 47.02it/s, bound:0 nc: 27 ncall:7.6e+02 eff:24.9% logz=178884.33+/-0.43 dlogz:314110.876>10]

194it [00:02, 42.63it/s, bound:0 nc: 12 ncall:8.2e+02 eff:23.6% logz=183696.45+/-0.43 dlogz:310324.318>10]

199it [00:02, 35.09it/s, bound:0 nc: 25 ncall:9.0e+02 eff:22.0% logz=193011.46+/-0.43 dlogz:299291.491>10]

205it [00:03, 34.87it/s, bound:0 nc: 37 ncall:9.6e+02 eff:21.3% logz=210233.58+/-0.44 dlogz:284408.255>10]

209it [00:03, 32.89it/s, bound:0 nc: 22 ncall:1.0e+03 eff:20.6% logz=224137.86+/-0.44 dlogz:270704.670>10]

213it [00:03, 33.47it/s, bound:0 nc:  2 ncall:1.1e+03 eff:20.2% logz=228939.41+/-0.44 dlogz:264545.849>10]

217it [00:03, 24.46it/s, bound:0 nc:  9 ncall:1.2e+03 eff:18.8% logz=235146.79+/-0.44 dlogz:257257.863>10]

222it [00:03, 27.49it/s, bound:0 nc: 15 ncall:1.2e+03 eff:18.5% logz=243074.00+/-0.44 dlogz:249397.283>10]

226it [00:04, 27.87it/s, bound:0 nc:  1 ncall:1.2e+03 eff:18.1% logz=256665.88+/-0.44 dlogz:243404.517>10]

230it [00:04, 25.50it/s, bound:0 nc:  4 ncall:1.3e+03 eff:17.5% logz=260546.09+/-0.44 dlogz:249149.023>10]

233it [00:04, 22.41it/s, bound:0 nc: 12 ncall:1.4e+03 eff:16.9% logz=267790.76+/-0.44 dlogz:244685.972>10]

237it [00:04, 21.64it/s, bound:0 nc: 44 ncall:1.4e+03 eff:16.3% logz=285084.47+/-0.45 dlogz:225675.132>10]

240it [00:04, 18.93it/s, bound:0 nc: 39 ncall:1.5e+03 eff:15.7% logz=288795.84+/-0.44 dlogz:219796.375>10]

243it [00:04, 20.22it/s, bound:0 nc: 15 ncall:1.6e+03 eff:15.5% logz=292523.70+/-0.45 dlogz:216822.742>10]

250it [00:05, 27.51it/s, bound:0 nc: 19 ncall:1.6e+03 eff:15.4% logz=299587.32+/-0.45 dlogz:211568.872>10]

253it [00:05, 22.23it/s, bound:0 nc: 37 ncall:1.7e+03 eff:14.9% logz=302158.65+/-0.45 dlogz:207261.541>10]

256it [00:05, 21.37it/s, bound:0 nc:  8 ncall:1.8e+03 eff:14.6% logz=309009.88+/-0.45 dlogz:203397.828>10]

259it [00:05, 19.59it/s, bound:0 nc: 23 ncall:1.8e+03 eff:14.2% logz=311669.79+/-0.45 dlogz:197606.178>10]

262it [00:05, 21.23it/s, bound:0 nc: 32 ncall:1.9e+03 eff:14.1% logz=312888.24+/-0.45 dlogz:195987.158>10]

265it [00:05, 18.26it/s, bound:0 nc: 49 ncall:1.9e+03 eff:13.7% logz=317375.85+/-0.46 dlogz:191246.807>10]

267it [00:06, 17.37it/s, bound:0 nc: 13 ncall:2.0e+03 eff:13.5% logz=322772.30+/-0.46 dlogz:186226.778>10]

271it [00:06, 21.17it/s, bound:0 nc:  8 ncall:2.0e+03 eff:13.4% logz=329269.72+/-0.46 dlogz:184888.130>10]

274it [00:06, 21.11it/s, bound:0 nc: 11 ncall:2.1e+03 eff:13.2% logz=331794.96+/-0.46 dlogz:183252.978>10]

277it [00:06, 20.99it/s, bound:0 nc: 10 ncall:2.1e+03 eff:13.1% logz=334616.86+/-0.46 dlogz:191044.562>10]

280it [00:06, 18.77it/s, bound:0 nc: 50 ncall:2.2e+03 eff:12.8% logz=340130.42+/-0.46 dlogz:185275.591>10]

282it [00:06, 17.45it/s, bound:0 nc:  9 ncall:2.2e+03 eff:12.6% logz=344306.59+/-0.46 dlogz:184838.204>10]

286it [00:07, 20.33it/s, bound:0 nc: 35 ncall:2.3e+03 eff:12.5% logz=347409.10+/-0.46 dlogz:202630.329>10]

289it [00:07, 22.17it/s, bound:0 nc:  6 ncall:2.3e+03 eff:12.4% logz=350839.00+/-0.46 dlogz:197199.396>10]

292it [00:07, 16.63it/s, bound:0 nc: 37 ncall:2.4e+03 eff:12.0% logz=354788.97+/-0.46 dlogz:193725.340>10]

294it [00:07, 13.98it/s, bound:0 nc: 63 ncall:2.5e+03 eff:11.7% logz=355637.08+/-0.47 dlogz:192358.565>10]

298it [00:07, 14.56it/s, bound:0 nc: 67 ncall:2.6e+03 eff:11.5% logz=362570.19+/-0.47 dlogz:187241.123>10]

300it [00:08, 10.25it/s, bound:0 nc: 39 ncall:2.7e+03 eff:11.0% logz=363924.96+/-0.47 dlogz:184685.166>10]

303it [00:08, 12.64it/s, bound:0 nc: 23 ncall:2.8e+03 eff:10.9% logz=369958.12+/-0.47 dlogz:178109.543>10]

307it [00:08, 16.81it/s, bound:0 nc: 12 ncall:2.8e+03 eff:10.9% logz=375933.60+/-0.47 dlogz:174140.802>10]

310it [00:09,  9.94it/s, bound:0 nc: 24 ncall:3.0e+03 eff:10.3% logz=378937.96+/-0.47 dlogz:170395.148>10]

312it [00:09,  9.84it/s, bound:0 nc: 55 ncall:3.1e+03 eff:10.1% logz=380603.36+/-0.47 dlogz:168570.508>10]

314it [00:09, 10.92it/s, bound:0 nc: 34 ncall:3.1e+03 eff:10.0% logz=382349.97+/-0.47 dlogz:166029.958>10]

316it [00:09, 11.69it/s, bound:1 nc:  6 ncall:3.2e+03 eff:10.0% logz=383602.80+/-0.47 dlogz:164915.573>10]

318it [00:09, 10.61it/s, bound:1 nc: 32 ncall:3.2e+03 eff:9.8% logz=385916.54+/-0.47 dlogz:164105.108>10]

320it [00:09, 11.31it/s, bound:2 nc: 28 ncall:3.3e+03 eff:9.8% logz=388752.59+/-0.47 dlogz:160252.534>10]

325it [00:10,  8.87it/s, bound:6 nc:178 ncall:3.5e+03 eff:9.3% logz=398563.69+/-0.48 dlogz:152742.404>10]

327it [00:10,  8.85it/s, bound:7 nc: 34 ncall:3.5e+03 eff:9.2% logz=400925.95+/-0.48 dlogz:153430.031>10]

329it [00:11,  7.14it/s, bound:8 nc: 51 ncall:3.7e+03 eff:8.9% logz=405729.78+/-0.48 dlogz:147554.593>10]

330it [00:11,  7.15it/s, bound:9 nc: 42 ncall:3.7e+03 eff:8.8% logz=406467.99+/-0.48 dlogz:146499.692>10]

331it [00:11,  7.35it/s, bound:9 nc: 37 ncall:3.8e+03 eff:8.8% logz=409073.03+/-0.48 dlogz:145761.468>10]

332it [00:11,  7.54it/s, bound:10 nc: 37 ncall:3.8e+03 eff:8.7% logz=409094.14+/-0.48 dlogz:143156.412>10]

334it [00:11,  8.48it/s, bound:11 nc: 26 ncall:3.9e+03 eff:8.6% logz=410411.52+/-0.48 dlogz:142735.856>10]

336it [00:12,  8.86it/s, bound:12 nc: 39 ncall:3.9e+03 eff:8.5% logz=414189.20+/-0.48 dlogz:140641.246>10]

338it [00:12,  9.28it/s, bound:13 nc: 45 ncall:4.0e+03 eff:8.5% logz=415754.13+/-0.48 dlogz:136968.833>10]

339it [00:12,  6.75it/s, bound:14 nc:103 ncall:4.1e+03 eff:8.3% logz=416979.04+/-0.48 dlogz:136902.330>10]

340it [00:12,  7.17it/s, bound:14 nc: 37 ncall:4.1e+03 eff:8.2% logz=419848.79+/-0.48 dlogz:135677.403>10]

342it [00:12,  8.35it/s, bound:15 nc: 39 ncall:4.2e+03 eff:8.2% logz=421724.25+/-0.46 dlogz:132010.101>10]

344it [00:13,  9.55it/s, bound:16 nc: 21 ncall:4.2e+03 eff:8.1% logz=422710.65+/-0.48 dlogz:130362.408>10]

346it [00:13, 10.78it/s, bound:17 nc: 20 ncall:4.3e+03 eff:8.1% logz=423499.82+/-0.48 dlogz:129635.966>10]

348it [00:13, 12.66it/s, bound:18 nc: 11 ncall:4.3e+03 eff:8.1% logz=424394.73+/-0.48 dlogz:128546.567>10]

350it [00:13, 12.92it/s, bound:19 nc: 16 ncall:4.4e+03 eff:8.0% logz=424421.51+/-0.48 dlogz:128245.540>10]

353it [00:13, 14.60it/s, bound:19 nc: 29 ncall:4.4e+03 eff:8.0% logz=426721.73+/-0.48 dlogz:126747.477>10]

355it [00:13, 12.22it/s, bound:20 nc: 53 ncall:4.5e+03 eff:7.9% logz=426871.81+/-0.49 dlogz:125901.017>10]

357it [00:14, 10.77it/s, bound:21 nc: 55 ncall:4.6e+03 eff:7.8% logz=429659.57+/-0.49 dlogz:125256.226>10]

359it [00:14, 11.21it/s, bound:22 nc: 28 ncall:4.6e+03 eff:7.7% logz=431348.74+/-0.49 dlogz:122656.608>10]

361it [00:14, 11.50it/s, bound:23 nc: 28 ncall:4.7e+03 eff:7.7% logz=433268.30+/-0.49 dlogz:119567.649>10]

363it [00:14, 11.75it/s, bound:24 nc: 21 ncall:4.7e+03 eff:7.6% logz=436085.65+/-0.49 dlogz:118493.738>10]

365it [00:14, 12.75it/s, bound:25 nc: 17 ncall:4.8e+03 eff:7.6% logz=438836.31+/-0.49 dlogz:115738.841>10]

367it [00:14, 13.46it/s, bound:26 nc: 21 ncall:4.8e+03 eff:7.6% logz=439630.52+/-0.49 dlogz:113839.522>10]

369it [00:14, 14.17it/s, bound:26 nc: 26 ncall:4.9e+03 eff:7.6% logz=441072.41+/-0.49 dlogz:112708.647>10]

371it [00:15, 13.11it/s, bound:27 nc: 30 ncall:4.9e+03 eff:7.5% logz=444043.54+/-0.49 dlogz:109840.319>10]

373it [00:15, 12.24it/s, bound:28 nc: 47 ncall:5.0e+03 eff:7.5% logz=447643.51+/-0.49 dlogz:105428.936>10]

375it [00:15, 11.60it/s, bound:29 nc: 35 ncall:5.1e+03 eff:7.4% logz=450335.77+/-0.49 dlogz:103437.230>10]

377it [00:15,  9.72it/s, bound:31 nc: 42 ncall:5.2e+03 eff:7.3% logz=451971.03+/-0.49 dlogz:101261.703>10]

379it [00:16,  9.16it/s, bound:32 nc: 37 ncall:5.2e+03 eff:7.2% logz=452501.16+/-0.49 dlogz:100439.937>10]

381it [00:16, 10.21it/s, bound:33 nc: 17 ncall:5.3e+03 eff:7.2% logz=453839.18+/-0.49 dlogz:99489.359>10]

383it [00:16, 11.86it/s, bound:33 nc: 22 ncall:5.3e+03 eff:7.2% logz=457465.17+/-0.49 dlogz:97351.818>10]

385it [00:16, 11.49it/s, bound:34 nc: 34 ncall:5.4e+03 eff:7.1% logz=458434.37+/-0.49 dlogz:94810.989>10]

387it [00:16, 11.96it/s, bound:35 nc: 25 ncall:5.4e+03 eff:7.1% logz=458742.66+/-0.50 dlogz:94470.312>10]

389it [00:16, 10.05it/s, bound:37 nc: 36 ncall:5.5e+03 eff:7.0% logz=463097.04+/-0.50 dlogz:90379.327>10]

391it [00:17, 10.72it/s, bound:38 nc: 33 ncall:5.6e+03 eff:7.0% logz=463677.03+/-0.50 dlogz:89317.365>10]

393it [00:17,  9.91it/s, bound:39 nc: 40 ncall:5.7e+03 eff:6.9% logz=466766.40+/-0.50 dlogz:106636.110>10]

395it [00:17, 10.12it/s, bound:40 nc: 37 ncall:5.7e+03 eff:6.9% logz=468298.11+/-0.50 dlogz:105622.236>10]

397it [00:17, 10.52it/s, bound:41 nc: 34 ncall:5.8e+03 eff:6.9% logz=468908.04+/-0.50 dlogz:103952.680>10]

399it [00:17, 10.58it/s, bound:42 nc: 40 ncall:5.8e+03 eff:6.8% logz=471054.59+/-0.50 dlogz:102194.515>10]

401it [00:17, 11.37it/s, bound:43 nc: 27 ncall:5.9e+03 eff:6.8% logz=475819.36+/-0.50 dlogz:100498.658>10]

403it [00:18, 11.77it/s, bound:44 nc: 31 ncall:5.9e+03 eff:6.8% logz=476214.89+/-0.50 dlogz:96858.029>10]

405it [00:18, 11.77it/s, bound:45 nc: 38 ncall:6.0e+03 eff:6.7% logz=477135.33+/-0.50 dlogz:95993.450>10]

407it [00:18,  9.66it/s, bound:46 nc: 60 ncall:6.1e+03 eff:6.7% logz=478612.88+/-0.50 dlogz:95599.647>10]

409it [00:18,  9.89it/s, bound:47 nc: 35 ncall:6.2e+03 eff:6.6% logz=480526.37+/-0.50 dlogz:93344.944>10]

411it [00:19,  7.57it/s, bound:49 nc:105 ncall:6.3e+03 eff:6.5% logz=482428.98+/-0.50 dlogz:90496.877>10]

413it [00:19,  8.40it/s, bound:50 nc: 35 ncall:6.4e+03 eff:6.5% logz=484335.41+/-0.50 dlogz:89699.782>10]

415it [00:19,  9.37it/s, bound:51 nc: 28 ncall:6.4e+03 eff:6.5% logz=484934.34+/-0.50 dlogz:87912.009>10]

417it [00:19,  8.36it/s, bound:52 nc: 66 ncall:6.5e+03 eff:6.4% logz=487608.54+/-0.50 dlogz:86890.857>10]

419it [00:20,  8.54it/s, bound:53 nc: 55 ncall:6.6e+03 eff:6.4% logz=489282.61+/-0.51 dlogz:83771.244>10]

420it [00:20,  7.78it/s, bound:54 nc: 60 ncall:6.6e+03 eff:6.3% logz=489616.35+/-0.51 dlogz:83494.988>10]

421it [00:20,  7.04it/s, bound:55 nc: 63 ncall:6.7e+03 eff:6.3% logz=490349.56+/-0.51 dlogz:83161.235>10]

422it [00:20,  7.43it/s, bound:56 nc: 36 ncall:6.7e+03 eff:6.3% logz=491154.60+/-0.51 dlogz:82428.016>10]

424it [00:20,  8.35it/s, bound:57 nc: 32 ncall:6.8e+03 eff:6.2% logz=491492.19+/-0.51 dlogz:81543.049>10]

425it [00:20,  6.93it/s, bound:57 nc: 77 ncall:6.9e+03 eff:6.2% logz=491886.69+/-0.51 dlogz:81285.348>10]

427it [00:21,  7.83it/s, bound:58 nc: 40 ncall:7.0e+03 eff:6.1% logz=492159.75+/-0.51 dlogz:80750.201>10]

429it [00:21,  8.90it/s, bound:59 nc: 34 ncall:7.0e+03 eff:6.1% logz=492881.74+/-0.51 dlogz:80503.778>10]

430it [00:21,  8.82it/s, bound:60 nc: 40 ncall:7.0e+03 eff:6.1% logz=493006.49+/-0.51 dlogz:79895.737>10]

432it [00:21, 10.43it/s, bound:61 nc: 22 ncall:7.1e+03 eff:6.1% logz=495381.23+/-0.51 dlogz:77498.075>10]

434it [00:21, 10.75it/s, bound:62 nc: 17 ncall:7.2e+03 eff:6.1% logz=496554.92+/-0.51 dlogz:76401.758>10]

436it [00:21,  9.92it/s, bound:63 nc: 40 ncall:7.2e+03 eff:6.0% logz=499344.86+/-0.49 dlogz:74154.453>10]

438it [00:22,  9.60it/s, bound:64 nc: 34 ncall:7.3e+03 eff:6.0% logz=501207.78+/-0.51 dlogz:73158.697>10]

439it [00:22,  9.52it/s, bound:64 nc: 36 ncall:7.3e+03 eff:6.0% logz=502008.00+/-0.51 dlogz:71569.589>10]

441it [00:22,  8.24it/s, bound:65 nc: 73 ncall:7.4e+03 eff:5.9% logz=502479.98+/-0.51 dlogz:70476.507>10]

442it [00:22,  8.39it/s, bound:66 nc: 35 ncall:7.5e+03 eff:5.9% logz=502671.13+/-0.51 dlogz:70297.344>10]

444it [00:23,  6.16it/s, bound:69 nc:130 ncall:7.6e+03 eff:5.8% logz=504050.10+/-0.51 dlogz:69736.039>10]

445it [00:23,  6.53it/s, bound:69 nc: 39 ncall:7.7e+03 eff:5.8% logz=504201.13+/-0.51 dlogz:68727.192>10]

447it [00:23,  8.24it/s, bound:70 nc: 24 ncall:7.7e+03 eff:5.8% logz=504856.48+/-0.51 dlogz:68471.923>10]

449it [00:23,  8.25it/s, bound:71 nc: 51 ncall:7.8e+03 eff:5.8% logz=505307.95+/-0.51 dlogz:67669.683>10]

451it [00:23,  9.12it/s, bound:72 nc: 38 ncall:7.9e+03 eff:5.7% logz=507216.72+/-0.52 dlogz:66023.764>10]

453it [00:24,  9.04it/s, bound:73 nc: 36 ncall:7.9e+03 eff:5.7% logz=508579.86+/-0.52 dlogz:64656.088>10]

455it [00:24,  9.79it/s, bound:74 nc: 38 ncall:8.0e+03 eff:5.7% logz=509069.54+/-0.52 dlogz:64159.323>10]

457it [00:24,  9.43it/s, bound:75 nc: 40 ncall:8.1e+03 eff:5.7% logz=510446.24+/-0.52 dlogz:63489.389>10]

459it [00:24,  8.35it/s, bound:76 nc: 68 ncall:8.2e+03 eff:5.6% logz=510970.56+/-0.52 dlogz:62074.570>10]

460it [00:25,  6.62it/s, bound:78 nc: 96 ncall:8.3e+03 eff:5.6% logz=511120.36+/-0.52 dlogz:61806.540>10]

462it [00:25,  7.76it/s, bound:79 nc: 31 ncall:8.3e+03 eff:5.6% logz=512207.78+/-0.52 dlogz:60601.374>10]

463it [00:25,  8.06it/s, bound:79 nc: 35 ncall:8.4e+03 eff:5.5% logz=512326.48+/-0.52 dlogz:60569.289>10]

464it [00:25,  8.20it/s, bound:80 nc: 38 ncall:8.4e+03 eff:5.5% logz=512697.91+/-0.52 dlogz:60450.572>10]

466it [00:25,  8.91it/s, bound:81 nc: 39 ncall:8.5e+03 eff:5.5% logz=512897.49+/-0.52 dlogz:60077.977>10]

468it [00:25,  9.35it/s, bound:82 nc: 39 ncall:8.5e+03 eff:5.5% logz=513153.70+/-0.52 dlogz:59791.608>10]

470it [00:26,  9.76it/s, bound:83 nc: 37 ncall:8.6e+03 eff:5.5% logz=514510.94+/-0.52 dlogz:65556.997>10]

472it [00:26,  8.55it/s, bound:84 nc: 66 ncall:8.7e+03 eff:5.4% logz=515281.44+/-0.52 dlogz:63881.991>10]

473it [00:26,  8.60it/s, bound:85 nc: 34 ncall:8.7e+03 eff:5.4% logz=515442.48+/-0.52 dlogz:63441.474>10]

475it [00:26,  8.77it/s, bound:86 nc: 40 ncall:8.8e+03 eff:5.4% logz=515931.42+/-0.52 dlogz:62829.046>10]

476it [00:26,  8.94it/s, bound:86 nc: 34 ncall:8.8e+03 eff:5.4% logz=516232.31+/-0.52 dlogz:62791.453>10]

477it [00:26,  8.73it/s, bound:87 nc: 40 ncall:8.9e+03 eff:5.4% logz=516419.26+/-0.52 dlogz:62490.553>10]

478it [00:27,  7.38it/s, bound:87 nc: 66 ncall:8.9e+03 eff:5.4% logz=516725.27+/-0.52 dlogz:62303.593>10]

479it [00:27,  7.82it/s, bound:88 nc: 29 ncall:9.0e+03 eff:5.4% logz=517390.67+/-0.52 dlogz:61997.567>10]

480it [00:27,  7.82it/s, bound:88 nc: 41 ncall:9.0e+03 eff:5.3% logz=517648.03+/-0.52 dlogz:61332.155>10]

481it [00:27,  7.94it/s, bound:89 nc: 36 ncall:9.0e+03 eff:5.3% logz=517674.75+/-0.52 dlogz:61074.780>10]

483it [00:27,  9.54it/s, bound:90 nc: 25 ncall:9.1e+03 eff:5.3% logz=517746.56+/-0.52 dlogz:61035.857>10]

485it [00:27, 10.11it/s, bound:90 nc: 40 ncall:9.1e+03 eff:5.3% logz=518093.02+/-0.53 dlogz:60877.373>10]

487it [00:28,  9.91it/s, bound:91 nc: 35 ncall:9.2e+03 eff:5.3% logz=519632.40+/-0.53 dlogz:60516.008>10]

488it [00:28,  9.15it/s, bound:92 nc: 40 ncall:9.2e+03 eff:5.3% logz=519775.29+/-0.53 dlogz:59090.331>10]

489it [00:28,  8.92it/s, bound:92 nc: 40 ncall:9.3e+03 eff:5.3% logz=520185.79+/-0.53 dlogz:58947.425>10]

490it [00:28,  8.55it/s, bound:93 nc: 40 ncall:9.3e+03 eff:5.3% logz=520232.72+/-0.51 dlogz:58536.907>10]

491it [00:28,  8.58it/s, bound:93 nc: 38 ncall:9.4e+03 eff:5.2% logz=520489.55+/-0.53 dlogz:58489.972>10]

492it [00:28,  8.48it/s, bound:94 nc: 40 ncall:9.4e+03 eff:5.2% logz=521345.90+/-0.53 dlogz:58233.125>10]

493it [00:28,  8.47it/s, bound:94 nc: 40 ncall:9.4e+03 eff:5.2% logz=521373.47+/-0.53 dlogz:57376.760>10]

495it [00:28,  9.82it/s, bound:95 nc: 40 ncall:9.5e+03 eff:5.2% logz=521665.08+/-0.53 dlogz:57314.305>10]

497it [00:29, 10.38it/s, bound:96 nc: 29 ncall:9.6e+03 eff:5.2% logz=521960.40+/-0.53 dlogz:56914.204>10]

499it [00:29, 10.18it/s, bound:97 nc: 30 ncall:9.6e+03 eff:5.2% logz=522367.36+/-0.53 dlogz:56523.778>10]

501it [00:29,  9.55it/s, bound:98 nc: 40 ncall:9.7e+03 eff:5.2% logz=523548.09+/-0.53 dlogz:55946.535>10]

503it [00:29,  9.97it/s, bound:99 nc: 40 ncall:9.8e+03 eff:5.2% logz=523807.97+/-0.53 dlogz:63024.932>10]

505it [00:29, 10.79it/s, bound:100 nc: 25 ncall:9.8e+03 eff:5.1% logz=524114.18+/-0.53 dlogz:62653.070>10]

507it [00:30,  9.80it/s, bound:101 nc: 40 ncall:9.9e+03 eff:5.1% logz=524804.38+/-0.53 dlogz:62454.755>10]

509it [00:30,  9.93it/s, bound:102 nc: 26 ncall:1.0e+04 eff:5.1% logz=525195.07+/-0.53 dlogz:61609.696>10]

511it [00:30,  9.50it/s, bound:103 nc: 36 ncall:1.0e+04 eff:5.1% logz=526080.62+/-0.53 dlogz:60644.815>10]

512it [00:30,  9.44it/s, bound:104 nc: 36 ncall:1.0e+04 eff:5.1% logz=526914.02+/-0.53 dlogz:60578.676>10]

513it [00:30,  9.30it/s, bound:104 nc: 39 ncall:1.0e+04 eff:5.1% logz=528004.76+/-0.53 dlogz:59745.267>10]

514it [00:30,  9.32it/s, bound:105 nc: 33 ncall:1.0e+04 eff:5.1% logz=528357.08+/-0.53 dlogz:58654.513>10]

516it [00:31,  9.24it/s, bound:106 nc: 40 ncall:1.0e+04 eff:5.0% logz=529019.87+/-0.53 dlogz:57659.272>10]

518it [00:31, 10.54it/s, bound:107 nc: 29 ncall:1.0e+04 eff:5.0% logz=531121.10+/-0.53 dlogz:57092.181>10]

520it [00:31,  9.63it/s, bound:108 nc: 40 ncall:1.0e+04 eff:5.0% logz=531926.62+/-0.52 dlogz:55123.428>10]

521it [00:31,  9.36it/s, bound:108 nc: 40 ncall:1.0e+04 eff:5.0% logz=532855.41+/-0.54 dlogz:54732.563>10]

523it [00:31, 10.58it/s, bound:109 nc: 29 ncall:1.0e+04 eff:5.0% logz=533460.90+/-0.54 dlogz:53775.364>10]

525it [00:31, 10.57it/s, bound:110 nc: 26 ncall:1.0e+04 eff:5.0% logz=533926.16+/-0.54 dlogz:56034.445>10]

527it [00:32,  9.94it/s, bound:111 nc: 35 ncall:1.1e+04 eff:5.0% logz=535140.54+/-0.54 dlogz:55087.149>10]

529it [00:32, 10.34it/s, bound:112 nc: 27 ncall:1.1e+04 eff:5.0% logz=535684.62+/-0.54 dlogz:54469.827>10]

531it [00:32,  9.96it/s, bound:113 nc: 40 ncall:1.1e+04 eff:5.0% logz=535836.67+/-0.54 dlogz:54093.281>10]

533it [00:32, 10.33it/s, bound:114 nc: 40 ncall:1.1e+04 eff:5.0% logz=536351.37+/-0.54 dlogz:53865.563>10]

535it [00:32, 10.77it/s, bound:115 nc: 31 ncall:1.1e+04 eff:4.9% logz=536631.78+/-0.54 dlogz:53283.008>10]

537it [00:33, 10.77it/s, bound:116 nc: 32 ncall:1.1e+04 eff:4.9% logz=536845.28+/-0.54 dlogz:53059.911>10]

539it [00:33,  9.83it/s, bound:117 nc: 40 ncall:1.1e+04 eff:4.9% logz=537423.43+/-0.54 dlogz:52914.236>10]

541it [00:33,  9.58it/s, bound:118 nc: 34 ncall:1.1e+04 eff:4.9% logz=538069.05+/-0.54 dlogz:51969.737>10]

542it [00:33,  9.56it/s, bound:118 nc: 35 ncall:1.1e+04 eff:4.9% logz=538162.29+/-0.54 dlogz:51830.462>10]

543it [00:33,  9.28it/s, bound:119 nc: 39 ncall:1.1e+04 eff:4.9% logz=538260.01+/-0.54 dlogz:51737.213>10]

545it [00:33,  9.63it/s, bound:120 nc: 36 ncall:1.1e+04 eff:4.9% logz=538819.91+/-0.54 dlogz:51589.001>10]

546it [00:34,  9.66it/s, bound:120 nc: 35 ncall:1.1e+04 eff:4.9% logz=538884.63+/-0.54 dlogz:51079.552>10]

547it [00:34,  9.62it/s, bound:121 nc: 34 ncall:1.1e+04 eff:4.9% logz=538896.35+/-0.54 dlogz:51014.821>10]

549it [00:34, 10.41it/s, bound:122 nc: 40 ncall:1.1e+04 eff:4.9% logz=538906.68+/-0.54 dlogz:50998.478>10]

551it [00:34,  9.83it/s, bound:123 nc: 25 ncall:1.1e+04 eff:4.9% logz=539482.84+/-0.53 dlogz:50883.748>10]

552it [00:34,  8.12it/s, bound:123 nc: 68 ncall:1.1e+04 eff:4.8% logz=539739.17+/-0.54 dlogz:50416.550>10]

553it [00:34,  8.13it/s, bound:124 nc: 40 ncall:1.1e+04 eff:4.8% logz=539890.07+/-0.54 dlogz:50160.207>10]

554it [00:35,  8.03it/s, bound:124 nc: 39 ncall:1.2e+04 eff:4.8% logz=539893.47+/-0.54 dlogz:50009.298>10]

555it [00:35,  8.07it/s, bound:125 nc: 40 ncall:1.2e+04 eff:4.8% logz=540033.54+/-0.55 dlogz:50005.887>10]

556it [00:35,  8.42it/s, bound:125 nc: 35 ncall:1.2e+04 eff:4.8% logz=540153.19+/-0.55 dlogz:49865.804>10]

557it [00:35,  8.24it/s, bound:126 nc: 40 ncall:1.2e+04 eff:4.8% logz=540380.81+/-0.55 dlogz:49746.144>10]

558it [00:35,  8.21it/s, bound:126 nc: 40 ncall:1.2e+04 eff:4.8% logz=540645.93+/-0.55 dlogz:49518.506>10]

559it [00:35,  8.23it/s, bound:127 nc: 40 ncall:1.2e+04 eff:4.8% logz=541139.33+/-0.55 dlogz:49253.374>10]

560it [00:35,  8.46it/s, bound:127 nc: 37 ncall:1.2e+04 eff:4.8% logz=541516.01+/-0.55 dlogz:48759.968>10]

561it [00:35,  8.43it/s, bound:128 nc: 38 ncall:1.2e+04 eff:4.8% logz=541823.46+/-0.55 dlogz:48383.274>10]

562it [00:35,  8.84it/s, bound:128 nc: 34 ncall:1.2e+04 eff:4.8% logz=541902.38+/-0.55 dlogz:48075.804>10]

563it [00:36,  8.74it/s, bound:129 nc: 39 ncall:1.2e+04 eff:4.8% logz=541906.52+/-0.54 dlogz:47996.872>10]

564it [00:36,  7.09it/s, bound:129 nc: 67 ncall:1.2e+04 eff:4.7% logz=541988.72+/-0.55 dlogz:47992.723>10]

566it [00:36,  8.31it/s, bound:130 nc: 34 ncall:1.2e+04 eff:4.7% logz=542130.24+/-0.55 dlogz:47853.933>10]

567it [00:36,  8.32it/s, bound:131 nc: 40 ncall:1.2e+04 eff:4.7% logz=542356.42+/-0.55 dlogz:47768.961>10]

569it [00:36,  9.53it/s, bound:132 nc: 26 ncall:1.2e+04 eff:4.7% logz=542962.36+/-0.55 dlogz:47332.366>10]

570it [00:36,  9.24it/s, bound:132 nc: 40 ncall:1.2e+04 eff:4.7% logz=543364.91+/-0.55 dlogz:46936.808>10]

571it [00:37,  8.95it/s, bound:133 nc: 40 ncall:1.2e+04 eff:4.7% logz=543637.99+/-0.55 dlogz:46534.242>10]

572it [00:37,  8.84it/s, bound:133 nc: 40 ncall:1.2e+04 eff:4.7% logz=543677.75+/-0.55 dlogz:46261.156>10]

573it [00:37,  8.65it/s, bound:134 nc: 40 ncall:1.2e+04 eff:4.7% logz=543744.25+/-0.55 dlogz:46221.386>10]

574it [00:37,  8.70it/s, bound:134 nc: 38 ncall:1.2e+04 eff:4.7% logz=543746.10+/-0.53 dlogz:46154.868>10]

575it [00:37,  8.54it/s, bound:135 nc: 40 ncall:1.2e+04 eff:4.7% logz=544163.01+/-0.55 dlogz:46153.007>10]

576it [00:37,  8.59it/s, bound:135 nc: 38 ncall:1.2e+04 eff:4.7% logz=544166.87+/-0.55 dlogz:45736.084>10]

577it [00:37,  8.58it/s, bound:136 nc: 38 ncall:1.2e+04 eff:4.7% logz=544177.45+/-0.54 dlogz:45732.215>10]

578it [00:37,  8.77it/s, bound:136 nc: 36 ncall:1.2e+04 eff:4.7% logz=544655.29+/-0.55 dlogz:45721.623>10]

579it [00:37,  8.60it/s, bound:137 nc: 40 ncall:1.2e+04 eff:4.6% logz=544763.94+/-0.55 dlogz:45243.763>10]

580it [00:38,  7.49it/s, bound:137 nc: 58 ncall:1.3e+04 eff:4.6% logz=544969.30+/-0.55 dlogz:45135.099>10]

582it [00:38,  8.76it/s, bound:138 nc: 40 ncall:1.3e+04 eff:4.6% logz=545166.97+/-0.55 dlogz:44910.765>10]

583it [00:38,  7.33it/s, bound:139 nc: 66 ncall:1.3e+04 eff:4.6% logz=545436.47+/-0.55 dlogz:44732.039>10]

584it [00:38,  7.58it/s, bound:140 nc: 40 ncall:1.3e+04 eff:4.6% logz=545472.11+/-0.55 dlogz:44462.529>10]

585it [00:38,  7.76it/s, bound:140 nc: 40 ncall:1.3e+04 eff:4.6% logz=545847.15+/-0.55 dlogz:44426.873>10]

586it [00:38,  7.89it/s, bound:141 nc: 40 ncall:1.3e+04 eff:4.6% logz=545881.90+/-0.55 dlogz:44051.820>10]

587it [00:38,  8.28it/s, bound:141 nc: 35 ncall:1.3e+04 eff:4.6% logz=545897.29+/-0.55 dlogz:44017.058>10]

588it [00:39,  8.35it/s, bound:142 nc: 39 ncall:1.3e+04 eff:4.6% logz=546238.82+/-0.55 dlogz:44001.655>10]

589it [00:39,  8.61it/s, bound:142 nc: 36 ncall:1.3e+04 eff:4.6% logz=546801.85+/-0.55 dlogz:43660.117>10]

590it [00:39,  6.67it/s, bound:143 nc: 76 ncall:1.3e+04 eff:4.6% logz=546931.75+/-0.56 dlogz:43097.072>10]

591it [00:39,  7.06it/s, bound:144 nc: 40 ncall:1.3e+04 eff:4.5% logz=546961.23+/-0.56 dlogz:42967.161>10]

592it [00:39,  7.41it/s, bound:144 nc: 40 ncall:1.3e+04 eff:4.5% logz=547083.82+/-0.56 dlogz:42937.666>10]

593it [00:39,  7.64it/s, bound:145 nc: 40 ncall:1.3e+04 eff:4.5% logz=547303.10+/-0.56 dlogz:42815.062>10]

595it [00:40,  8.45it/s, bound:146 nc: 38 ncall:1.3e+04 eff:4.5% logz=547519.22+/-0.56 dlogz:42588.460>10]

596it [00:40,  8.47it/s, bound:146 nc: 39 ncall:1.3e+04 eff:4.5% logz=547615.35+/-0.56 dlogz:42379.621>10]

597it [00:40,  8.34it/s, bound:147 nc: 40 ncall:1.3e+04 eff:4.5% logz=547672.11+/-0.56 dlogz:42283.486>10]

599it [00:40,  9.22it/s, bound:148 nc: 35 ncall:1.3e+04 eff:4.5% logz=547770.91+/-0.56 dlogz:42160.535>10]

600it [00:40,  8.95it/s, bound:148 nc: 40 ncall:1.3e+04 eff:4.5% logz=547849.94+/-0.56 dlogz:42127.884>10]

601it [00:40,  8.97it/s, bound:149 nc: 35 ncall:1.3e+04 eff:4.5% logz=547999.59+/-0.56 dlogz:42048.842>10]

602it [00:40,  8.79it/s, bound:149 nc: 40 ncall:1.3e+04 eff:4.5% logz=548294.17+/-0.54 dlogz:41899.182>10]

603it [00:40,  8.67it/s, bound:150 nc: 40 ncall:1.3e+04 eff:4.5% logz=548379.11+/-0.56 dlogz:41604.588>10]

605it [00:41,  9.61it/s, bound:151 nc: 26 ncall:1.3e+04 eff:4.5% logz=548674.09+/-0.56 dlogz:41264.995>10]

606it [00:41,  9.28it/s, bound:151 nc: 40 ncall:1.4e+04 eff:4.5% logz=549105.59+/-0.56 dlogz:41224.634>10]

607it [00:41,  9.42it/s, bound:152 nc: 33 ncall:1.4e+04 eff:4.5% logz=549265.62+/-0.56 dlogz:40793.119>10]

608it [00:41,  9.08it/s, bound:152 nc: 40 ncall:1.4e+04 eff:4.5% logz=549624.04+/-0.56 dlogz:40633.072>10]

609it [00:41,  8.87it/s, bound:153 nc: 40 ncall:1.4e+04 eff:4.5% logz=549634.57+/-0.56 dlogz:40274.646>10]

610it [00:41,  8.87it/s, bound:153 nc: 38 ncall:1.4e+04 eff:4.5% logz=549684.07+/-0.56 dlogz:40264.104>10]

611it [00:41,  8.74it/s, bound:154 nc: 39 ncall:1.4e+04 eff:4.5% logz=549740.62+/-0.56 dlogz:40214.588>10]

612it [00:41,  8.85it/s, bound:154 nc: 37 ncall:1.4e+04 eff:4.4% logz=549855.23+/-0.56 dlogz:40158.025>10]

614it [00:42,  9.84it/s, bound:155 nc: 27 ncall:1.4e+04 eff:4.4% logz=550062.91+/-0.56 dlogz:39998.007>10]

615it [00:42,  7.75it/s, bound:156 nc: 69 ncall:1.4e+04 eff:4.4% logz=550485.85+/-0.56 dlogz:39835.699>10]

616it [00:42,  7.87it/s, bound:157 nc: 40 ncall:1.4e+04 eff:4.4% logz=550548.50+/-0.56 dlogz:39412.748>10]

617it [00:42,  8.01it/s, bound:157 nc: 40 ncall:1.4e+04 eff:4.4% logz=550619.03+/-0.56 dlogz:39350.089>10]

618it [00:42,  8.27it/s, bound:158 nc: 37 ncall:1.4e+04 eff:4.4% logz=550869.96+/-0.56 dlogz:39279.544>10]

619it [00:42,  8.31it/s, bound:158 nc: 40 ncall:1.4e+04 eff:4.4% logz=550929.40+/-0.56 dlogz:39028.600>10]

620it [00:42,  8.27it/s, bound:159 nc: 40 ncall:1.4e+04 eff:4.4% logz=550982.30+/-0.56 dlogz:38969.146>10]

621it [00:42,  8.60it/s, bound:159 nc: 36 ncall:1.4e+04 eff:4.4% logz=551097.48+/-0.56 dlogz:38916.233>10]

622it [00:43,  8.49it/s, bound:160 nc: 40 ncall:1.4e+04 eff:4.4% logz=551270.82+/-0.56 dlogz:38801.043>10]

623it [00:43,  8.45it/s, bound:160 nc: 40 ncall:1.4e+04 eff:4.4% logz=551430.74+/-0.56 dlogz:38627.686>10]

624it [00:43,  8.25it/s, bound:161 nc: 40 ncall:1.4e+04 eff:4.4% logz=551565.95+/-0.56 dlogz:38467.757>10]

625it [00:43,  8.26it/s, bound:161 nc: 40 ncall:1.4e+04 eff:4.4% logz=551685.53+/-0.56 dlogz:38332.536>10]

626it [00:43,  8.29it/s, bound:162 nc: 40 ncall:1.4e+04 eff:4.4% logz=551735.27+/-0.57 dlogz:38212.946>10]

627it [00:43,  8.33it/s, bound:162 nc: 40 ncall:1.4e+04 eff:4.4% logz=551773.01+/-0.57 dlogz:38163.193>10]

628it [00:43,  8.34it/s, bound:163 nc: 40 ncall:1.4e+04 eff:4.4% logz=551795.31+/-0.55 dlogz:38125.434>10]

629it [00:43,  8.37it/s, bound:163 nc: 40 ncall:1.4e+04 eff:4.4% logz=551873.80+/-0.57 dlogz:38103.130>10]

631it [00:44,  9.01it/s, bound:164 nc: 35 ncall:1.5e+04 eff:4.3% logz=551970.47+/-0.57 dlogz:37964.357>10]

632it [00:44,  9.07it/s, bound:165 nc: 36 ncall:1.5e+04 eff:4.3% logz=552084.74+/-0.57 dlogz:37927.925>10]

633it [00:44,  8.94it/s, bound:165 nc: 39 ncall:1.5e+04 eff:4.3% logz=552220.62+/-0.57 dlogz:37813.641>10]

634it [00:44,  7.30it/s, bound:166 nc: 68 ncall:1.5e+04 eff:4.3% logz=552372.31+/-0.57 dlogz:37677.758>10]

635it [00:44,  7.75it/s, bound:167 nc: 36 ncall:1.5e+04 eff:4.3% logz=552519.84+/-0.57 dlogz:37526.056>10]

636it [00:44,  7.83it/s, bound:167 nc: 40 ncall:1.5e+04 eff:4.3% logz=552647.68+/-0.57 dlogz:37378.510>10]

637it [00:44,  8.07it/s, bound:168 nc: 37 ncall:1.5e+04 eff:4.3% logz=552771.49+/-0.57 dlogz:37250.655>10]

638it [00:45,  8.23it/s, bound:168 nc: 39 ncall:1.5e+04 eff:4.3% logz=552775.51+/-0.56 dlogz:37126.832>10]

639it [00:45,  8.21it/s, bound:169 nc: 40 ncall:1.5e+04 eff:4.3% logz=552802.50+/-0.57 dlogz:37122.801>10]

640it [00:45,  8.47it/s, bound:169 nc: 34 ncall:1.5e+04 eff:4.3% logz=552938.39+/-0.57 dlogz:37095.800>10]

641it [00:45,  8.68it/s, bound:170 nc: 36 ncall:1.5e+04 eff:4.3% logz=553168.66+/-0.57 dlogz:36959.897>10]

643it [00:45,  9.27it/s, bound:171 nc: 34 ncall:1.5e+04 eff:4.3% logz=553330.32+/-0.57 dlogz:36659.474>10]

644it [00:45,  9.00it/s, bound:171 nc: 40 ncall:1.5e+04 eff:4.3% logz=553574.97+/-0.57 dlogz:36567.929>10]

645it [00:45,  8.95it/s, bound:172 nc: 37 ncall:1.5e+04 eff:4.3% logz=553753.53+/-0.57 dlogz:36323.272>10]

646it [00:45,  9.11it/s, bound:172 nc: 35 ncall:1.5e+04 eff:4.3% logz=553848.31+/-0.57 dlogz:36144.690>10]

648it [00:46,  9.79it/s, bound:173 nc: 30 ncall:1.5e+04 eff:4.3% logz=554081.84+/-0.57 dlogz:35981.188>10]

650it [00:46,  9.79it/s, bound:174 nc: 40 ncall:1.5e+04 eff:4.3% logz=554161.82+/-0.57 dlogz:35768.755>10]

651it [00:46,  9.41it/s, bound:175 nc: 40 ncall:1.5e+04 eff:4.3% logz=554473.43+/-0.57 dlogz:35736.342>10]

652it [00:46,  9.14it/s, bound:175 nc: 40 ncall:1.5e+04 eff:4.3% logz=555067.94+/-0.57 dlogz:35424.719>10]

653it [00:46,  8.89it/s, bound:176 nc: 40 ncall:1.5e+04 eff:4.3% logz=555304.63+/-0.57 dlogz:34830.199>10]

654it [00:46,  8.72it/s, bound:176 nc: 40 ncall:1.5e+04 eff:4.3% logz=555314.28+/-0.57 dlogz:34593.498>10]

655it [00:46,  8.61it/s, bound:177 nc: 39 ncall:1.5e+04 eff:4.2% logz=555319.52+/-0.56 dlogz:34583.831>10]

656it [00:47,  8.53it/s, bound:177 nc: 39 ncall:1.5e+04 eff:4.2% logz=555343.92+/-0.57 dlogz:34578.580>10]

657it [00:47,  8.51it/s, bound:178 nc: 40 ncall:1.5e+04 eff:4.2% logz=555391.93+/-0.57 dlogz:34554.170>10]

658it [00:47,  8.66it/s, bound:178 nc: 37 ncall:1.6e+04 eff:4.2% logz=555422.44+/-0.57 dlogz:34506.148>10]

659it [00:47,  8.56it/s, bound:179 nc: 40 ncall:1.6e+04 eff:4.2% logz=555523.98+/-0.57 dlogz:34475.620>10]

660it [00:47,  8.70it/s, bound:179 nc: 37 ncall:1.6e+04 eff:4.2% logz=555722.12+/-0.57 dlogz:34374.068>10]

661it [00:47,  8.86it/s, bound:180 nc: 34 ncall:1.6e+04 eff:4.2% logz=555768.80+/-0.57 dlogz:34175.920>10]

662it [00:47,  8.93it/s, bound:180 nc: 37 ncall:1.6e+04 eff:4.2% logz=555904.61+/-0.57 dlogz:34129.224>10]

663it [00:47,  9.20it/s, bound:181 nc: 33 ncall:1.6e+04 eff:4.2% logz=555950.96+/-0.58 dlogz:33993.403>10]

664it [00:47,  9.09it/s, bound:181 nc: 38 ncall:1.6e+04 eff:4.2% logz=556209.67+/-0.58 dlogz:33947.041>10]

665it [00:48,  8.78it/s, bound:182 nc: 40 ncall:1.6e+04 eff:4.2% logz=556659.70+/-0.58 dlogz:33688.314>10]

666it [00:48,  7.44it/s, bound:182 nc: 60 ncall:1.6e+04 eff:4.2% logz=556665.63+/-0.58 dlogz:33238.274>10]

668it [00:48,  8.24it/s, bound:183 nc: 40 ncall:1.6e+04 eff:4.2% logz=557087.65+/-0.58 dlogz:32970.117>10]

669it [00:48,  8.47it/s, bound:184 nc: 36 ncall:1.6e+04 eff:4.2% logz=557160.42+/-0.58 dlogz:32810.289>10]

670it [00:48,  8.67it/s, bound:184 nc: 37 ncall:1.6e+04 eff:4.2% logz=557338.59+/-0.58 dlogz:32737.509>10]

671it [00:48,  8.52it/s, bound:185 nc: 40 ncall:1.6e+04 eff:4.2% logz=557482.38+/-0.58 dlogz:32559.321>10]

672it [00:48,  8.48it/s, bound:185 nc: 40 ncall:1.6e+04 eff:4.2% logz=558008.35+/-0.58 dlogz:32415.525>10]

673it [00:49,  8.37it/s, bound:186 nc: 40 ncall:1.6e+04 eff:4.2% logz=558092.97+/-0.58 dlogz:31889.542>10]

674it [00:49,  8.28it/s, bound:186 nc: 40 ncall:1.6e+04 eff:4.2% logz=558121.30+/-0.58 dlogz:31804.904>10]

676it [00:49,  8.68it/s, bound:187 nc: 40 ncall:1.6e+04 eff:4.2% logz=558484.01+/-0.58 dlogz:31473.680>10]

677it [00:49,  8.78it/s, bound:188 nc: 36 ncall:1.6e+04 eff:4.2% logz=558631.05+/-0.58 dlogz:31413.833>10]

678it [00:49,  8.30it/s, bound:188 nc: 46 ncall:1.6e+04 eff:4.2% logz=558758.72+/-0.58 dlogz:31266.777>10]

679it [00:49,  8.55it/s, bound:189 nc: 35 ncall:1.6e+04 eff:4.2% logz=558860.26+/-0.58 dlogz:31139.097>10]

680it [00:49,  8.52it/s, bound:189 nc: 40 ncall:1.6e+04 eff:4.1% logz=559000.71+/-0.58 dlogz:31037.538>10]

681it [00:50,  7.07it/s, bound:190 nc: 64 ncall:1.6e+04 eff:4.1% logz=559086.90+/-0.56 dlogz:30897.079>10]

682it [00:50,  7.42it/s, bound:191 nc: 39 ncall:1.6e+04 eff:4.1% logz=559247.47+/-0.58 dlogz:30810.882>10]

683it [00:50,  5.42it/s, bound:192 nc: 99 ncall:1.7e+04 eff:4.1% logz=559340.17+/-0.58 dlogz:30650.294>10]

684it [00:50,  6.04it/s, bound:192 nc: 40 ncall:1.7e+04 eff:4.1% logz=559385.24+/-0.58 dlogz:30557.582>10]

685it [00:50,  6.56it/s, bound:193 nc: 40 ncall:1.7e+04 eff:4.1% logz=559411.60+/-0.58 dlogz:30512.496>10]

686it [00:50,  7.02it/s, bound:193 nc: 39 ncall:1.7e+04 eff:4.1% logz=559829.86+/-0.58 dlogz:30486.131>10]

688it [00:51,  6.46it/s, bound:194 nc: 80 ncall:1.7e+04 eff:4.1% logz=560311.84+/-0.58 dlogz:29737.530>10]

689it [00:51,  5.81it/s, bound:195 nc: 73 ncall:1.7e+04 eff:4.1% logz=560472.09+/-0.58 dlogz:29585.848>10]

690it [00:51,  6.41it/s, bound:196 nc: 37 ncall:1.7e+04 eff:4.1% logz=560483.31+/-0.58 dlogz:29425.587>10]

691it [00:51,  6.86it/s, bound:196 nc: 40 ncall:1.7e+04 eff:4.1% logz=560508.00+/-0.58 dlogz:29414.356>10]

693it [00:51,  8.33it/s, bound:197 nc: 40 ncall:1.7e+04 eff:4.1% logz=561102.67+/-0.58 dlogz:28951.592>10]

694it [00:51,  8.63it/s, bound:198 nc: 35 ncall:1.7e+04 eff:4.1% logz=561140.02+/-0.58 dlogz:28794.959>10]

695it [00:52,  8.57it/s, bound:198 nc: 40 ncall:1.7e+04 eff:4.1% logz=561203.24+/-0.58 dlogz:28757.594>10]

696it [00:52,  8.69it/s, bound:199 nc: 37 ncall:1.7e+04 eff:4.1% logz=561499.26+/-0.58 dlogz:28694.364>10]

697it [00:52,  7.11it/s, bound:199 nc: 69 ncall:1.7e+04 eff:4.0% logz=561616.40+/-0.58 dlogz:28398.332>10]

698it [00:52,  7.43it/s, bound:200 nc: 40 ncall:1.7e+04 eff:4.0% logz=561777.55+/-0.58 dlogz:28281.178>10]

699it [00:52,  6.28it/s, bound:200 nc: 74 ncall:1.7e+04 eff:4.0% logz=561828.53+/-0.58 dlogz:28120.019>10]

701it [00:52,  7.45it/s, bound:201 nc: 40 ncall:1.7e+04 eff:4.0% logz=562082.07+/-0.59 dlogz:27999.424>10]

702it [00:52,  7.64it/s, bound:202 nc: 40 ncall:1.7e+04 eff:4.0% logz=562155.75+/-0.57 dlogz:27815.459>10]

703it [00:53,  7.87it/s, bound:202 nc: 40 ncall:1.7e+04 eff:4.0% logz=562241.95+/-0.59 dlogz:27741.767>10]

704it [00:53,  7.90it/s, bound:203 nc: 40 ncall:1.8e+04 eff:4.0% logz=562304.61+/-0.59 dlogz:27655.549>10]

706it [00:53,  7.20it/s, bound:204 nc: 80 ncall:1.8e+04 eff:4.0% logz=562488.57+/-0.59 dlogz:27456.656>10]

708it [00:53,  7.97it/s, bound:205 nc: 40 ncall:1.8e+04 eff:4.0% logz=563295.43+/-0.59 dlogz:26834.507>10]

709it [00:53,  7.06it/s, bound:206 nc: 65 ncall:1.8e+04 eff:4.0% logz=563313.33+/-0.59 dlogz:26602.012>10]

710it [00:54,  7.51it/s, bound:207 nc: 34 ncall:1.8e+04 eff:4.0% logz=563360.95+/-0.59 dlogz:26584.095>10]

711it [00:54,  7.72it/s, bound:207 nc: 40 ncall:1.8e+04 eff:4.0% logz=563780.03+/-0.59 dlogz:26536.469>10]

713it [00:54,  8.61it/s, bound:208 nc: 32 ncall:1.8e+04 eff:4.0% logz=564746.21+/-0.59 dlogz:25725.370>10]

714it [00:54,  8.45it/s, bound:209 nc: 40 ncall:1.8e+04 eff:4.0% logz=564764.69+/-0.59 dlogz:25151.170>10]

715it [00:54,  8.72it/s, bound:209 nc: 35 ncall:1.8e+04 eff:4.0% logz=564819.74+/-0.59 dlogz:25132.679>10]

716it [00:54,  8.55it/s, bound:210 nc: 40 ncall:1.8e+04 eff:4.0% logz=564830.26+/-0.59 dlogz:25077.615>10]

717it [00:54,  8.45it/s, bound:210 nc: 40 ncall:1.8e+04 eff:4.0% logz=564864.56+/-0.59 dlogz:25067.080>10]

718it [00:55,  6.92it/s, bound:211 nc: 70 ncall:1.8e+04 eff:4.0% logz=565202.96+/-0.59 dlogz:25032.769>10]

719it [00:55,  7.34it/s, bound:212 nc: 36 ncall:1.8e+04 eff:4.0% logz=565207.61+/-0.59 dlogz:24694.358>10]

721it [00:55,  8.29it/s, bound:213 nc: 38 ncall:1.8e+04 eff:4.0% logz=565269.08+/-0.59 dlogz:24671.126>10]

723it [00:55,  9.14it/s, bound:214 nc: 40 ncall:1.8e+04 eff:4.0% logz=565443.04+/-0.59 dlogz:24477.420>10]

724it [00:55,  6.69it/s, bound:215 nc: 96 ncall:1.8e+04 eff:3.9% logz=565535.30+/-0.59 dlogz:24454.212>10]

726it [00:56,  7.73it/s, bound:216 nc: 39 ncall:1.8e+04 eff:3.9% logz=565903.95+/-0.58 dlogz:24209.365>10]

727it [00:56,  7.88it/s, bound:216 nc: 37 ncall:1.8e+04 eff:3.9% logz=565908.86+/-0.59 dlogz:23993.270>10]

728it [00:56,  7.95it/s, bound:217 nc: 40 ncall:1.9e+04 eff:3.9% logz=565919.00+/-0.59 dlogz:23988.351>10]

730it [00:56,  7.10it/s, bound:218 nc: 77 ncall:1.9e+04 eff:3.9% logz=566034.74+/-0.59 dlogz:23937.333>10]

731it [00:56,  7.32it/s, bound:219 nc: 40 ncall:1.9e+04 eff:3.9% logz=566100.04+/-0.59 dlogz:23862.430>10]

733it [00:56,  8.17it/s, bound:220 nc: 40 ncall:1.9e+04 eff:3.9% logz=566321.24+/-0.59 dlogz:23702.832>10]

734it [00:57,  6.83it/s, bound:220 nc: 78 ncall:1.9e+04 eff:3.9% logz=566423.00+/-0.59 dlogz:23575.893>10]

736it [00:57,  7.86it/s, bound:221 nc: 36 ncall:1.9e+04 eff:3.9% logz=566995.20+/-0.59 dlogz:23472.620>10]

737it [00:57,  7.98it/s, bound:222 nc: 40 ncall:1.9e+04 eff:3.9% logz=567053.18+/-0.59 dlogz:22901.894>10]

739it [00:57,  8.60it/s, bound:223 nc: 40 ncall:1.9e+04 eff:3.9% logz=567120.86+/-0.60 dlogz:22824.775>10]

740it [00:57,  7.44it/s, bound:223 nc: 65 ncall:1.9e+04 eff:3.9% logz=567398.78+/-0.60 dlogz:22776.197>10]

741it [00:58,  7.58it/s, bound:224 nc: 40 ncall:1.9e+04 eff:3.9% logz=567818.60+/-0.60 dlogz:22498.269>10]

743it [00:58,  8.49it/s, bound:225 nc: 40 ncall:1.9e+04 eff:3.9% logz=568099.70+/-0.60 dlogz:22048.611>10]

744it [00:58,  8.47it/s, bound:225 nc: 40 ncall:1.9e+04 eff:3.9% logz=568233.76+/-0.60 dlogz:21797.302>10]

745it [00:58,  8.42it/s, bound:226 nc: 40 ncall:1.9e+04 eff:3.9% logz=568294.57+/-0.60 dlogz:21663.230>10]

746it [00:58,  8.37it/s, bound:226 nc: 40 ncall:1.9e+04 eff:3.9% logz=568349.46+/-0.60 dlogz:21602.415>10]

747it [00:58,  8.30it/s, bound:227 nc: 40 ncall:1.9e+04 eff:3.9% logz=568452.59+/-0.60 dlogz:21547.511>10]

748it [00:58,  8.31it/s, bound:227 nc: 40 ncall:1.9e+04 eff:3.9% logz=568536.24+/-0.60 dlogz:21444.369>10]

749it [00:58,  8.38it/s, bound:228 nc: 38 ncall:1.9e+04 eff:3.9% logz=568645.45+/-0.60 dlogz:21360.704>10]

750it [00:59,  8.31it/s, bound:228 nc: 40 ncall:1.9e+04 eff:3.9% logz=568721.83+/-0.60 dlogz:21251.478>10]

751it [00:59,  8.31it/s, bound:229 nc: 40 ncall:1.9e+04 eff:3.9% logz=568901.04+/-0.58 dlogz:21175.095>10]

752it [00:59,  8.33it/s, bound:229 nc: 40 ncall:2.0e+04 eff:3.9% logz=569014.34+/-0.60 dlogz:20995.866>10]

753it [00:59,  8.45it/s, bound:230 nc: 38 ncall:2.0e+04 eff:3.9% logz=569016.75+/-0.59 dlogz:20882.556>10]

754it [00:59,  8.43it/s, bound:230 nc: 40 ncall:2.0e+04 eff:3.9% logz=569181.75+/-0.60 dlogz:20880.135>10]

755it [00:59,  8.35it/s, bound:231 nc: 40 ncall:2.0e+04 eff:3.8% logz=569516.09+/-0.60 dlogz:20715.117>10]

756it [00:59,  8.42it/s, bound:231 nc: 40 ncall:2.0e+04 eff:3.8% logz=569580.56+/-0.60 dlogz:20380.768>10]

757it [00:59,  8.42it/s, bound:232 nc: 40 ncall:2.0e+04 eff:3.8% logz=569584.44+/-0.60 dlogz:20316.281>10]

758it [00:59,  8.46it/s, bound:232 nc: 40 ncall:2.0e+04 eff:3.8% logz=569612.02+/-0.60 dlogz:20312.389>10]

760it [01:00,  9.50it/s, bound:233 nc: 40 ncall:2.0e+04 eff:3.8% logz=569837.07+/-0.60 dlogz:20154.334>10]

761it [01:00,  7.25it/s, bound:234 nc: 80 ncall:2.0e+04 eff:3.8% logz=569883.45+/-0.60 dlogz:20059.726>10]

762it [01:00,  7.47it/s, bound:235 nc: 40 ncall:2.0e+04 eff:3.8% logz=569885.19+/-0.58 dlogz:20013.338>10]

763it [01:00,  7.71it/s, bound:235 nc: 40 ncall:2.0e+04 eff:3.8% logz=569902.02+/-0.60 dlogz:20011.577>10]

764it [01:00,  6.27it/s, bound:236 nc: 78 ncall:2.0e+04 eff:3.8% logz=569985.08+/-0.60 dlogz:20265.177>10]

765it [01:01,  6.71it/s, bound:237 nc: 40 ncall:2.0e+04 eff:3.8% logz=570066.85+/-0.60 dlogz:20182.101>10]

766it [01:01,  7.12it/s, bound:237 nc: 40 ncall:2.0e+04 eff:3.8% logz=570457.37+/-0.60 dlogz:20100.325>10]

767it [01:01,  7.37it/s, bound:238 nc: 40 ncall:2.0e+04 eff:3.8% logz=570534.48+/-0.60 dlogz:19709.791>10]

768it [01:01,  7.60it/s, bound:238 nc: 40 ncall:2.0e+04 eff:3.8% logz=570618.29+/-0.60 dlogz:19632.671>10]

769it [01:01,  7.78it/s, bound:239 nc: 40 ncall:2.0e+04 eff:3.8% logz=570637.08+/-0.60 dlogz:19548.846>10]

770it [01:01,  8.10it/s, bound:239 nc: 37 ncall:2.0e+04 eff:3.8% logz=570651.13+/-0.60 dlogz:19530.042>10]

771it [01:01,  8.11it/s, bound:240 nc: 40 ncall:2.0e+04 eff:3.8% logz=570949.78+/-0.60 dlogz:19515.976>10]

772it [01:01,  8.21it/s, bound:240 nc: 40 ncall:2.0e+04 eff:3.8% logz=571028.25+/-0.60 dlogz:19217.316>10]

773it [01:02,  6.37it/s, bound:241 nc: 80 ncall:2.0e+04 eff:3.8% logz=571071.36+/-0.60 dlogz:19138.834>10]

774it [01:02,  6.93it/s, bound:242 nc: 38 ncall:2.0e+04 eff:3.8% logz=571182.42+/-0.59 dlogz:19095.712>10]

775it [01:02,  7.22it/s, bound:242 nc: 40 ncall:2.1e+04 eff:3.8% logz=571402.57+/-0.60 dlogz:18984.641>10]

776it [01:02,  7.52it/s, bound:243 nc: 40 ncall:2.1e+04 eff:3.8% logz=571651.87+/-0.60 dlogz:18764.480>10]

777it [01:02,  7.82it/s, bound:243 nc: 40 ncall:2.1e+04 eff:3.8% logz=571718.12+/-0.60 dlogz:18515.164>10]

779it [01:02,  8.47it/s, bound:244 nc: 40 ncall:2.1e+04 eff:3.8% logz=571778.30+/-0.61 dlogz:18404.202>10]

780it [01:03,  6.69it/s, bound:245 nc: 80 ncall:2.1e+04 eff:3.8% logz=571935.59+/-0.61 dlogz:18388.692>10]

781it [01:03,  7.14it/s, bound:246 nc: 38 ncall:2.1e+04 eff:3.8% logz=571952.70+/-0.61 dlogz:18231.395>10]

782it [01:03,  7.40it/s, bound:246 nc: 40 ncall:2.1e+04 eff:3.8% logz=572054.50+/-0.61 dlogz:18214.276>10]

783it [01:03,  7.69it/s, bound:247 nc: 39 ncall:2.1e+04 eff:3.8% logz=572098.49+/-0.61 dlogz:18112.463>10]

785it [01:03,  8.30it/s, bound:248 nc: 40 ncall:2.1e+04 eff:3.7% logz=572273.71+/-0.61 dlogz:18049.975>10]

786it [01:03,  8.36it/s, bound:248 nc: 40 ncall:2.1e+04 eff:3.7% logz=572300.21+/-0.61 dlogz:17893.209>10]

787it [01:03,  8.38it/s, bound:249 nc: 39 ncall:2.1e+04 eff:3.7% logz=572373.08+/-0.61 dlogz:17866.699>10]

789it [01:03,  9.55it/s, bound:250 nc: 40 ncall:2.1e+04 eff:3.7% logz=572767.93+/-0.61 dlogz:17660.192>10]

790it [01:04,  9.53it/s, bound:250 nc: 36 ncall:2.1e+04 eff:3.7% logz=573022.13+/-0.61 dlogz:17398.944>10]

791it [01:04,  9.20it/s, bound:251 nc: 40 ncall:2.1e+04 eff:3.7% logz=573280.66+/-0.61 dlogz:17144.730>10]

792it [01:04,  9.21it/s, bound:251 nc: 36 ncall:2.1e+04 eff:3.7% logz=573410.75+/-0.61 dlogz:16886.192>10]

793it [01:04,  8.95it/s, bound:252 nc: 40 ncall:2.1e+04 eff:3.7% logz=573462.86+/-0.61 dlogz:16756.087>10]

794it [01:04,  8.72it/s, bound:252 nc: 40 ncall:2.1e+04 eff:3.7% logz=573550.26+/-0.61 dlogz:16703.962>10]

795it [01:04,  8.59it/s, bound:253 nc: 40 ncall:2.1e+04 eff:3.7% logz=573842.23+/-0.61 dlogz:16616.553>10]

796it [01:04,  8.55it/s, bound:253 nc: 40 ncall:2.1e+04 eff:3.7% logz=573900.34+/-0.61 dlogz:18533.311>10]

797it [01:04,  8.49it/s, bound:254 nc: 39 ncall:2.1e+04 eff:3.7% logz=573992.10+/-0.61 dlogz:18475.189>10]

798it [01:05,  6.49it/s, bound:254 nc: 80 ncall:2.1e+04 eff:3.7% logz=574205.95+/-0.61 dlogz:18383.415>10]

799it [01:05,  6.89it/s, bound:255 nc: 40 ncall:2.2e+04 eff:3.7% logz=574261.42+/-0.60 dlogz:18169.555>10]

800it [01:05,  7.21it/s, bound:255 nc: 40 ncall:2.2e+04 eff:3.7% logz=574398.16+/-0.61 dlogz:18114.067>10]

801it [01:05,  7.43it/s, bound:256 nc: 39 ncall:2.2e+04 eff:3.7% logz=574422.13+/-0.61 dlogz:17977.319>10]

802it [01:05,  7.70it/s, bound:256 nc: 38 ncall:2.2e+04 eff:3.7% logz=574438.42+/-0.61 dlogz:17953.333>10]

803it [01:05,  8.11it/s, bound:257 nc: 36 ncall:2.2e+04 eff:3.7% logz=574560.82+/-0.61 dlogz:17937.029>10]

804it [01:05,  8.11it/s, bound:257 nc: 40 ncall:2.2e+04 eff:3.7% logz=574565.16+/-0.61 dlogz:17999.258>10]

805it [01:06,  8.20it/s, bound:258 nc: 40 ncall:2.2e+04 eff:3.7% logz=574606.24+/-0.61 dlogz:17994.914>10]

806it [01:06,  8.21it/s, bound:258 nc: 40 ncall:2.2e+04 eff:3.7% logz=574608.87+/-0.60 dlogz:17953.820>10]

808it [01:06,  9.05it/s, bound:259 nc: 34 ncall:2.2e+04 eff:3.7% logz=574788.67+/-0.61 dlogz:17824.259>10]

809it [01:06,  8.88it/s, bound:260 nc: 39 ncall:2.2e+04 eff:3.7% logz=574947.59+/-0.61 dlogz:17771.350>10]

810it [01:06,  8.85it/s, bound:260 nc: 38 ncall:2.2e+04 eff:3.7% logz=575232.61+/-0.61 dlogz:17612.417>10]

811it [01:06,  8.64it/s, bound:261 nc: 40 ncall:2.2e+04 eff:3.7% logz=575340.41+/-0.61 dlogz:17327.388>10]

812it [01:06,  8.52it/s, bound:261 nc: 40 ncall:2.2e+04 eff:3.7% logz=575494.13+/-0.61 dlogz:17219.576>10]

813it [01:06,  8.42it/s, bound:262 nc: 40 ncall:2.2e+04 eff:3.7% logz=575497.19+/-0.61 dlogz:17065.838>10]

814it [01:07,  8.51it/s, bound:262 nc: 38 ncall:2.2e+04 eff:3.7% logz=575687.76+/-0.61 dlogz:17062.765>10]

815it [01:07,  8.44it/s, bound:263 nc: 40 ncall:2.2e+04 eff:3.7% logz=575735.10+/-0.61 dlogz:16872.183>10]

816it [01:07,  8.45it/s, bound:263 nc: 40 ncall:2.2e+04 eff:3.7% logz=575846.70+/-0.61 dlogz:16824.835>10]

817it [01:07,  8.40it/s, bound:264 nc: 40 ncall:2.2e+04 eff:3.7% logz=575993.50+/-0.62 dlogz:16713.225>10]

819it [01:07,  8.72it/s, bound:265 nc: 40 ncall:2.2e+04 eff:3.7% logz=576028.51+/-0.62 dlogz:16541.619>10]

820it [01:07,  8.55it/s, bound:265 nc: 40 ncall:2.2e+04 eff:3.7% logz=576233.29+/-0.62 dlogz:16531.369>10]

821it [01:07,  8.71it/s, bound:266 nc: 36 ncall:2.2e+04 eff:3.7% logz=576298.47+/-0.62 dlogz:16326.576>10]

822it [01:07,  8.77it/s, bound:266 nc: 37 ncall:2.2e+04 eff:3.7% logz=576326.33+/-0.62 dlogz:16261.390>10]

823it [01:08,  8.94it/s, bound:267 nc: 34 ncall:2.2e+04 eff:3.7% logz=576415.05+/-0.62 dlogz:16233.513>10]

824it [01:08,  8.82it/s, bound:267 nc: 38 ncall:2.2e+04 eff:3.7% logz=576498.84+/-0.62 dlogz:16144.781>10]

825it [01:08,  8.84it/s, bound:268 nc: 35 ncall:2.2e+04 eff:3.7% logz=576602.36+/-0.62 dlogz:16060.977>10]

826it [01:08,  6.99it/s, bound:268 nc: 70 ncall:2.3e+04 eff:3.7% logz=576612.63+/-0.60 dlogz:15957.454>10]

827it [01:08,  7.56it/s, bound:269 nc: 35 ncall:2.3e+04 eff:3.7% logz=576692.20+/-0.62 dlogz:15947.166>10]

829it [01:08,  7.51it/s, bound:270 nc: 57 ncall:2.3e+04 eff:3.7% logz=577196.78+/-0.62 dlogz:15570.581>10]

830it [01:08,  7.93it/s, bound:271 nc: 35 ncall:2.3e+04 eff:3.7% logz=577244.62+/-0.62 dlogz:15362.977>10]

831it [01:09,  8.37it/s, bound:271 nc: 34 ncall:2.3e+04 eff:3.7% logz=577458.10+/-0.62 dlogz:15315.127>10]

832it [01:09,  8.74it/s, bound:272 nc: 33 ncall:2.3e+04 eff:3.7% logz=577563.25+/-0.62 dlogz:15101.638>10]

833it [01:09,  7.34it/s, bound:272 nc: 64 ncall:2.3e+04 eff:3.6% logz=577567.17+/-0.62 dlogz:14996.472>10]

834it [01:09,  6.52it/s, bound:273 nc: 64 ncall:2.3e+04 eff:3.6% logz=577710.54+/-0.62 dlogz:14992.541>10]

835it [01:09,  7.15it/s, bound:274 nc: 35 ncall:2.3e+04 eff:3.6% logz=577744.13+/-0.62 dlogz:14849.152>10]

836it [01:09,  7.73it/s, bound:274 nc: 34 ncall:2.3e+04 eff:3.6% logz=577886.38+/-0.62 dlogz:14815.554>10]

837it [01:09,  6.62it/s, bound:275 nc: 66 ncall:2.3e+04 eff:3.6% logz=578018.74+/-0.62 dlogz:14673.290>10]

839it [01:10,  8.58it/s, bound:276 nc: 29 ncall:2.3e+04 eff:3.6% logz=578089.52+/-0.62 dlogz:14516.182>10]

841it [01:10,  9.84it/s, bound:277 nc: 21 ncall:2.3e+04 eff:3.6% logz=578181.27+/-0.62 dlogz:14435.365>10]

843it [01:10,  9.83it/s, bound:278 nc: 33 ncall:2.3e+04 eff:3.6% logz=578331.70+/-0.62 dlogz:14335.180>10]

845it [01:10, 10.53it/s, bound:279 nc: 33 ncall:2.3e+04 eff:3.6% logz=578376.59+/-0.62 dlogz:14197.863>10]

847it [01:10,  9.22it/s, bound:280 nc: 61 ncall:2.3e+04 eff:3.6% logz=578713.18+/-0.62 dlogz:13880.161>10]

849it [01:11, 10.64it/s, bound:281 nc: 20 ncall:2.3e+04 eff:3.6% logz=578814.05+/-0.62 dlogz:13829.638>10]

851it [01:11,  7.66it/s, bound:283 nc:105 ncall:2.4e+04 eff:3.6% logz=579103.65+/-0.62 dlogz:13510.495>10]

852it [01:11,  6.87it/s, bound:283 nc: 69 ncall:2.4e+04 eff:3.6% logz=579109.71+/-0.61 dlogz:13465.972>10]

853it [01:11,  6.45it/s, bound:284 nc: 62 ncall:2.4e+04 eff:3.6% logz=579540.48+/-0.62 dlogz:13459.905>10]

855it [01:12,  7.99it/s, bound:285 nc: 26 ncall:2.4e+04 eff:3.6% logz=579654.63+/-0.62 dlogz:12920.595>10]

856it [01:12,  8.28it/s, bound:285 nc: 35 ncall:2.4e+04 eff:3.6% logz=579820.50+/-0.62 dlogz:12914.948>10]

858it [01:12,  6.84it/s, bound:287 nc: 98 ncall:2.4e+04 eff:3.6% logz=580129.53+/-0.63 dlogz:12607.022>10]

859it [01:12,  7.31it/s, bound:287 nc: 33 ncall:2.4e+04 eff:3.6% logz=580158.20+/-0.63 dlogz:12440.005>10]

860it [01:12,  6.46it/s, bound:288 nc: 70 ncall:2.4e+04 eff:3.6% logz=580507.37+/-0.63 dlogz:12411.330>10]

861it [01:13,  6.40it/s, bound:289 nc: 54 ncall:2.4e+04 eff:3.6% logz=580509.98+/-0.62 dlogz:12062.148>10]

863it [01:13,  6.59it/s, bound:290 nc: 79 ncall:2.4e+04 eff:3.6% logz=580589.31+/-0.63 dlogz:12031.224>10]

864it [01:13,  7.06it/s, bound:291 nc: 35 ncall:2.4e+04 eff:3.6% logz=580756.55+/-0.63 dlogz:11980.163>10]

866it [01:13,  7.26it/s, bound:292 nc: 56 ncall:2.4e+04 eff:3.6% logz=580856.66+/-0.63 dlogz:11751.523>10]

868it [01:13,  8.16it/s, bound:293 nc: 35 ncall:2.4e+04 eff:3.6% logz=580947.73+/-0.63 dlogz:11683.670>10]

870it [01:14,  9.08it/s, bound:294 nc: 28 ncall:2.4e+04 eff:3.6% logz=580952.69+/-0.60 dlogz:11617.877>10]

872it [01:14, 10.05it/s, bound:295 nc: 25 ncall:2.4e+04 eff:3.6% logz=581075.32+/-0.63 dlogz:11594.492>10]

874it [01:14,  9.11it/s, bound:296 nc: 61 ncall:2.5e+04 eff:3.6% logz=581308.32+/-0.63 dlogz:11363.832>10]

876it [01:14,  8.60it/s, bound:297 nc: 55 ncall:2.5e+04 eff:3.6% logz=581436.68+/-0.62 dlogz:11221.333>10]

878it [01:14,  9.52it/s, bound:298 nc: 26 ncall:2.5e+04 eff:3.6% logz=581497.81+/-0.63 dlogz:11108.917>10]

880it [01:15,  7.41it/s, bound:300 nc: 28 ncall:2.5e+04 eff:3.6% logz=581501.41+/-0.61 dlogz:11069.245>10]

882it [01:15,  7.48it/s, bound:301 nc: 70 ncall:2.5e+04 eff:3.5% logz=581637.96+/-0.63 dlogz:11011.607>10]

883it [01:15,  6.79it/s, bound:302 nc: 68 ncall:2.5e+04 eff:3.5% logz=581705.71+/-0.63 dlogz:10931.279>10]

884it [01:16,  4.93it/s, bound:305 nc:133 ncall:2.5e+04 eff:3.5% logz=581719.71+/-0.63 dlogz:10863.522>10]

886it [01:16,  6.08it/s, bound:306 nc: 35 ncall:2.5e+04 eff:3.5% logz=581858.21+/-0.63 dlogz:11171.928>10]

887it [01:16,  6.57it/s, bound:306 nc: 35 ncall:2.5e+04 eff:3.5% logz=581891.30+/-0.63 dlogz:11088.051>10]

889it [01:16,  7.79it/s, bound:307 nc: 33 ncall:2.5e+04 eff:3.5% logz=582085.90+/-0.63 dlogz:10899.565>10]

891it [01:16,  8.95it/s, bound:308 nc: 31 ncall:2.5e+04 eff:3.5% logz=582114.20+/-0.63 dlogz:10858.038>10]

892it [01:17,  7.64it/s, bound:309 nc: 65 ncall:2.5e+04 eff:3.5% logz=582391.39+/-0.63 dlogz:10832.001>10]

894it [01:17,  9.13it/s, bound:310 nc: 24 ncall:2.5e+04 eff:3.5% logz=582627.90+/-0.63 dlogz:10524.494>10]

896it [01:17,  5.80it/s, bound:313 nc: 64 ncall:2.6e+04 eff:3.5% logz=582724.38+/-0.63 dlogz:10309.381>10]

897it [01:17,  6.26it/s, bound:314 nc: 35 ncall:2.6e+04 eff:3.5% logz=582742.40+/-0.62 dlogz:10221.763>10]

898it [01:18,  5.89it/s, bound:314 nc: 66 ncall:2.6e+04 eff:3.5% logz=582744.08+/-0.62 dlogz:10203.732>10]

899it [01:18,  4.45it/s, bound:317 nc:127 ncall:2.6e+04 eff:3.5% logz=582807.60+/-0.64 dlogz:10202.040>10]

901it [01:18,  5.32it/s, bound:317 nc: 64 ncall:2.6e+04 eff:3.5% logz=582914.27+/-0.64 dlogz:10108.555>10]

902it [01:18,  5.27it/s, bound:318 nc: 64 ncall:2.6e+04 eff:3.5% logz=582946.59+/-0.64 dlogz:10031.808>10]

904it [01:19,  6.91it/s, bound:319 nc: 34 ncall:2.6e+04 eff:3.5% logz=583003.67+/-0.64 dlogz:9948.901>10]

906it [01:19,  7.78it/s, bound:320 nc: 35 ncall:2.6e+04 eff:3.5% logz=583040.53+/-0.64 dlogz:9923.638>10]

907it [01:19,  5.29it/s, bound:323 nc:138 ncall:2.6e+04 eff:3.5% logz=583051.45+/-0.64 dlogz:9905.481>10]

908it [01:19,  4.96it/s, bound:324 nc: 81 ncall:2.6e+04 eff:3.5% logz=583082.02+/-0.64 dlogz:9894.550>10]

910it [01:20,  6.35it/s, bound:325 nc: 33 ncall:2.6e+04 eff:3.5% logz=583236.97+/-0.64 dlogz:9847.586>10]

912it [01:20,  8.05it/s, bound:326 nc: 24 ncall:2.6e+04 eff:3.5% logz=583306.65+/-0.64 dlogz:9705.421>10]

913it [01:20,  5.75it/s, bound:328 nc:119 ncall:2.7e+04 eff:3.4% logz=583387.01+/-0.64 dlogz:9639.291>10]

914it [01:20,  6.36it/s, bound:328 nc: 33 ncall:2.7e+04 eff:3.4% logz=583438.66+/-0.64 dlogz:9558.921>10]

916it [01:21,  5.53it/s, bound:330 nc:115 ncall:2.7e+04 eff:3.4% logz=583875.97+/-0.64 dlogz:9226.019>10]

918it [01:21,  6.72it/s, bound:331 nc: 31 ncall:2.7e+04 eff:3.4% logz=583996.84+/-0.64 dlogz:9045.488>10]

920it [01:21,  7.59it/s, bound:332 nc: 35 ncall:2.7e+04 eff:3.4% logz=584085.19+/-0.64 dlogz:8908.455>10]

922it [01:21,  7.64it/s, bound:333 nc: 54 ncall:2.7e+04 eff:3.4% logz=584308.89+/-0.64 dlogz:8649.403>10]

923it [01:22,  6.17it/s, bound:335 nc: 98 ncall:2.7e+04 eff:3.4% logz=584358.23+/-0.64 dlogz:8636.929>10]

925it [01:22,  6.80it/s, bound:335 nc: 64 ncall:2.7e+04 eff:3.4% logz=584383.62+/-0.64 dlogz:8586.420>10]

926it [01:22,  7.24it/s, bound:336 nc: 35 ncall:2.7e+04 eff:3.4% logz=584446.13+/-0.64 dlogz:8562.160>10]

927it [01:22,  7.10it/s, bound:336 nc: 49 ncall:2.7e+04 eff:3.4% logz=584558.69+/-0.64 dlogz:8499.639>10]

929it [01:22,  6.18it/s, bound:338 nc:103 ncall:2.7e+04 eff:3.4% logz=584653.59+/-0.64 dlogz:8308.310>10]

931it [01:23,  6.82it/s, bound:339 nc: 55 ncall:2.7e+04 eff:3.4% logz=584675.29+/-0.64 dlogz:8274.474>10]

932it [01:23,  7.03it/s, bound:340 nc: 40 ncall:2.7e+04 eff:3.4% logz=584706.08+/-0.64 dlogz:8270.418>10]

934it [01:23,  6.99it/s, bound:341 nc: 62 ncall:2.8e+04 eff:3.4% logz=584754.61+/-0.64 dlogz:8198.365>10]

935it [01:23,  6.82it/s, bound:342 nc: 52 ncall:2.8e+04 eff:3.4% logz=584804.70+/-0.64 dlogz:8191.059>10]

936it [01:24,  5.71it/s, bound:344 nc: 87 ncall:2.8e+04 eff:3.4% logz=584818.59+/-0.64 dlogz:8140.952>10]

938it [01:24,  6.09it/s, bound:345 nc: 65 ncall:2.8e+04 eff:3.4% logz=584893.99+/-0.64 dlogz:8083.223>10]

940it [01:24,  5.64it/s, bound:347 nc: 99 ncall:2.8e+04 eff:3.4% logz=584985.74+/-0.65 dlogz:7989.879>10]

941it [01:24,  5.47it/s, bound:347 nc: 68 ncall:2.8e+04 eff:3.4% logz=584996.26+/-0.65 dlogz:7959.851>10]

943it [01:25,  6.63it/s, bound:348 nc: 32 ncall:2.8e+04 eff:3.4% logz=585002.52+/-0.64 dlogz:7947.123>10]

944it [01:25,  6.25it/s, bound:349 nc: 64 ncall:2.8e+04 eff:3.4% logz=585086.93+/-0.65 dlogz:7943.031>10]

946it [01:25,  7.50it/s, bound:350 nc: 34 ncall:2.8e+04 eff:3.4% logz=585127.47+/-0.65 dlogz:7856.779>10]

947it [01:25,  7.91it/s, bound:351 nc: 32 ncall:2.8e+04 eff:3.4% logz=585133.96+/-0.65 dlogz:7818.053>10]

948it [01:25,  8.23it/s, bound:351 nc: 35 ncall:2.8e+04 eff:3.4% logz=585262.42+/-0.65 dlogz:7811.544>10]

950it [01:25,  9.78it/s, bound:352 nc: 19 ncall:2.8e+04 eff:3.4% logz=585449.79+/-0.65 dlogz:7629.731>10]

952it [01:26, 11.06it/s, bound:353 nc: 28 ncall:2.8e+04 eff:3.4% logz=585484.57+/-0.65 dlogz:7469.931>10]

954it [01:26,  9.03it/s, bound:354 nc: 69 ncall:2.8e+04 eff:3.4% logz=585578.04+/-0.65 dlogz:7403.082>10]

956it [01:26,  9.88it/s, bound:355 nc: 32 ncall:2.8e+04 eff:3.4% logz=585721.37+/-0.65 dlogz:7239.744>10]

958it [01:26,  8.62it/s, bound:356 nc: 53 ncall:2.9e+04 eff:3.4% logz=585842.38+/-0.65 dlogz:7169.473>10]

960it [01:26,  9.04it/s, bound:357 nc: 35 ncall:2.9e+04 eff:3.4% logz=585911.81+/-0.65 dlogz:7066.105>10]

961it [01:27,  9.14it/s, bound:358 nc: 33 ncall:2.9e+04 eff:3.4% logz=585942.39+/-0.65 dlogz:7033.531>10]

963it [01:27, 10.62it/s, bound:359 nc: 23 ncall:2.9e+04 eff:3.4% logz=586040.42+/-0.65 dlogz:6996.846>10]

965it [01:27,  9.40it/s, bound:360 nc: 27 ncall:2.9e+04 eff:3.4% logz=586091.80+/-0.65 dlogz:6885.599>10]

967it [01:27,  9.79it/s, bound:361 nc: 33 ncall:2.9e+04 eff:3.4% logz=586214.60+/-0.65 dlogz:6826.278>10]

969it [01:27, 11.31it/s, bound:361 nc: 27 ncall:2.9e+04 eff:3.4% logz=586286.85+/-0.65 dlogz:6664.930>10]

971it [01:27, 10.92it/s, bound:362 nc: 34 ncall:2.9e+04 eff:3.4% logz=586594.47+/-0.65 dlogz:6460.792>10]

973it [01:28, 11.26it/s, bound:363 nc: 31 ncall:2.9e+04 eff:3.4% logz=586648.48+/-0.65 dlogz:6314.585>10]

975it [01:28, 11.49it/s, bound:364 nc: 20 ncall:2.9e+04 eff:3.4% logz=586690.75+/-0.65 dlogz:6293.523>10]

977it [01:28, 12.10it/s, bound:365 nc: 25 ncall:2.9e+04 eff:3.4% logz=586767.03+/-0.65 dlogz:6186.249>10]

979it [01:28, 12.67it/s, bound:366 nc: 24 ncall:2.9e+04 eff:3.4% logz=586785.59+/-0.65 dlogz:6170.170>10]

981it [01:28, 11.56it/s, bound:367 nc: 41 ncall:2.9e+04 eff:3.4% logz=586827.80+/-0.65 dlogz:6139.966>10]

983it [01:28, 12.08it/s, bound:368 nc: 28 ncall:2.9e+04 eff:3.4% logz=586893.33+/-0.65 dlogz:6057.519>10]

985it [01:29, 11.01it/s, bound:369 nc: 29 ncall:2.9e+04 eff:3.4% logz=586952.50+/-0.66 dlogz:6028.720>10]

987it [01:29, 11.63it/s, bound:370 nc: 25 ncall:2.9e+04 eff:3.4% logz=586991.82+/-0.66 dlogz:5981.745>10]

989it [01:29, 12.33it/s, bound:371 nc: 21 ncall:2.9e+04 eff:3.4% logz=587079.05+/-0.66 dlogz:5929.090>10]

991it [01:29, 12.73it/s, bound:371 nc: 36 ncall:2.9e+04 eff:3.4% logz=587157.46+/-0.66 dlogz:5831.571>10]

993it [01:29, 13.47it/s, bound:372 nc: 21 ncall:3.0e+04 eff:3.4% logz=587329.21+/-0.66 dlogz:5630.018>10]

995it [01:29, 14.24it/s, bound:373 nc: 22 ncall:3.0e+04 eff:3.4% logz=587438.85+/-0.66 dlogz:5598.342>10]

997it [01:29, 14.13it/s, bound:373 nc: 29 ncall:3.0e+04 eff:3.4% logz=587608.59+/-0.66 dlogz:5458.578>10]

999it [01:30, 14.54it/s, bound:374 nc: 22 ncall:3.0e+04 eff:3.4% logz=587621.84+/-0.66 dlogz:5333.331>10]

1001it [01:30, 15.58it/s, bound:375 nc: 18 ncall:3.0e+04 eff:3.4% logz=587733.64+/-0.66 dlogz:5280.186>10]

1003it [01:30, 14.73it/s, bound:375 nc: 30 ncall:3.0e+04 eff:3.4% logz=587824.07+/-0.66 dlogz:5177.968>10]

1005it [01:30, 13.17it/s, bound:376 nc: 33 ncall:3.0e+04 eff:3.4% logz=587876.91+/-0.66 dlogz:5083.691>10]

1007it [01:30, 11.68it/s, bound:378 nc: 24 ncall:3.0e+04 eff:3.4% logz=587907.65+/-0.66 dlogz:5062.296>10]

1009it [01:30, 12.99it/s, bound:378 nc: 16 ncall:3.0e+04 eff:3.4% logz=587974.65+/-0.66 dlogz:5021.663>10]

1011it [01:31, 13.38it/s, bound:379 nc: 19 ncall:3.0e+04 eff:3.4% logz=588093.50+/-0.66 dlogz:4885.620>10]

1013it [01:31, 13.22it/s, bound:380 nc: 18 ncall:3.0e+04 eff:3.4% logz=588153.19+/-0.66 dlogz:4806.739>10]

1015it [01:31, 13.00it/s, bound:380 nc: 30 ncall:3.0e+04 eff:3.4% logz=588202.45+/-0.66 dlogz:4814.739>10]

1017it [01:31, 11.37it/s, bound:382 nc: 26 ncall:3.0e+04 eff:3.4% logz=588271.91+/-0.66 dlogz:4775.014>10]

1019it [01:31, 12.23it/s, bound:383 nc: 14 ncall:3.0e+04 eff:3.4% logz=588306.69+/-0.66 dlogz:4706.881>10]

1021it [01:31, 12.58it/s, bound:383 nc: 24 ncall:3.0e+04 eff:3.4% logz=588373.08+/-0.66 dlogz:4640.027>10]

1023it [01:32, 12.13it/s, bound:384 nc: 20 ncall:3.0e+04 eff:3.4% logz=588416.51+/-0.66 dlogz:4588.018>10]

1025it [01:32, 13.02it/s, bound:385 nc: 26 ncall:3.0e+04 eff:3.4% logz=588550.21+/-0.67 dlogz:4571.486>10]

1027it [01:32, 13.73it/s, bound:386 nc: 24 ncall:3.0e+04 eff:3.4% logz=588761.97+/-0.67 dlogz:4285.549>10]

1029it [01:32, 13.89it/s, bound:386 nc: 24 ncall:3.0e+04 eff:3.4% logz=588814.03+/-0.67 dlogz:4231.069>10]

1031it [01:32, 14.29it/s, bound:387 nc: 23 ncall:3.0e+04 eff:3.4% logz=588836.89+/-0.67 dlogz:4169.556>10]

1033it [01:32, 14.73it/s, bound:388 nc: 23 ncall:3.0e+04 eff:3.4% logz=588843.32+/-0.66 dlogz:4155.398>10]

1035it [01:32, 14.28it/s, bound:388 nc: 27 ncall:3.1e+04 eff:3.4% logz=588874.99+/-0.67 dlogz:4147.692>10]

1037it [01:32, 15.21it/s, bound:389 nc: 16 ncall:3.1e+04 eff:3.4% logz=588933.59+/-0.67 dlogz:4074.851>10]

1039it [01:33, 14.02it/s, bound:390 nc: 26 ncall:3.1e+04 eff:3.4% logz=588947.24+/-0.67 dlogz:4055.651>10]

1041it [01:33, 14.30it/s, bound:391 nc: 21 ncall:3.1e+04 eff:3.4% logz=589066.75+/-0.67 dlogz:3947.926>10]

1043it [01:33, 14.54it/s, bound:392 nc: 16 ncall:3.1e+04 eff:3.4% logz=589086.64+/-0.67 dlogz:3922.187>10]

1046it [01:33, 17.25it/s, bound:392 nc: 11 ncall:3.1e+04 eff:3.4% logz=589178.10+/-0.67 dlogz:3836.013>10]

1048it [01:33, 16.01it/s, bound:393 nc: 19 ncall:3.1e+04 eff:3.4% logz=589222.75+/-0.67 dlogz:3792.873>10]

1050it [01:33, 16.62it/s, bound:394 nc: 20 ncall:3.1e+04 eff:3.4% logz=589260.25+/-0.67 dlogz:3738.770>10]

1052it [01:33, 17.02it/s, bound:395 nc: 20 ncall:3.1e+04 eff:3.4% logz=589335.32+/-0.67 dlogz:3672.004>10]

1054it [01:34, 16.34it/s, bound:395 nc: 25 ncall:3.1e+04 eff:3.4% logz=589384.40+/-0.67 dlogz:3627.345>10]

1056it [01:34, 13.99it/s, bound:396 nc: 27 ncall:3.1e+04 eff:3.4% logz=589454.86+/-0.67 dlogz:3605.709>10]

1058it [01:34, 13.93it/s, bound:397 nc: 26 ncall:3.1e+04 eff:3.4% logz=589491.06+/-0.67 dlogz:3515.827>10]

1060it [01:34, 11.70it/s, bound:399 nc: 27 ncall:3.1e+04 eff:3.4% logz=589527.62+/-0.67 dlogz:3486.382>10]

1062it [01:34, 12.85it/s, bound:400 nc: 14 ncall:3.1e+04 eff:3.4% logz=589603.29+/-0.67 dlogz:3465.950>10]

1064it [01:34, 12.92it/s, bound:400 nc: 22 ncall:3.1e+04 eff:3.4% logz=589639.44+/-0.67 dlogz:3381.635>10]

1066it [01:35, 12.44it/s, bound:401 nc: 21 ncall:3.1e+04 eff:3.4% logz=589671.93+/-0.67 dlogz:3339.670>10]

1068it [01:35, 12.82it/s, bound:402 nc: 26 ncall:3.1e+04 eff:3.4% logz=589747.81+/-0.68 dlogz:3269.713>10]

1071it [01:35, 14.69it/s, bound:403 nc: 19 ncall:3.1e+04 eff:3.4% logz=589872.23+/-0.68 dlogz:3131.027>10]

1073it [01:35, 14.04it/s, bound:404 nc: 24 ncall:3.1e+04 eff:3.4% logz=589887.83+/-0.68 dlogz:3121.151>10]

1075it [01:35, 14.55it/s, bound:404 nc: 19 ncall:3.1e+04 eff:3.4% logz=589960.01+/-0.68 dlogz:3056.616>10]

1077it [01:35, 15.38it/s, bound:405 nc: 14 ncall:3.1e+04 eff:3.4% logz=590031.86+/-0.68 dlogz:3011.573>10]

1079it [01:35, 13.97it/s, bound:406 nc: 22 ncall:3.2e+04 eff:3.4% logz=590070.65+/-0.67 dlogz:2927.889>10]

1081it [01:36, 12.95it/s, bound:407 nc: 32 ncall:3.2e+04 eff:3.4% logz=590156.37+/-0.68 dlogz:2902.650>10]

1083it [01:36, 13.48it/s, bound:408 nc: 25 ncall:3.2e+04 eff:3.4% logz=590184.65+/-0.68 dlogz:2836.170>10]

1085it [01:36, 13.54it/s, bound:409 nc: 14 ncall:3.2e+04 eff:3.4% logz=590215.55+/-0.68 dlogz:2783.142>10]

1087it [01:36, 14.83it/s, bound:409 nc: 15 ncall:3.2e+04 eff:3.4% logz=590257.27+/-0.67 dlogz:2739.994>10]

1089it [01:36, 13.66it/s, bound:410 nc: 39 ncall:3.2e+04 eff:3.4% logz=590261.15+/-0.66 dlogz:2734.462>10]

1091it [01:36, 10.69it/s, bound:412 nc: 25 ncall:3.2e+04 eff:3.4% logz=590321.26+/-0.67 dlogz:2721.582>10]

1093it [01:37, 10.27it/s, bound:413 nc: 22 ncall:3.2e+04 eff:3.4% logz=590495.70+/-0.68 dlogz:2584.138>10]

1096it [01:37, 12.68it/s, bound:414 nc: 19 ncall:3.2e+04 eff:3.4% logz=590551.16+/-0.68 dlogz:2482.142>10]

1098it [01:37, 12.39it/s, bound:415 nc: 12 ncall:3.2e+04 eff:3.4% logz=590602.36+/-0.68 dlogz:2434.170>10]

1101it [01:37, 14.48it/s, bound:415 nc: 18 ncall:3.2e+04 eff:3.4% logz=590663.66+/-0.68 dlogz:2338.107>10]

1103it [01:37, 13.30it/s, bound:416 nc: 19 ncall:3.2e+04 eff:3.4% logz=590676.17+/-0.68 dlogz:2323.662>10]

1105it [01:37, 14.11it/s, bound:417 nc: 20 ncall:3.2e+04 eff:3.4% logz=590704.47+/-0.67 dlogz:2291.773>10]

1107it [01:38, 15.17it/s, bound:418 nc: 18 ncall:3.2e+04 eff:3.4% logz=590818.67+/-0.68 dlogz:2207.757>10]

1109it [01:38, 12.04it/s, bound:419 nc: 21 ncall:3.2e+04 eff:3.4% logz=590892.24+/-0.68 dlogz:2211.936>10]

1111it [01:38, 13.28it/s, bound:419 nc: 20 ncall:3.2e+04 eff:3.4% logz=590940.03+/-0.68 dlogz:2132.684>10]

1113it [01:39,  4.88it/s, bound:420 nc: 58 ncall:3.2e+04 eff:3.4% logz=590974.15+/-0.69 dlogz:2074.819>10]

1115it [01:40,  4.18it/s, bound:421 nc: 22 ncall:3.2e+04 eff:3.4% logz=591002.64+/-0.69 dlogz:2036.781>10]

1116it [01:40,  4.30it/s, bound:422 nc: 15 ncall:3.2e+04 eff:3.4% logz=591004.16+/-0.67 dlogz:2029.605>10]

1117it [01:40,  4.21it/s, bound:422 nc: 21 ncall:3.2e+04 eff:3.4% logz=591005.01+/-0.66 dlogz:2028.077>10]

1118it [01:40,  4.09it/s, bound:422 nc: 20 ncall:3.3e+04 eff:3.4% logz=591086.63+/-0.69 dlogz:2027.219>10]

1119it [01:41,  2.67it/s, bound:423 nc: 62 ncall:3.3e+04 eff:3.4% logz=591135.32+/-0.69 dlogz:1945.587>10]

1120it [01:42,  2.50it/s, bound:424 nc: 37 ncall:3.3e+04 eff:3.4% logz=591139.57+/-0.68 dlogz:1896.881>10]

1121it [01:42,  1.98it/s, bound:424 nc: 60 ncall:3.3e+04 eff:3.4% logz=591168.57+/-0.69 dlogz:1892.615>10]

1122it [01:43,  2.36it/s, bound:425 nc: 15 ncall:3.3e+04 eff:3.4% logz=591170.14+/-0.67 dlogz:1961.692>10]

1123it [01:43,  2.74it/s, bound:425 nc: 18 ncall:3.3e+04 eff:3.4% logz=591209.01+/-0.69 dlogz:1960.109>10]

1124it [01:43,  2.75it/s, bound:425 nc: 72 ncall:3.3e+04 eff:3.4% logz=591211.51+/-0.68 dlogz:2525.747>10]

1126it [01:43,  4.24it/s, bound:426 nc: 28 ncall:3.3e+04 eff:3.4% logz=591223.24+/-0.69 dlogz:2522.161>10]

1128it [01:43,  5.81it/s, bound:427 nc: 23 ncall:3.3e+04 eff:3.4% logz=591234.14+/-0.67 dlogz:2503.912>10]

1130it [01:44,  7.23it/s, bound:428 nc: 19 ncall:3.3e+04 eff:3.4% logz=591260.06+/-0.69 dlogz:2478.985>10]

1133it [01:44,  8.66it/s, bound:429 nc: 53 ncall:3.3e+04 eff:3.4% logz=591319.41+/-0.69 dlogz:2909.373>10]

1135it [01:44,  9.50it/s, bound:430 nc: 35 ncall:3.3e+04 eff:3.4% logz=591324.67+/-0.69 dlogz:2901.698>10]

1138it [01:44, 11.61it/s, bound:431 nc: 28 ncall:3.3e+04 eff:3.4% logz=591397.39+/-0.69 dlogz:2847.831>10]

1140it [01:44, 12.48it/s, bound:432 nc: 19 ncall:3.3e+04 eff:3.4% logz=591405.34+/-0.69 dlogz:2822.717>10]

1142it [01:44, 13.23it/s, bound:433 nc: 24 ncall:3.3e+04 eff:3.4% logz=591428.09+/-0.69 dlogz:2803.149>10]

1144it [01:45, 13.71it/s, bound:433 nc: 27 ncall:3.3e+04 eff:3.4% logz=591432.73+/-0.69 dlogz:2792.809>10]

1146it [01:45, 13.95it/s, bound:434 nc: 28 ncall:3.3e+04 eff:3.4% logz=591514.53+/-0.69 dlogz:2747.419>10]

1148it [01:45, 11.97it/s, bound:435 nc: 23 ncall:3.3e+04 eff:3.4% logz=591540.07+/-0.69 dlogz:2685.232>10]

1150it [01:46,  3.88it/s, bound:436 nc: 46 ncall:3.3e+04 eff:3.4% logz=591552.43+/-0.68 dlogz:2672.749>10]

1151it [01:47,  3.93it/s, bound:436 nc: 17 ncall:3.3e+04 eff:3.4% logz=591561.50+/-0.69 dlogz:2670.019>10]

1152it [01:47,  3.86it/s, bound:437 nc: 23 ncall:3.3e+04 eff:3.4% logz=591595.51+/-0.69 dlogz:2660.935>10]

1153it [01:47,  3.50it/s, bound:437 nc: 29 ncall:3.3e+04 eff:3.4% logz=591614.49+/-0.69 dlogz:2626.912>10]

1154it [01:47,  3.53it/s, bound:438 nc: 20 ncall:3.4e+04 eff:3.4% logz=591618.54+/-0.69 dlogz:2607.917>10]

1155it [01:48,  2.87it/s, bound:438 nc: 40 ncall:3.4e+04 eff:3.4% logz=591651.83+/-0.69 dlogz:2603.854>10]

1156it [01:48,  3.27it/s, bound:439 nc: 13 ncall:3.4e+04 eff:3.4% logz=591660.96+/-0.69 dlogz:2570.550>10]

1157it [01:48,  3.30it/s, bound:439 nc: 20 ncall:3.4e+04 eff:3.4% logz=591663.91+/-0.69 dlogz:2561.407>10]

1158it [01:49,  3.70it/s, bound:439 nc: 13 ncall:3.4e+04 eff:3.4% logz=591668.08+/-0.69 dlogz:2558.445>10]

1159it [01:49,  3.82it/s, bound:439 nc: 21 ncall:3.4e+04 eff:3.4% logz=591697.88+/-0.70 dlogz:2554.262>10]

1161it [01:49,  4.41it/s, bound:440 nc: 24 ncall:3.4e+04 eff:3.5% logz=591723.43+/-0.68 dlogz:2515.618>10]

1162it [01:49,  4.80it/s, bound:440 nc: 12 ncall:3.4e+04 eff:3.5% logz=591727.85+/-0.69 dlogz:2514.338>10]

1163it [01:50,  4.33it/s, bound:440 nc: 22 ncall:3.4e+04 eff:3.5% logz=591741.02+/-0.70 dlogz:2509.904>10]

1164it [01:50,  4.12it/s, bound:441 nc: 24 ncall:3.4e+04 eff:3.5% logz=591791.77+/-0.70 dlogz:2496.722>10]

1165it [01:50,  4.10it/s, bound:441 nc: 20 ncall:3.4e+04 eff:3.5% logz=591802.43+/-0.70 dlogz:2445.964>10]

1166it [01:50,  4.37it/s, bound:441 nc: 15 ncall:3.4e+04 eff:3.5% logz=591804.70+/-0.69 dlogz:2435.284>10]

1167it [01:51,  4.70it/s, bound:442 nc: 14 ncall:3.4e+04 eff:3.5% logz=591817.21+/-0.70 dlogz:2433.006>10]

1168it [01:51,  4.80it/s, bound:442 nc: 16 ncall:3.4e+04 eff:3.5% logz=591838.56+/-0.70 dlogz:2420.487>10]

1169it [01:51,  4.35it/s, bound:442 nc: 24 ncall:3.4e+04 eff:3.5% logz=591866.11+/-0.70 dlogz:2399.123>10]

1170it [01:52,  2.86it/s, bound:443 nc: 51 ncall:3.4e+04 eff:3.5% logz=591869.00+/-0.69 dlogz:2371.562>10]

1171it [01:52,  2.53it/s, bound:444 nc: 41 ncall:3.4e+04 eff:3.5% logz=591875.10+/-0.69 dlogz:2368.655>10]

1172it [01:52,  2.97it/s, bound:444 nc: 15 ncall:3.4e+04 eff:3.5% logz=591895.65+/-0.70 dlogz:2362.542>10]

1173it [01:53,  2.74it/s, bound:445 nc: 35 ncall:3.4e+04 eff:3.5% logz=591912.20+/-0.70 dlogz:2341.977>10]

1174it [01:53,  2.86it/s, bound:445 nc: 26 ncall:3.4e+04 eff:3.5% logz=591915.81+/-0.69 dlogz:2325.416>10]

1175it [01:53,  3.05it/s, bound:446 nc: 22 ncall:3.4e+04 eff:3.5% logz=591919.59+/-0.70 dlogz:2321.796>10]

1176it [01:54,  3.27it/s, bound:446 nc: 20 ncall:3.4e+04 eff:3.5% logz=591922.77+/-0.69 dlogz:2318.009>10]

1177it [01:54,  3.57it/s, bound:446 nc: 19 ncall:3.4e+04 eff:3.5% logz=591932.01+/-0.70 dlogz:2314.815>10]

1178it [01:54,  3.33it/s, bound:447 nc: 30 ncall:3.4e+04 eff:3.5% logz=591957.97+/-0.70 dlogz:2305.560>10]

1179it [01:55,  3.34it/s, bound:447 nc: 25 ncall:3.4e+04 eff:3.5% logz=591997.63+/-0.70 dlogz:2279.584>10]

1180it [01:55,  3.70it/s, bound:448 nc: 16 ncall:3.4e+04 eff:3.5% logz=592020.95+/-0.70 dlogz:2239.917>10]

1181it [01:55,  3.65it/s, bound:448 nc: 23 ncall:3.4e+04 eff:3.5% logz=592029.91+/-0.70 dlogz:2216.581>10]

1182it [01:55,  3.60it/s, bound:448 nc: 24 ncall:3.4e+04 eff:3.5% logz=592046.57+/-0.70 dlogz:2207.608>10]

1183it [01:55,  4.22it/s, bound:449 nc: 11 ncall:3.4e+04 eff:3.5% logz=592047.92+/-0.68 dlogz:2190.936>10]

1184it [01:56,  4.01it/s, bound:449 nc: 22 ncall:3.4e+04 eff:3.5% logz=592057.74+/-0.70 dlogz:2189.574>10]

1185it [01:56,  3.37it/s, bound:449 nc: 31 ncall:3.4e+04 eff:3.5% logz=592062.25+/-0.70 dlogz:2179.741>10]

1186it [01:56,  3.58it/s, bound:450 nc: 20 ncall:3.4e+04 eff:3.5% logz=592063.62+/-0.68 dlogz:2175.225>10]

1187it [01:57,  3.68it/s, bound:450 nc: 22 ncall:3.4e+04 eff:3.5% logz=592067.10+/-0.70 dlogz:2173.834>10]

1188it [01:57,  3.74it/s, bound:450 nc: 20 ncall:3.4e+04 eff:3.5% logz=592069.11+/-0.69 dlogz:2170.346>10]

1189it [01:57,  3.36it/s, bound:451 nc: 27 ncall:3.4e+04 eff:3.5% logz=592073.82+/-0.70 dlogz:2168.328>10]

1190it [01:58,  2.19it/s, bound:451 nc: 65 ncall:3.4e+04 eff:3.5% logz=592086.36+/-0.70 dlogz:2163.601>10]

1191it [01:59,  2.26it/s, bound:452 nc: 34 ncall:3.4e+04 eff:3.5% logz=592091.21+/-0.70 dlogz:2151.045>10]

1192it [01:59,  2.43it/s, bound:452 nc: 29 ncall:3.4e+04 eff:3.5% logz=592110.59+/-0.70 dlogz:2146.187>10]

1193it [02:00,  2.06it/s, bound:453 nc: 51 ncall:3.4e+04 eff:3.5% logz=592112.34+/-0.69 dlogz:2126.793>10]

1194it [02:00,  2.18it/s, bound:454 nc: 34 ncall:3.5e+04 eff:3.5% logz=592120.56+/-0.70 dlogz:2125.033>10]

1195it [02:00,  2.12it/s, bound:454 nc: 44 ncall:3.5e+04 eff:3.5% logz=592131.63+/-0.70 dlogz:2116.794>10]

1196it [02:01,  2.46it/s, bound:455 nc: 20 ncall:3.5e+04 eff:3.5% logz=592133.72+/-0.69 dlogz:2105.718>10]

1197it [02:01,  2.62it/s, bound:455 nc: 27 ncall:3.5e+04 eff:3.5% logz=592147.70+/-0.70 dlogz:2103.611>10]

1198it [02:01,  2.89it/s, bound:455 nc: 24 ncall:3.5e+04 eff:3.5% logz=592169.35+/-0.70 dlogz:2089.625>10]

1199it [02:02,  2.94it/s, bound:456 nc: 26 ncall:3.5e+04 eff:3.5% logz=592180.80+/-0.70 dlogz:2067.954>10]

1200it [02:02,  3.06it/s, bound:456 nc: 27 ncall:3.5e+04 eff:3.5% logz=592197.83+/-0.70 dlogz:2056.500>10]

1201it [02:02,  3.10it/s, bound:457 nc: 25 ncall:3.5e+04 eff:3.5% logz=592200.74+/-0.70 dlogz:2039.457>10]

1202it [02:03,  3.09it/s, bound:457 nc: 26 ncall:3.5e+04 eff:3.5% logz=592208.25+/-0.70 dlogz:2036.531>10]

1203it [02:03,  3.23it/s, bound:458 nc: 25 ncall:3.5e+04 eff:3.5% logz=592210.28+/-0.69 dlogz:2029.011>10]

1204it [02:03,  3.47it/s, bound:458 nc: 22 ncall:3.5e+04 eff:3.5% logz=592215.80+/-0.70 dlogz:2026.962>10]

1205it [02:03,  3.34it/s, bound:458 nc: 29 ncall:3.5e+04 eff:3.5% logz=592265.49+/-0.71 dlogz:2021.430>10]

1206it [02:04,  3.64it/s, bound:459 nc: 18 ncall:3.5e+04 eff:3.5% logz=592273.07+/-0.71 dlogz:1971.728>10]

1207it [02:04,  3.70it/s, bound:459 nc: 23 ncall:3.5e+04 eff:3.5% logz=592276.80+/-0.70 dlogz:1964.140>10]

1208it [02:04,  3.11it/s, bound:459 nc: 38 ncall:3.5e+04 eff:3.5% logz=592280.92+/-0.70 dlogz:1960.399>10]

1209it [02:05,  3.24it/s, bound:460 nc: 25 ncall:3.5e+04 eff:3.5% logz=592283.74+/-0.69 dlogz:1956.262>10]

1210it [02:05,  3.22it/s, bound:460 nc: 27 ncall:3.5e+04 eff:3.5% logz=592288.98+/-0.71 dlogz:1953.437>10]

1211it [02:05,  3.39it/s, bound:461 nc: 22 ncall:3.5e+04 eff:3.5% logz=592312.04+/-0.71 dlogz:1948.179>10]

1212it [02:05,  3.55it/s, bound:461 nc: 21 ncall:3.5e+04 eff:3.5% logz=592317.79+/-0.71 dlogz:1925.105>10]

1213it [02:06,  3.66it/s, bound:461 nc: 23 ncall:3.5e+04 eff:3.5% logz=592332.75+/-0.71 dlogz:1919.343>10]

1214it [02:06,  3.56it/s, bound:462 nc: 27 ncall:3.5e+04 eff:3.5% logz=592365.26+/-0.71 dlogz:1904.374>10]

1215it [02:06,  4.09it/s, bound:462 nc: 14 ncall:3.5e+04 eff:3.5% logz=592379.64+/-0.71 dlogz:1871.852>10]

1216it [02:06,  4.11it/s, bound:462 nc: 21 ncall:3.5e+04 eff:3.5% logz=592383.35+/-0.70 dlogz:1857.459>10]

1217it [02:07,  3.89it/s, bound:463 nc: 24 ncall:3.5e+04 eff:3.5% logz=592407.26+/-0.71 dlogz:1853.739>10]

1218it [02:07,  4.19it/s, bound:463 nc: 15 ncall:3.5e+04 eff:3.5% logz=592430.96+/-0.71 dlogz:1829.813>10]

1219it [02:07,  2.83it/s, bound:463 nc: 57 ncall:3.5e+04 eff:3.5% logz=592433.48+/-0.70 dlogz:1806.095>10]

1220it [02:08,  3.06it/s, bound:464 nc: 24 ncall:3.5e+04 eff:3.5% logz=592443.49+/-0.71 dlogz:1803.572>10]

1221it [02:08,  2.39it/s, bound:464 nc: 58 ncall:3.5e+04 eff:3.5% logz=592450.07+/-0.71 dlogz:1793.549>10]

1222it [02:09,  2.65it/s, bound:465 nc: 23 ncall:3.5e+04 eff:3.5% logz=592477.72+/-0.71 dlogz:1786.954>10]

1223it [02:09,  3.03it/s, bound:465 nc: 19 ncall:3.5e+04 eff:3.5% logz=592487.56+/-0.71 dlogz:1759.294>10]

1224it [02:09,  3.28it/s, bound:465 nc: 23 ncall:3.5e+04 eff:3.5% logz=592509.54+/-0.71 dlogz:1749.434>10]

1225it [02:09,  3.54it/s, bound:466 nc: 20 ncall:3.5e+04 eff:3.5% logz=592517.15+/-0.71 dlogz:1727.442>10]

1226it [02:10,  3.61it/s, bound:466 nc: 24 ncall:3.5e+04 eff:3.5% logz=592531.98+/-0.71 dlogz:1719.820>10]

1227it [02:10,  3.31it/s, bound:466 nc: 31 ncall:3.5e+04 eff:3.5% logz=592534.62+/-0.70 dlogz:1704.980>10]

1228it [02:10,  3.60it/s, bound:467 nc: 21 ncall:3.5e+04 eff:3.5% logz=592535.63+/-0.69 dlogz:1702.326>10]

1229it [02:10,  3.43it/s, bound:467 nc: 27 ncall:3.5e+04 eff:3.5% logz=592549.71+/-0.71 dlogz:1701.311>10]

1230it [02:11,  2.26it/s, bound:469 nc: 67 ncall:3.5e+04 eff:3.5% logz=592554.90+/-0.71 dlogz:1687.209>10]

1231it [02:12,  2.61it/s, bound:469 nc: 21 ncall:3.6e+04 eff:3.5% logz=592556.94+/-0.70 dlogz:1682.010>10]

1232it [02:12,  2.84it/s, bound:469 nc: 23 ncall:3.6e+04 eff:3.5% logz=592559.91+/-0.70 dlogz:1679.956>10]

1233it [02:12,  2.71it/s, bound:470 nc: 31 ncall:3.6e+04 eff:3.5% logz=592586.22+/-0.71 dlogz:1676.975>10]

1234it [02:13,  2.81it/s, bound:470 nc: 28 ncall:3.6e+04 eff:3.5% logz=592602.39+/-0.71 dlogz:1650.651>10]

1235it [02:13,  3.07it/s, bound:471 nc: 21 ncall:3.6e+04 eff:3.5% logz=592606.28+/-0.71 dlogz:1634.469>10]

1236it [02:13,  3.29it/s, bound:471 nc: 21 ncall:3.6e+04 eff:3.5% logz=592618.99+/-0.71 dlogz:1630.572>10]

1237it [02:13,  3.48it/s, bound:471 nc: 22 ncall:3.6e+04 eff:3.5% logz=592622.17+/-0.71 dlogz:1617.849>10]

1238it [02:14,  3.73it/s, bound:472 nc: 19 ncall:3.6e+04 eff:3.5% logz=592623.25+/-0.69 dlogz:1614.656>10]

1239it [02:14,  3.04it/s, bound:472 nc: 41 ncall:3.6e+04 eff:3.5% logz=592640.67+/-0.71 dlogz:1613.563>10]

1240it [02:15,  2.27it/s, bound:473 nc: 62 ncall:3.6e+04 eff:3.5% logz=592645.43+/-0.71 dlogz:1596.132>10]

1241it [02:15,  2.49it/s, bound:474 nc: 26 ncall:3.6e+04 eff:3.5% logz=592646.97+/-0.70 dlogz:1684.241>10]

1242it [02:15,  2.96it/s, bound:474 nc: 17 ncall:3.6e+04 eff:3.5% logz=592656.30+/-0.71 dlogz:1682.682>10]

1243it [02:15,  3.25it/s, bound:474 nc: 22 ncall:3.6e+04 eff:3.5% logz=592667.26+/-0.71 dlogz:1673.341>10]

1244it [02:16,  3.70it/s, bound:475 nc: 16 ncall:3.6e+04 eff:3.5% logz=592677.56+/-0.71 dlogz:1662.366>10]

1245it [02:16,  3.67it/s, bound:475 nc: 25 ncall:3.6e+04 eff:3.5% logz=592704.85+/-0.71 dlogz:1652.060>10]

1246it [02:16,  4.05it/s, bound:475 nc: 16 ncall:3.6e+04 eff:3.5% logz=592706.18+/-0.70 dlogz:1624.750>10]

1247it [02:16,  3.98it/s, bound:476 nc: 21 ncall:3.6e+04 eff:3.5% logz=592708.70+/-0.71 dlogz:1623.417>10]

1248it [02:17,  4.03it/s, bound:476 nc: 20 ncall:3.6e+04 eff:3.5% logz=592719.16+/-0.72 dlogz:1620.883>10]

1249it [02:17,  3.80it/s, bound:476 nc: 26 ncall:3.6e+04 eff:3.5% logz=592734.75+/-0.72 dlogz:1610.404>10]

1250it [02:17,  4.24it/s, bound:477 nc: 14 ncall:3.6e+04 eff:3.5% logz=592736.38+/-0.70 dlogz:1594.806>10]

1251it [02:17,  3.99it/s, bound:477 nc: 24 ncall:3.6e+04 eff:3.5% logz=592737.24+/-0.69 dlogz:1593.160>10]

1252it [02:18,  4.06it/s, bound:477 nc: 21 ncall:3.6e+04 eff:3.5% logz=592745.57+/-0.72 dlogz:1592.286>10]

1253it [02:18,  3.95it/s, bound:478 nc: 21 ncall:3.6e+04 eff:3.5% logz=592747.13+/-0.70 dlogz:1583.947>10]

1254it [02:18,  3.62it/s, bound:478 nc: 27 ncall:3.6e+04 eff:3.5% logz=592769.99+/-0.72 dlogz:1582.379>10]

1255it [02:18,  4.03it/s, bound:479 nc: 15 ncall:3.6e+04 eff:3.5% logz=592775.60+/-0.72 dlogz:1559.502>10]

1256it [02:19,  4.19it/s, bound:479 nc: 20 ncall:3.6e+04 eff:3.5% logz=592776.90+/-0.70 dlogz:1553.878>10]

1257it [02:19,  3.84it/s, bound:479 nc: 26 ncall:3.6e+04 eff:3.5% logz=592805.47+/-0.72 dlogz:1552.565>10]

1258it [02:19,  3.92it/s, bound:480 nc: 21 ncall:3.6e+04 eff:3.5% logz=592807.14+/-0.70 dlogz:1523.983>10]

1259it [02:19,  3.81it/s, bound:480 nc: 28 ncall:3.6e+04 eff:3.5% logz=592810.89+/-0.71 dlogz:1522.301>10]

1260it [02:20,  3.70it/s, bound:481 nc: 25 ncall:3.6e+04 eff:3.5% logz=592820.92+/-0.72 dlogz:1518.546>10]

1261it [02:20,  3.56it/s, bound:481 nc: 27 ncall:3.6e+04 eff:3.5% logz=592829.84+/-0.72 dlogz:1508.494>10]

1262it [02:20,  3.75it/s, bound:482 nc: 21 ncall:3.6e+04 eff:3.5% logz=592831.33+/-0.70 dlogz:1499.568>10]

1263it [02:20,  3.73it/s, bound:482 nc: 25 ncall:3.6e+04 eff:3.5% logz=592839.96+/-0.72 dlogz:1498.067>10]

1264it [02:22,  2.03it/s, bound:483 nc: 90 ncall:3.6e+04 eff:3.5% logz=592843.54+/-0.71 dlogz:1489.421>10]

1265it [02:22,  2.26it/s, bound:483 nc: 26 ncall:3.6e+04 eff:3.5% logz=592850.75+/-0.72 dlogz:1824.145>10]

1266it [02:22,  2.80it/s, bound:484 nc: 13 ncall:3.6e+04 eff:3.5% logz=592854.75+/-0.72 dlogz:1816.920>10]

1267it [02:22,  3.21it/s, bound:484 nc: 18 ncall:3.6e+04 eff:3.5% logz=592864.82+/-0.72 dlogz:1812.910>10]

1268it [02:22,  3.42it/s, bound:484 nc: 27 ncall:3.6e+04 eff:3.5% logz=592867.44+/-0.71 dlogz:1802.825>10]

1269it [02:23,  3.92it/s, bound:485 nc: 16 ncall:3.6e+04 eff:3.5% logz=592875.53+/-0.72 dlogz:1800.187>10]

1270it [02:23,  2.78it/s, bound:485 nc: 56 ncall:3.7e+04 eff:3.5% logz=592879.63+/-0.72 dlogz:1792.089>10]

1271it [02:23,  3.06it/s, bound:486 nc: 24 ncall:3.7e+04 eff:3.5% logz=592881.17+/-0.70 dlogz:1787.974>10]

1272it [02:24,  3.26it/s, bound:486 nc: 24 ncall:3.7e+04 eff:3.5% logz=592891.45+/-0.72 dlogz:1786.419>10]

1273it [02:24,  2.96it/s, bound:487 nc: 34 ncall:3.7e+04 eff:3.5% logz=592903.05+/-0.72 dlogz:1776.127>10]

1274it [02:25,  2.79it/s, bound:487 nc: 39 ncall:3.7e+04 eff:3.5% logz=592904.79+/-0.71 dlogz:1764.519>10]

1275it [02:25,  3.16it/s, bound:488 nc: 22 ncall:3.7e+04 eff:3.5% logz=592916.98+/-0.72 dlogz:1762.765>10]

1276it [02:25,  3.50it/s, bound:488 nc: 22 ncall:3.7e+04 eff:3.5% logz=592926.80+/-0.72 dlogz:1750.561>10]

1277it [02:25,  4.12it/s, bound:488 nc: 12 ncall:3.7e+04 eff:3.5% logz=592930.25+/-0.72 dlogz:1740.735>10]

1278it [02:26,  3.32it/s, bound:489 nc: 37 ncall:3.7e+04 eff:3.5% logz=592936.32+/-0.72 dlogz:1737.268>10]

1279it [02:26,  3.63it/s, bound:489 nc: 20 ncall:3.7e+04 eff:3.5% logz=592940.01+/-0.72 dlogz:1731.183>10]

1280it [02:26,  4.27it/s, bound:490 nc: 12 ncall:3.7e+04 eff:3.5% logz=592945.68+/-0.72 dlogz:1727.484>10]

1281it [02:26,  3.96it/s, bound:490 nc: 27 ncall:3.7e+04 eff:3.5% logz=592947.52+/-0.71 dlogz:1721.806>10]

1282it [02:26,  4.25it/s, bound:490 nc: 17 ncall:3.7e+04 eff:3.5% logz=592953.68+/-0.72 dlogz:1719.947>10]

1283it [02:27,  4.35it/s, bound:491 nc: 20 ncall:3.7e+04 eff:3.5% logz=592954.86+/-0.70 dlogz:1713.778>10]

1284it [02:27,  4.13it/s, bound:491 nc: 24 ncall:3.7e+04 eff:3.5% logz=592985.86+/-0.72 dlogz:1712.586>10]

1285it [02:27,  4.26it/s, bound:491 nc: 19 ncall:3.7e+04 eff:3.5% logz=592987.51+/-0.71 dlogz:1681.568>10]

1286it [02:27,  3.63it/s, bound:492 nc: 32 ncall:3.7e+04 eff:3.5% logz=592996.15+/-0.72 dlogz:1679.915>10]

1287it [02:28,  3.35it/s, bound:492 nc: 31 ncall:3.7e+04 eff:3.5% logz=592998.69+/-0.71 dlogz:1671.254>10]

1288it [02:28,  3.56it/s, bound:493 nc: 21 ncall:3.7e+04 eff:3.5% logz=593003.55+/-0.72 dlogz:1668.702>10]

1289it [02:28,  3.14it/s, bound:493 nc: 35 ncall:3.7e+04 eff:3.5% logz=593013.21+/-0.72 dlogz:1663.834>10]

1290it [02:29,  3.40it/s, bound:494 nc: 20 ncall:3.7e+04 eff:3.5% logz=593025.00+/-0.72 dlogz:1654.163>10]

1291it [02:29,  3.20it/s, bound:494 nc: 31 ncall:3.7e+04 eff:3.5% logz=593042.64+/-0.72 dlogz:1642.357>10]

1292it [02:30,  2.72it/s, bound:495 nc: 42 ncall:3.7e+04 eff:3.5% logz=593063.00+/-0.72 dlogz:1624.707>10]

1293it [02:30,  3.32it/s, bound:495 nc: 12 ncall:3.7e+04 eff:3.5% logz=593072.59+/-0.72 dlogz:1604.336>10]

1294it [02:30,  3.54it/s, bound:496 nc: 21 ncall:3.7e+04 eff:3.5% logz=593078.44+/-0.72 dlogz:1594.730>10]

1295it [02:30,  3.31it/s, bound:496 nc: 31 ncall:3.7e+04 eff:3.5% logz=593082.52+/-0.72 dlogz:1588.864>10]

1296it [02:31,  3.28it/s, bound:497 nc: 25 ncall:3.7e+04 eff:3.5% logz=593087.03+/-0.72 dlogz:1584.775>10]

1297it [02:31,  2.96it/s, bound:497 nc: 37 ncall:3.7e+04 eff:3.5% logz=593089.79+/-0.72 dlogz:1580.252>10]

1298it [02:32,  2.44it/s, bound:498 nc: 51 ncall:3.7e+04 eff:3.5% logz=593092.44+/-0.72 dlogz:1577.476>10]

1299it [02:32,  2.75it/s, bound:499 nc: 23 ncall:3.7e+04 eff:3.5% logz=593101.09+/-0.73 dlogz:1574.816>10]

1300it [02:32,  3.18it/s, bound:499 nc: 17 ncall:3.7e+04 eff:3.5% logz=593117.98+/-0.73 dlogz:1566.158>10]

1301it [02:32,  3.33it/s, bound:499 nc: 23 ncall:3.7e+04 eff:3.5% logz=593122.96+/-0.72 dlogz:1549.253>10]

1302it [02:33,  3.25it/s, bound:500 nc: 27 ncall:3.7e+04 eff:3.5% logz=593144.24+/-0.73 dlogz:1544.258>10]

1303it [02:33,  3.37it/s, bound:500 nc: 24 ncall:3.7e+04 eff:3.5% logz=593148.76+/-0.72 dlogz:1522.966>10]

1304it [02:33,  3.90it/s, bound:501 nc: 15 ncall:3.7e+04 eff:3.5% logz=593197.90+/-0.73 dlogz:1518.440>10]

1305it [02:34,  3.01it/s, bound:501 nc: 44 ncall:3.7e+04 eff:3.5% logz=593205.75+/-0.73 dlogz:1469.288>10]

1306it [02:34,  3.33it/s, bound:502 nc: 19 ncall:3.7e+04 eff:3.5% logz=593215.67+/-0.73 dlogz:1461.417>10]

1307it [02:34,  3.54it/s, bound:502 nc: 21 ncall:3.7e+04 eff:3.5% logz=593216.77+/-0.71 dlogz:1451.487>10]

1308it [02:35,  2.64it/s, bound:502 nc: 55 ncall:3.8e+04 eff:3.5% logz=593218.43+/-0.71 dlogz:1450.381>10]

1309it [02:35,  2.82it/s, bound:503 nc: 25 ncall:3.8e+04 eff:3.5% logz=593220.53+/-0.71 dlogz:1448.707>10]

1310it [02:35,  3.03it/s, bound:503 nc: 24 ncall:3.8e+04 eff:3.5% logz=593223.82+/-0.72 dlogz:1446.588>10]

1311it [02:35,  3.69it/s, bound:504 nc: 11 ncall:3.8e+04 eff:3.5% logz=593225.05+/-0.71 dlogz:1443.288>10]

1312it [02:36,  3.83it/s, bound:504 nc: 20 ncall:3.8e+04 eff:3.5% logz=593227.55+/-0.72 dlogz:1442.047>10]

1313it [02:36,  3.64it/s, bound:504 nc: 23 ncall:3.8e+04 eff:3.5% logz=593228.82+/-0.71 dlogz:1439.533>10]

1314it [02:36,  3.38it/s, bound:505 nc: 28 ncall:3.8e+04 eff:3.5% logz=593230.46+/-0.71 dlogz:1438.252>10]

1315it [02:37,  3.30it/s, bound:505 nc: 28 ncall:3.8e+04 eff:3.5% logz=593246.07+/-0.73 dlogz:1436.598>10]

1317it [02:37,  5.06it/s, bound:506 nc: 15 ncall:3.8e+04 eff:3.5% logz=593274.46+/-0.73 dlogz:1400.062>10]

1318it [02:37,  5.74it/s, bound:506 nc: 28 ncall:3.8e+04 eff:3.5% logz=593277.12+/-0.72 dlogz:1392.562>10]

1320it [02:37,  7.82it/s, bound:507 nc: 20 ncall:3.8e+04 eff:3.5% logz=593292.62+/-0.72 dlogz:1377.410>10]

1322it [02:37,  9.14it/s, bound:508 nc: 21 ncall:3.8e+04 eff:3.5% logz=593297.74+/-0.73 dlogz:1373.256>10]

1324it [02:37,  9.88it/s, bound:508 nc: 32 ncall:3.8e+04 eff:3.5% logz=593313.54+/-0.73 dlogz:1357.055>10]

1326it [02:37, 11.61it/s, bound:509 nc: 17 ncall:3.8e+04 eff:3.5% logz=593317.97+/-0.71 dlogz:1351.252>10]

1328it [02:37, 13.30it/s, bound:510 nc: 21 ncall:3.8e+04 eff:3.5% logz=593342.49+/-0.73 dlogz:1346.368>10]

1330it [02:38, 11.71it/s, bound:511 nc: 26 ncall:3.8e+04 eff:3.5% logz=593347.13+/-0.73 dlogz:1323.140>10]

1332it [02:38, 12.40it/s, bound:511 nc: 26 ncall:3.8e+04 eff:3.5% logz=593360.25+/-0.73 dlogz:1317.969>10]

1334it [02:38, 10.74it/s, bound:513 nc: 29 ncall:3.8e+04 eff:3.5% logz=593362.70+/-0.71 dlogz:1305.156>10]

1336it [02:38, 11.57it/s, bound:513 nc: 31 ncall:3.8e+04 eff:3.5% logz=593383.24+/-0.73 dlogz:1300.888>10]

1338it [02:38, 12.63it/s, bound:514 nc: 18 ncall:3.8e+04 eff:3.5% logz=593393.50+/-0.72 dlogz:1275.026>10]

1340it [02:39, 12.13it/s, bound:515 nc: 18 ncall:3.8e+04 eff:3.5% logz=593405.58+/-0.73 dlogz:1267.552>10]

1342it [02:39, 13.30it/s, bound:515 nc: 21 ncall:3.8e+04 eff:3.5% logz=593408.56+/-0.72 dlogz:1259.919>10]

1344it [02:39, 14.27it/s, bound:516 nc: 20 ncall:3.8e+04 eff:3.5% logz=593414.19+/-0.72 dlogz:1253.618>10]

1346it [02:39, 14.33it/s, bound:517 nc: 21 ncall:3.8e+04 eff:3.5% logz=593440.03+/-0.74 dlogz:1233.216>10]

1348it [02:39, 12.16it/s, bound:518 nc: 47 ncall:3.9e+04 eff:3.5% logz=593454.30+/-0.74 dlogz:1219.708>10]

1350it [02:39, 11.64it/s, bound:519 nc: 22 ncall:3.9e+04 eff:3.5% logz=593458.31+/-0.72 dlogz:1210.222>10]

1352it [02:40,  9.34it/s, bound:520 nc: 22 ncall:3.9e+04 eff:3.5% logz=593461.89+/-0.72 dlogz:1206.085>10]

1354it [02:40,  9.93it/s, bound:521 nc: 19 ncall:3.9e+04 eff:3.5% logz=593485.03+/-0.74 dlogz:1198.565>10]

1357it [02:40, 12.48it/s, bound:522 nc: 17 ncall:3.9e+04 eff:3.5% logz=593504.27+/-0.74 dlogz:1166.559>10]

1359it [02:40, 12.27it/s, bound:523 nc: 26 ncall:3.9e+04 eff:3.5% logz=593509.52+/-0.73 dlogz:1159.171>10]

1361it [02:40, 12.18it/s, bound:524 nc: 30 ncall:3.9e+04 eff:3.5% logz=593527.49+/-0.74 dlogz:1153.249>10]

1363it [02:40, 12.19it/s, bound:525 nc: 37 ncall:3.9e+04 eff:3.5% logz=593531.12+/-0.72 dlogz:1136.552>10]

1365it [02:41, 13.15it/s, bound:526 nc: 22 ncall:3.9e+04 eff:3.5% logz=593537.78+/-0.73 dlogz:1131.829>10]

1367it [02:41, 13.99it/s, bound:527 nc: 15 ncall:3.9e+04 eff:3.5% logz=593557.66+/-0.74 dlogz:1124.429>10]

1369it [02:41, 13.16it/s, bound:527 nc: 26 ncall:3.9e+04 eff:3.5% logz=593570.99+/-0.74 dlogz:1100.130>10]

1371it [02:41, 12.15it/s, bound:528 nc: 23 ncall:3.9e+04 eff:3.5% logz=593586.27+/-0.74 dlogz:1094.086>10]

1373it [02:41, 10.09it/s, bound:530 nc: 38 ncall:3.9e+04 eff:3.5% logz=593606.35+/-0.74 dlogz:1075.784>10]

1375it [02:42,  8.68it/s, bound:532 nc: 78 ncall:3.9e+04 eff:3.5% logz=593610.80+/-0.72 dlogz:1057.131>10]

1377it [02:42,  9.40it/s, bound:533 nc: 29 ncall:3.9e+04 eff:3.5% logz=593615.09+/-0.73 dlogz:1053.100>10]

1379it [02:42,  9.94it/s, bound:534 nc: 29 ncall:3.9e+04 eff:3.5% logz=593656.30+/-0.74 dlogz:1029.129>10]

1381it [02:42,  9.09it/s, bound:535 nc: 32 ncall:4.0e+04 eff:3.5% logz=593686.49+/-0.74 dlogz:990.770>10]

1383it [02:42,  9.68it/s, bound:536 nc: 31 ncall:4.0e+04 eff:3.5% logz=593690.42+/-0.72 dlogz:976.941>10]

1385it [02:43, 11.43it/s, bound:537 nc: 14 ncall:4.0e+04 eff:3.5% logz=593704.36+/-0.74 dlogz:966.670>10]

1387it [02:43,  9.86it/s, bound:537 nc: 60 ncall:4.0e+04 eff:3.5% logz=593720.22+/-0.74 dlogz:959.640>10]

1389it [02:43, 11.12it/s, bound:538 nc: 17 ncall:4.0e+04 eff:3.5% logz=593727.76+/-0.73 dlogz:939.745>10]

1391it [02:43, 12.00it/s, bound:539 nc: 27 ncall:4.0e+04 eff:3.5% logz=593732.62+/-0.74 dlogz:937.388>10]

1393it [02:43, 13.48it/s, bound:540 nc:  9 ncall:4.0e+04 eff:3.5% logz=593743.06+/-0.75 dlogz:931.267>10]

1395it [02:43, 13.57it/s, bound:540 nc: 25 ncall:4.0e+04 eff:3.5% logz=593753.29+/-0.74 dlogz:916.226>10]

1397it [02:43, 12.80it/s, bound:541 nc: 26 ncall:4.0e+04 eff:3.5% logz=593762.22+/-0.75 dlogz:910.596>10]

1399it [02:44, 13.14it/s, bound:542 nc: 28 ncall:4.0e+04 eff:3.5% logz=593784.80+/-0.75 dlogz:893.894>10]

1401it [02:44, 12.28it/s, bound:543 nc: 24 ncall:4.0e+04 eff:3.5% logz=593796.83+/-0.74 dlogz:872.655>10]

1403it [02:44, 11.74it/s, bound:544 nc: 25 ncall:4.0e+04 eff:3.5% logz=593809.81+/-0.75 dlogz:861.116>10]

1405it [02:44, 11.76it/s, bound:545 nc: 24 ncall:4.0e+04 eff:3.5% logz=593841.49+/-0.75 dlogz:843.900>10]

1407it [02:44, 13.06it/s, bound:545 nc: 16 ncall:4.0e+04 eff:3.5% logz=593846.52+/-0.74 dlogz:821.541>10]

1409it [02:44, 11.85it/s, bound:546 nc: 23 ncall:4.0e+04 eff:3.5% logz=593859.76+/-0.75 dlogz:812.031>10]

1411it [02:45, 13.09it/s, bound:547 nc: 18 ncall:4.0e+04 eff:3.5% logz=593881.07+/-0.75 dlogz:796.397>10]

1413it [02:45, 12.04it/s, bound:548 nc: 18 ncall:4.0e+04 eff:3.5% logz=593887.78+/-0.75 dlogz:782.251>10]

1415it [02:45, 12.15it/s, bound:548 nc: 27 ncall:4.0e+04 eff:3.5% logz=593891.45+/-0.74 dlogz:776.896>10]

1417it [02:45, 12.30it/s, bound:549 nc: 29 ncall:4.0e+04 eff:3.5% logz=593897.86+/-0.74 dlogz:770.173>10]

1419it [02:45, 11.83it/s, bound:550 nc: 17 ncall:4.1e+04 eff:3.5% logz=593901.25+/-0.73 dlogz:765.898>10]

1421it [02:46,  9.88it/s, bound:552 nc: 31 ncall:4.1e+04 eff:3.5% logz=593910.63+/-0.75 dlogz:761.993>10]

1423it [02:46,  8.62it/s, bound:554 nc: 71 ncall:4.1e+04 eff:3.5% logz=593924.88+/-0.75 dlogz:750.293>10]

1425it [02:46,  8.54it/s, bound:554 nc: 59 ncall:4.1e+04 eff:3.5% logz=593927.01+/-0.73 dlogz:739.395>10]

1427it [02:46,  9.59it/s, bound:555 nc: 31 ncall:4.1e+04 eff:3.5% logz=593934.29+/-0.75 dlogz:736.287>10]

1429it [02:46, 10.19it/s, bound:556 nc: 23 ncall:4.1e+04 eff:3.5% logz=593939.67+/-0.74 dlogz:727.704>10]

1431it [02:47, 10.77it/s, bound:557 nc: 24 ncall:4.1e+04 eff:3.5% logz=593944.96+/-0.74 dlogz:815.209>10]

1433it [02:47, 12.00it/s, bound:557 nc: 24 ncall:4.1e+04 eff:3.5% logz=593955.31+/-0.73 dlogz:804.284>10]

1435it [02:47, 10.46it/s, bound:558 nc: 58 ncall:4.1e+04 eff:3.5% logz=593970.97+/-0.75 dlogz:907.448>10]

1437it [02:47, 11.40it/s, bound:559 nc: 21 ncall:4.1e+04 eff:3.5% logz=593973.73+/-0.73 dlogz:892.660>10]

1439it [02:47,  9.93it/s, bound:560 nc: 55 ncall:4.1e+04 eff:3.5% logz=593991.21+/-0.76 dlogz:888.480>10]

1441it [02:48,  8.33it/s, bound:562 nc: 85 ncall:4.1e+04 eff:3.5% logz=593996.57+/-0.74 dlogz:870.322>10]

1442it [02:48,  7.76it/s, bound:562 nc: 55 ncall:4.1e+04 eff:3.5% logz=594001.50+/-0.75 dlogz:868.526>10]

1444it [02:48,  9.01it/s, bound:563 nc: 28 ncall:4.1e+04 eff:3.5% logz=594013.94+/-0.76 dlogz:859.081>10]

1446it [02:48, 10.15it/s, bound:564 nc: 27 ncall:4.1e+04 eff:3.5% logz=594017.79+/-0.74 dlogz:848.982>10]

1448it [02:48, 10.14it/s, bound:565 nc: 30 ncall:4.2e+04 eff:3.5% logz=594020.90+/-0.74 dlogz:845.431>10]

1450it [02:49, 11.01it/s, bound:566 nc: 25 ncall:4.2e+04 eff:3.5% logz=594022.61+/-0.73 dlogz:843.052>10]

1452it [02:49,  9.93it/s, bound:567 nc: 28 ncall:4.2e+04 eff:3.5% logz=594037.80+/-0.74 dlogz:828.911>10]

1454it [02:49, 10.78it/s, bound:568 nc: 17 ncall:4.2e+04 eff:3.5% logz=594051.99+/-0.74 dlogz:814.211>10]

1456it [02:49, 11.34it/s, bound:568 nc: 27 ncall:4.2e+04 eff:3.5% logz=594066.64+/-0.76 dlogz:807.206>10]

1458it [02:49, 10.75it/s, bound:569 nc: 35 ncall:4.2e+04 eff:3.5% logz=594071.47+/-0.76 dlogz:797.036>10]

1460it [02:50, 10.15it/s, bound:571 nc: 23 ncall:4.2e+04 eff:3.5% logz=594078.48+/-0.75 dlogz:789.378>10]

1462it [02:50, 11.40it/s, bound:572 nc: 15 ncall:4.2e+04 eff:3.5% logz=594082.23+/-0.74 dlogz:783.977>10]

1464it [02:50, 12.20it/s, bound:572 nc: 17 ncall:4.2e+04 eff:3.5% logz=594084.35+/-0.73 dlogz:781.445>10]

1466it [02:50, 12.88it/s, bound:573 nc: 17 ncall:4.2e+04 eff:3.5% logz=594087.33+/-0.75 dlogz:779.543>10]

1468it [02:50, 12.64it/s, bound:574 nc: 24 ncall:4.2e+04 eff:3.5% logz=594091.92+/-0.76 dlogz:776.186>10]

1470it [02:50, 13.57it/s, bound:574 nc: 19 ncall:4.2e+04 eff:3.5% logz=594094.82+/-0.74 dlogz:771.092>10]

1472it [02:50, 13.73it/s, bound:575 nc: 25 ncall:4.2e+04 eff:3.5% logz=594101.59+/-0.76 dlogz:766.634>10]

1474it [02:51, 12.96it/s, bound:576 nc: 30 ncall:4.2e+04 eff:3.5% logz=594108.62+/-0.76 dlogz:761.504>10]

1476it [02:51, 13.19it/s, bound:577 nc: 27 ncall:4.2e+04 eff:3.5% logz=594115.13+/-0.76 dlogz:754.551>10]

1478it [02:51, 12.93it/s, bound:578 nc: 28 ncall:4.2e+04 eff:3.5% logz=594131.71+/-0.76 dlogz:739.513>10]

1480it [02:51, 13.49it/s, bound:578 nc: 31 ncall:4.2e+04 eff:3.5% logz=594135.78+/-0.76 dlogz:731.511>10]

1482it [02:51, 12.50it/s, bound:579 nc: 34 ncall:4.2e+04 eff:3.5% logz=594152.98+/-0.76 dlogz:718.348>10]

1484it [02:51, 10.54it/s, bound:580 nc: 37 ncall:4.3e+04 eff:3.5% logz=594157.80+/-0.76 dlogz:709.833>10]

1486it [02:52, 11.14it/s, bound:581 nc: 20 ncall:4.3e+04 eff:3.5% logz=594174.47+/-0.75 dlogz:692.231>10]

1488it [02:52, 11.03it/s, bound:582 nc: 33 ncall:4.3e+04 eff:3.5% logz=594184.35+/-0.76 dlogz:684.995>10]

1490it [02:52, 10.91it/s, bound:583 nc: 33 ncall:4.3e+04 eff:3.5% logz=594197.40+/-0.77 dlogz:677.748>10]

1492it [02:52, 11.27it/s, bound:584 nc: 31 ncall:4.3e+04 eff:3.5% logz=594201.99+/-0.75 dlogz:663.594>10]

1494it [02:52, 11.66it/s, bound:585 nc: 21 ncall:4.3e+04 eff:3.5% logz=594207.31+/-0.76 dlogz:661.568>10]

1496it [02:52, 11.29it/s, bound:586 nc: 29 ncall:4.3e+04 eff:3.5% logz=594213.58+/-0.75 dlogz:652.437>10]

1498it [02:53, 11.03it/s, bound:587 nc: 28 ncall:4.3e+04 eff:3.5% logz=594215.17+/-0.74 dlogz:649.834>10]

1500it [02:53,  9.09it/s, bound:588 nc: 67 ncall:4.3e+04 eff:3.5% logz=594220.21+/-0.77 dlogz:648.325>10]

1501it [02:53,  8.36it/s, bound:589 nc: 49 ncall:4.3e+04 eff:3.5% logz=594224.03+/-0.75 dlogz:644.154>10]

1503it [02:53,  9.51it/s, bound:590 nc: 25 ncall:4.3e+04 eff:3.5% logz=594228.22+/-0.76 dlogz:639.220>10]

1505it [02:53, 10.35it/s, bound:591 nc: 22 ncall:4.3e+04 eff:3.5% logz=594239.99+/-0.77 dlogz:634.947>10]

1507it [02:54, 10.45it/s, bound:592 nc: 29 ncall:4.3e+04 eff:3.5% logz=594242.03+/-0.74 dlogz:622.988>10]

1509it [02:54, 10.78it/s, bound:593 nc: 30 ncall:4.3e+04 eff:3.5% logz=594250.81+/-0.77 dlogz:621.518>10]

1511it [02:54, 11.75it/s, bound:594 nc: 19 ncall:4.3e+04 eff:3.5% logz=594254.72+/-0.76 dlogz:612.135>10]

1513it [02:54, 12.68it/s, bound:595 nc: 31 ncall:4.3e+04 eff:3.5% logz=594264.92+/-0.77 dlogz:605.599>10]

1515it [02:54, 13.34it/s, bound:596 nc: 20 ncall:4.3e+04 eff:3.5% logz=594271.03+/-0.77 dlogz:597.254>10]

1517it [02:54, 11.23it/s, bound:597 nc: 53 ncall:4.4e+04 eff:3.5% logz=594274.21+/-0.76 dlogz:591.844>10]

1519it [02:55, 11.37it/s, bound:598 nc: 22 ncall:4.4e+04 eff:3.5% logz=594277.46+/-0.76 dlogz:588.972>10]

1521it [02:55, 11.73it/s, bound:599 nc: 24 ncall:4.4e+04 eff:3.5% logz=594279.77+/-0.75 dlogz:585.648>10]

1523it [02:55,  8.76it/s, bound:601 nc: 28 ncall:4.4e+04 eff:3.5% logz=594300.39+/-0.77 dlogz:578.737>10]

1525it [02:55,  9.46it/s, bound:602 nc: 27 ncall:4.4e+04 eff:3.5% logz=594306.91+/-0.76 dlogz:558.549>10]

1527it [02:56,  8.87it/s, bound:604 nc: 34 ncall:4.4e+04 eff:3.5% logz=594313.38+/-0.76 dlogz:552.847>10]

1529it [02:56,  9.55it/s, bound:605 nc: 34 ncall:4.4e+04 eff:3.5% logz=594320.41+/-0.77 dlogz:546.624>10]

1531it [02:56,  9.67it/s, bound:606 nc: 35 ncall:4.4e+04 eff:3.5% logz=594323.61+/-0.76 dlogz:542.278>10]

1533it [02:56,  9.64it/s, bound:607 nc: 32 ncall:4.4e+04 eff:3.5% logz=594339.13+/-0.76 dlogz:534.321>10]

1535it [02:56, 10.52it/s, bound:608 nc: 20 ncall:4.4e+04 eff:3.5% logz=594349.76+/-0.76 dlogz:515.697>10]

1537it [02:56,  9.97it/s, bound:608 nc: 49 ncall:4.4e+04 eff:3.5% logz=594351.11+/-0.74 dlogz:513.375>10]

1539it [02:57, 10.33it/s, bound:609 nc: 29 ncall:4.4e+04 eff:3.5% logz=594364.60+/-0.78 dlogz:510.851>10]

1541it [02:57, 10.91it/s, bound:610 nc: 28 ncall:4.4e+04 eff:3.5% logz=594370.06+/-0.77 dlogz:496.188>10]

1543it [02:57, 10.50it/s, bound:611 nc: 32 ncall:4.4e+04 eff:3.5% logz=594380.23+/-0.77 dlogz:486.149>10]

1545it [02:57, 10.86it/s, bound:612 nc: 27 ncall:4.4e+04 eff:3.5% logz=594394.76+/-0.78 dlogz:482.128>10]

1547it [02:57, 10.64it/s, bound:613 nc: 30 ncall:4.4e+04 eff:3.5% logz=594397.34+/-0.76 dlogz:467.916>10]

1549it [02:58, 10.63it/s, bound:614 nc: 31 ncall:4.5e+04 eff:3.5% logz=594399.51+/-0.75 dlogz:465.414>10]

1551it [02:58, 10.92it/s, bound:615 nc: 31 ncall:4.5e+04 eff:3.5% logz=594403.48+/-0.77 dlogz:463.342>10]

1553it [02:58, 10.89it/s, bound:616 nc: 27 ncall:4.5e+04 eff:3.5% logz=594409.29+/-0.77 dlogz:457.304>10]

1555it [02:58, 10.40it/s, bound:617 nc: 34 ncall:4.5e+04 eff:3.5% logz=594425.90+/-0.78 dlogz:448.507>10]

1557it [02:58, 10.92it/s, bound:618 nc: 26 ncall:4.5e+04 eff:3.5% logz=594430.19+/-0.77 dlogz:435.904>10]

1559it [02:59,  9.21it/s, bound:620 nc: 33 ncall:4.5e+04 eff:3.5% logz=594432.43+/-0.76 dlogz:432.197>10]

1561it [02:59, 10.31it/s, bound:620 nc: 32 ncall:4.5e+04 eff:3.5% logz=594434.85+/-0.76 dlogz:429.930>10]

1563it [02:59, 11.25it/s, bound:621 nc: 27 ncall:4.5e+04 eff:3.5% logz=594439.41+/-0.76 dlogz:425.884>10]

1565it [02:59, 11.42it/s, bound:622 nc: 23 ncall:4.5e+04 eff:3.5% logz=594449.76+/-0.78 dlogz:418.808>10]

1567it [02:59, 11.01it/s, bound:623 nc: 31 ncall:4.5e+04 eff:3.5% logz=594456.67+/-0.77 dlogz:411.041>10]

1569it [02:59, 11.26it/s, bound:624 nc: 35 ncall:4.5e+04 eff:3.5% logz=594467.58+/-0.76 dlogz:397.029>10]

1571it [03:00, 10.74it/s, bound:625 nc: 35 ncall:4.5e+04 eff:3.5% logz=594468.77+/-0.75 dlogz:395.273>10]

1573it [03:00, 10.93it/s, bound:626 nc: 24 ncall:4.5e+04 eff:3.5% logz=594478.54+/-0.76 dlogz:386.079>10]

1575it [03:00, 10.48it/s, bound:627 nc: 35 ncall:4.5e+04 eff:3.5% logz=594480.42+/-0.76 dlogz:384.191>10]

1577it [03:00, 10.27it/s, bound:628 nc: 35 ncall:4.5e+04 eff:3.5% logz=594485.37+/-0.77 dlogz:379.432>10]

1579it [03:00, 10.31it/s, bound:629 nc: 31 ncall:4.5e+04 eff:3.5% logz=594487.15+/-0.76 dlogz:377.131>10]

1581it [03:01, 10.47it/s, bound:630 nc: 30 ncall:4.6e+04 eff:3.5% logz=594491.27+/-0.78 dlogz:374.867>10]

1583it [03:01, 10.33it/s, bound:631 nc: 32 ncall:4.6e+04 eff:3.5% logz=594493.60+/-0.76 dlogz:370.638>10]

1585it [03:01,  9.67it/s, bound:632 nc: 30 ncall:4.6e+04 eff:3.5% logz=594495.00+/-0.75 dlogz:369.007>10]

1586it [03:01,  8.42it/s, bound:632 nc: 62 ncall:4.6e+04 eff:3.5% logz=594496.32+/-0.76 dlogz:368.311>10]

1588it [03:01,  8.81it/s, bound:633 nc: 35 ncall:4.6e+04 eff:3.5% logz=594499.06+/-0.76 dlogz:365.274>10]

1590it [03:02,  9.73it/s, bound:634 nc: 25 ncall:4.6e+04 eff:3.5% logz=594503.13+/-0.78 dlogz:363.413>10]

1592it [03:02, 10.56it/s, bound:635 nc: 30 ncall:4.6e+04 eff:3.5% logz=594506.70+/-0.78 dlogz:358.891>10]

1594it [03:02, 10.26it/s, bound:636 nc: 35 ncall:4.6e+04 eff:3.5% logz=594508.45+/-0.76 dlogz:355.387>10]

1596it [03:02,  8.95it/s, bound:637 nc: 60 ncall:4.6e+04 eff:3.5% logz=594510.45+/-0.77 dlogz:354.120>10]

1598it [03:02,  9.56it/s, bound:638 nc: 35 ncall:4.6e+04 eff:3.5% logz=594514.09+/-0.76 dlogz:349.857>10]

1600it [03:03,  9.89it/s, bound:639 nc: 35 ncall:4.6e+04 eff:3.5% logz=594525.67+/-0.79 dlogz:344.020>10]

1602it [03:03,  9.34it/s, bound:640 nc: 50 ncall:4.6e+04 eff:3.5% logz=594528.78+/-0.77 dlogz:335.631>10]

1604it [03:03, 10.19it/s, bound:641 nc: 26 ncall:4.6e+04 eff:3.5% logz=594530.96+/-0.76 dlogz:333.055>10]

1606it [03:03,  8.99it/s, bound:643 nc: 32 ncall:4.6e+04 eff:3.5% logz=594533.12+/-0.77 dlogz:331.435>10]

1608it [03:03,  9.66it/s, bound:644 nc: 24 ncall:4.6e+04 eff:3.5% logz=594535.07+/-0.76 dlogz:328.681>10]

1610it [03:04, 10.22it/s, bound:645 nc: 28 ncall:4.7e+04 eff:3.5% logz=594537.92+/-0.78 dlogz:327.486>10]

1612it [03:04,  9.04it/s, bound:646 nc: 29 ncall:4.7e+04 eff:3.5% logz=594540.43+/-0.77 dlogz:323.406>10]

1613it [03:04,  9.14it/s, bound:646 nc: 35 ncall:4.7e+04 eff:3.5% logz=594541.79+/-0.77 dlogz:322.543>10]

1615it [03:04,  9.49it/s, bound:647 nc: 34 ncall:4.7e+04 eff:3.5% logz=594543.71+/-0.76 dlogz:319.994>10]

1617it [03:04, 10.65it/s, bound:648 nc: 16 ncall:4.7e+04 eff:3.5% logz=594545.63+/-0.77 dlogz:318.520>10]

1619it [03:05, 10.25it/s, bound:649 nc: 34 ncall:4.7e+04 eff:3.5% logz=594547.81+/-0.77 dlogz:316.019>10]

1621it [03:05, 10.56it/s, bound:650 nc: 29 ncall:4.7e+04 eff:3.5% logz=594549.59+/-0.77 dlogz:314.384>10]

1623it [03:05,  7.17it/s, bound:650 nc: 28 ncall:4.7e+04 eff:3.5% logz=594552.84+/-0.77 dlogz:311.176>10]

1624it [03:06,  5.61it/s, bound:651 nc: 30 ncall:4.7e+04 eff:3.5% logz=594555.21+/-0.78 dlogz:309.994>10]

1625it [03:06,  4.64it/s, bound:651 nc: 29 ncall:4.7e+04 eff:3.5% logz=594556.55+/-0.77 dlogz:307.615>10]

1626it [03:06,  4.31it/s, bound:652 nc: 24 ncall:4.7e+04 eff:3.5% logz=594557.69+/-0.77 dlogz:306.261>10]

1627it [03:07,  3.75it/s, bound:652 nc: 34 ncall:4.7e+04 eff:3.5% logz=594558.51+/-0.77 dlogz:305.113>10]

1628it [03:07,  3.53it/s, bound:653 nc: 32 ncall:4.7e+04 eff:3.5% logz=594560.94+/-0.78 dlogz:304.275>10]

1629it [03:07,  3.29it/s, bound:653 nc: 32 ncall:4.7e+04 eff:3.5% logz=594564.18+/-0.78 dlogz:301.832>10]

1630it [03:08,  3.34it/s, bound:654 nc: 28 ncall:4.7e+04 eff:3.5% logz=594565.17+/-0.77 dlogz:298.581>10]

1631it [03:08,  3.36it/s, bound:654 nc: 25 ncall:4.7e+04 eff:3.5% logz=594569.33+/-0.79 dlogz:297.579>10]

1632it [03:08,  3.15it/s, bound:655 nc: 33 ncall:4.7e+04 eff:3.5% logz=594571.17+/-0.78 dlogz:293.407>10]

1633it [03:08,  3.33it/s, bound:655 nc: 28 ncall:4.7e+04 eff:3.5% logz=594574.27+/-0.79 dlogz:291.560>10]

1634it [03:09,  3.52it/s, bound:656 nc: 18 ncall:4.7e+04 eff:3.5% logz=594577.67+/-0.79 dlogz:288.439>10]

1635it [03:09,  3.39it/s, bound:656 nc: 35 ncall:4.7e+04 eff:3.5% logz=594578.83+/-0.78 dlogz:285.029>10]

1636it [03:09,  3.92it/s, bound:657 nc: 17 ncall:4.7e+04 eff:3.5% logz=594579.51+/-0.77 dlogz:283.857>10]

1637it [03:10,  3.72it/s, bound:657 nc: 27 ncall:4.7e+04 eff:3.5% logz=594579.97+/-0.76 dlogz:283.168>10]

1638it [03:10,  3.29it/s, bound:657 nc: 34 ncall:4.7e+04 eff:3.5% logz=594580.31+/-0.76 dlogz:282.696>10]

1639it [03:10,  3.55it/s, bound:658 nc: 21 ncall:4.7e+04 eff:3.5% logz=594580.59+/-0.76 dlogz:282.345>10]

1640it [03:11,  2.60it/s, bound:658 nc: 61 ncall:4.7e+04 eff:3.5% logz=594580.93+/-0.76 dlogz:282.045>10]

1641it [03:11,  3.10it/s, bound:659 nc: 15 ncall:4.7e+04 eff:3.5% logz=594581.95+/-0.77 dlogz:281.693>10]

1642it [03:11,  2.97it/s, bound:659 nc: 34 ncall:4.7e+04 eff:3.5% logz=594583.82+/-0.78 dlogz:280.659>10]

1643it [03:12,  3.17it/s, bound:660 nc: 25 ncall:4.8e+04 eff:3.5% logz=594585.19+/-0.78 dlogz:280.349>10]

1644it [03:12,  3.08it/s, bound:660 nc: 34 ncall:4.8e+04 eff:3.5% logz=594587.01+/-0.78 dlogz:278.972>10]

1645it [03:12,  3.13it/s, bound:661 nc: 27 ncall:4.8e+04 eff:3.5% logz=594588.08+/-0.77 dlogz:277.131>10]

1646it [03:13,  3.27it/s, bound:661 nc: 26 ncall:4.8e+04 eff:3.5% logz=594588.79+/-0.77 dlogz:276.051>10]

1647it [03:13,  3.19it/s, bound:662 nc: 32 ncall:4.8e+04 eff:3.5% logz=594590.03+/-0.77 dlogz:275.326>10]

1648it [03:13,  3.14it/s, bound:662 nc: 31 ncall:4.8e+04 eff:3.5% logz=594591.99+/-0.78 dlogz:274.080>10]

1649it [03:14,  3.01it/s, bound:663 nc: 30 ncall:4.8e+04 eff:3.5% logz=594594.45+/-0.79 dlogz:272.105>10]

1650it [03:14,  3.10it/s, bound:663 nc: 28 ncall:4.8e+04 eff:3.5% logz=594595.46+/-0.78 dlogz:269.630>10]

1651it [03:14,  3.06it/s, bound:664 nc: 31 ncall:4.8e+04 eff:3.5% logz=594595.99+/-0.77 dlogz:268.615>10]

1652it [03:15,  1.99it/s, bound:664 nc: 75 ncall:4.8e+04 eff:3.5% logz=594596.51+/-0.77 dlogz:268.071>10]

1653it [03:15,  2.13it/s, bound:665 nc: 35 ncall:4.8e+04 eff:3.5% logz=594597.36+/-0.77 dlogz:267.533>10]

1654it [03:16,  2.41it/s, bound:665 nc: 26 ncall:4.8e+04 eff:3.5% logz=594598.23+/-0.77 dlogz:295.311>10]

1655it [03:16,  2.62it/s, bound:666 nc: 28 ncall:4.8e+04 eff:3.5% logz=594599.01+/-0.77 dlogz:294.427>10]

1656it [03:16,  2.80it/s, bound:666 nc: 32 ncall:4.8e+04 eff:3.5% logz=594599.74+/-0.77 dlogz:293.631>10]

1657it [03:17,  2.76it/s, bound:667 nc: 32 ncall:4.8e+04 eff:3.5% logz=594600.36+/-0.77 dlogz:292.895>10]

1658it [03:17,  2.74it/s, bound:667 nc: 34 ncall:4.8e+04 eff:3.5% logz=594604.34+/-0.80 dlogz:292.263>10]

1659it [03:17,  2.72it/s, bound:668 nc: 34 ncall:4.8e+04 eff:3.5% logz=594606.65+/-0.79 dlogz:288.270>10]

1660it [03:18,  2.70it/s, bound:668 nc: 31 ncall:4.8e+04 eff:3.5% logz=594607.79+/-0.78 dlogz:285.945>10]

1661it [03:18,  2.26it/s, bound:669 nc: 53 ncall:4.8e+04 eff:3.5% logz=594610.58+/-0.79 dlogz:284.798>10]

1662it [03:19,  2.50it/s, bound:670 nc: 26 ncall:4.8e+04 eff:3.5% logz=594612.56+/-0.78 dlogz:281.989>10]

1663it [03:19,  2.65it/s, bound:670 nc: 28 ncall:4.8e+04 eff:3.5% logz=594613.65+/-0.78 dlogz:279.999>10]

1664it [03:19,  2.68it/s, bound:671 nc: 33 ncall:4.8e+04 eff:3.5% logz=594615.84+/-0.79 dlogz:278.893>10]

1665it [03:20,  2.70it/s, bound:671 nc: 33 ncall:4.8e+04 eff:3.5% logz=594617.11+/-0.78 dlogz:276.697>10]

1666it [03:20,  2.49it/s, bound:672 nc: 43 ncall:4.8e+04 eff:3.4% logz=594618.26+/-0.78 dlogz:275.406>10]

1667it [03:21,  2.41it/s, bound:672 nc: 42 ncall:4.8e+04 eff:3.4% logz=594619.07+/-0.77 dlogz:274.253>10]

1668it [03:21,  2.69it/s, bound:673 nc: 25 ncall:4.8e+04 eff:3.4% logz=594620.68+/-0.78 dlogz:273.431>10]

1669it [03:21,  3.00it/s, bound:673 nc: 22 ncall:4.8e+04 eff:3.4% logz=594622.12+/-0.78 dlogz:271.802>10]

1670it [03:22,  2.35it/s, bound:673 nc: 57 ncall:4.8e+04 eff:3.4% logz=594623.24+/-0.78 dlogz:270.353>10]

1671it [03:22,  2.43it/s, bound:674 nc: 33 ncall:4.8e+04 eff:3.4% logz=594623.93+/-0.77 dlogz:269.216>10]

1672it [03:23,  2.51it/s, bound:674 nc: 33 ncall:4.9e+04 eff:3.4% logz=594625.56+/-0.79 dlogz:268.513>10]

1673it [03:23,  2.59it/s, bound:675 nc: 33 ncall:4.9e+04 eff:3.4% logz=594627.23+/-0.79 dlogz:266.872>10]

1674it [03:23,  2.61it/s, bound:675 nc: 34 ncall:4.9e+04 eff:3.4% logz=594628.09+/-0.78 dlogz:265.190>10]

1675it [03:24,  2.56it/s, bound:676 nc: 35 ncall:4.9e+04 eff:3.4% logz=594628.65+/-0.77 dlogz:264.320>10]

1676it [03:24,  2.65it/s, bound:676 nc: 32 ncall:4.9e+04 eff:3.4% logz=594629.68+/-0.78 dlogz:263.743>10]

1677it [03:24,  2.77it/s, bound:677 nc: 28 ncall:4.9e+04 eff:3.4% logz=594632.14+/-0.79 dlogz:262.700>10]

1678it [03:25,  3.06it/s, bound:677 nc: 24 ncall:4.9e+04 eff:3.4% logz=594633.23+/-0.78 dlogz:260.236>10]

1679it [03:25,  3.33it/s, bound:678 nc: 23 ncall:4.9e+04 eff:3.4% logz=594635.57+/-0.79 dlogz:259.126>10]

1680it [03:25,  3.02it/s, bound:678 nc: 33 ncall:4.9e+04 eff:3.4% logz=594636.74+/-0.78 dlogz:256.772>10]

1681it [03:26,  3.01it/s, bound:679 nc: 32 ncall:4.9e+04 eff:3.4% logz=594638.78+/-0.79 dlogz:255.598>10]

1682it [03:26,  3.29it/s, bound:679 nc: 20 ncall:4.9e+04 eff:3.4% logz=594640.75+/-0.79 dlogz:253.547>10]

1683it [03:26,  3.28it/s, bound:680 nc: 26 ncall:4.9e+04 eff:3.4% logz=594645.79+/-0.80 dlogz:251.557>10]

1684it [03:27,  3.07it/s, bound:680 nc: 35 ncall:4.9e+04 eff:3.4% logz=594647.55+/-0.79 dlogz:246.504>10]

1685it [03:27,  3.03it/s, bound:681 nc: 30 ncall:4.9e+04 eff:3.4% logz=594648.67+/-0.78 dlogz:244.730>10]

1686it [03:27,  3.03it/s, bound:681 nc: 31 ncall:4.9e+04 eff:3.4% logz=594651.10+/-0.80 dlogz:243.602>10]

1687it [03:28,  3.19it/s, bound:682 nc: 24 ncall:4.9e+04 eff:3.4% logz=594653.24+/-0.79 dlogz:241.157>10]

1688it [03:28,  3.00it/s, bound:682 nc: 33 ncall:4.9e+04 eff:3.4% logz=594654.68+/-0.79 dlogz:239.010>10]

1689it [03:28,  2.92it/s, bound:683 nc: 29 ncall:4.9e+04 eff:3.4% logz=594655.49+/-0.78 dlogz:237.555>10]

1690it [03:29,  3.07it/s, bound:683 nc: 25 ncall:4.9e+04 eff:3.4% logz=594656.44+/-0.78 dlogz:236.735>10]

1691it [03:29,  3.32it/s, bound:684 nc: 24 ncall:4.9e+04 eff:3.4% logz=594657.16+/-0.78 dlogz:235.773>10]

1692it [03:29,  3.04it/s, bound:684 nc: 35 ncall:4.9e+04 eff:3.4% logz=594657.96+/-0.78 dlogz:235.035>10]

1693it [03:30,  2.99it/s, bound:685 nc: 32 ncall:4.9e+04 eff:3.4% logz=594658.61+/-0.77 dlogz:234.226>10]

1694it [03:30,  3.19it/s, bound:685 nc: 26 ncall:4.9e+04 eff:3.4% logz=594659.46+/-0.78 dlogz:233.559>10]

1695it [03:30,  3.21it/s, bound:686 nc: 28 ncall:4.9e+04 eff:3.4% logz=594660.21+/-0.78 dlogz:232.702>10]

1696it [03:31,  2.33it/s, bound:686 nc: 68 ncall:4.9e+04 eff:3.4% logz=594660.80+/-0.77 dlogz:231.942>10]

1697it [03:31,  2.43it/s, bound:687 nc: 35 ncall:4.9e+04 eff:3.4% logz=594661.30+/-0.77 dlogz:231.335>10]

1698it [03:31,  2.82it/s, bound:687 nc: 22 ncall:4.9e+04 eff:3.4% logz=594662.64+/-0.79 dlogz:230.823>10]

1699it [03:32,  2.97it/s, bound:688 nc: 25 ncall:4.9e+04 eff:3.4% logz=594663.57+/-0.78 dlogz:229.475>10]

1700it [03:32,  2.86it/s, bound:688 nc: 34 ncall:4.9e+04 eff:3.4% logz=594664.59+/-0.78 dlogz:228.528>10]

1701it [03:32,  2.75it/s, bound:689 nc: 33 ncall:4.9e+04 eff:3.4% logz=594667.00+/-0.80 dlogz:227.500>10]

1702it [03:33,  2.80it/s, bound:689 nc: 31 ncall:4.9e+04 eff:3.4% logz=594668.14+/-0.79 dlogz:225.074>10]

1703it [03:33,  2.91it/s, bound:690 nc: 27 ncall:4.9e+04 eff:3.4% logz=594668.78+/-0.78 dlogz:223.924>10]

1704it [03:34,  2.65it/s, bound:690 nc: 35 ncall:4.9e+04 eff:3.4% logz=594669.66+/-0.78 dlogz:223.265>10]

1705it [03:34,  3.21it/s, bound:691 nc: 14 ncall:5.0e+04 eff:3.4% logz=594670.49+/-0.78 dlogz:222.380>10]

1706it [03:35,  2.27it/s, bound:691 nc: 67 ncall:5.0e+04 eff:3.4% logz=594671.09+/-0.78 dlogz:221.530>10]

1707it [03:35,  2.37it/s, bound:692 nc: 33 ncall:5.0e+04 eff:3.4% logz=594671.63+/-0.77 dlogz:220.924>10]

1708it [03:35,  2.64it/s, bound:692 nc: 25 ncall:5.0e+04 eff:3.4% logz=594672.16+/-0.77 dlogz:220.366>10]

1709it [03:36,  2.72it/s, bound:693 nc: 28 ncall:5.0e+04 eff:3.4% logz=594672.62+/-0.77 dlogz:219.826>10]

1710it [03:36,  2.76it/s, bound:693 nc: 31 ncall:5.0e+04 eff:3.4% logz=594673.35+/-0.78 dlogz:219.356>10]

1711it [03:36,  2.75it/s, bound:694 nc: 30 ncall:5.0e+04 eff:3.4% logz=594675.45+/-0.80 dlogz:218.614>10]

1712it [03:37,  1.98it/s, bound:695 nc: 73 ncall:5.0e+04 eff:3.4% logz=594676.43+/-0.79 dlogz:216.501>10]

1713it [03:37,  2.34it/s, bound:695 nc: 21 ncall:5.0e+04 eff:3.4% logz=594677.14+/-0.78 dlogz:215.505>10]

1714it [03:38,  2.57it/s, bound:695 nc: 25 ncall:5.0e+04 eff:3.4% logz=594677.68+/-0.78 dlogz:214.788>10]

1715it [03:38,  2.76it/s, bound:696 nc: 31 ncall:5.0e+04 eff:3.4% logz=594678.23+/-0.78 dlogz:214.236>10]

1716it [03:38,  3.00it/s, bound:696 nc: 25 ncall:5.0e+04 eff:3.4% logz=594678.96+/-0.78 dlogz:213.666>10]

1717it [03:39,  2.80it/s, bound:697 nc: 35 ncall:5.0e+04 eff:3.4% logz=594681.80+/-0.80 dlogz:212.931>10]

1718it [03:39,  2.81it/s, bound:697 nc: 32 ncall:5.0e+04 eff:3.4% logz=594683.50+/-0.80 dlogz:210.077>10]

1719it [03:39,  2.79it/s, bound:698 nc: 34 ncall:5.0e+04 eff:3.4% logz=594684.40+/-0.79 dlogz:208.363>10]

1720it [03:40,  2.79it/s, bound:698 nc: 32 ncall:5.0e+04 eff:3.4% logz=594690.43+/-0.81 dlogz:207.447>10]

1721it [03:40,  2.87it/s, bound:699 nc: 29 ncall:5.0e+04 eff:3.4% logz=594691.53+/-0.79 dlogz:201.404>10]

1722it [03:41,  2.32it/s, bound:699 nc: 54 ncall:5.0e+04 eff:3.4% logz=594692.35+/-0.79 dlogz:200.291>10]

1723it [03:41,  2.50it/s, bound:700 nc: 31 ncall:5.0e+04 eff:3.4% logz=594693.11+/-0.78 dlogz:199.460>10]

1724it [03:42,  2.08it/s, bound:700 nc: 65 ncall:5.0e+04 eff:3.4% logz=594693.81+/-0.78 dlogz:198.686>10]

1725it [03:42,  2.24it/s, bound:701 nc: 31 ncall:5.0e+04 eff:3.4% logz=594695.57+/-0.79 dlogz:197.978>10]

1726it [03:42,  2.30it/s, bound:701 nc: 35 ncall:5.0e+04 eff:3.4% logz=594696.19+/-0.78 dlogz:196.201>10]

1727it [03:43,  2.38it/s, bound:702 nc: 35 ncall:5.0e+04 eff:3.4% logz=594696.61+/-0.78 dlogz:195.568>10]

1728it [03:43,  2.46it/s, bound:702 nc: 32 ncall:5.0e+04 eff:3.4% logz=594696.99+/-0.78 dlogz:195.144>10]

1729it [03:43,  2.74it/s, bound:703 nc: 20 ncall:5.0e+04 eff:3.4% logz=594697.39+/-0.78 dlogz:194.746>10]

1730it [03:44,  2.77it/s, bound:703 nc: 30 ncall:5.0e+04 eff:3.4% logz=594697.96+/-0.78 dlogz:194.334>10]

1731it [03:44,  2.96it/s, bound:704 nc: 25 ncall:5.0e+04 eff:3.4% logz=594698.56+/-0.78 dlogz:193.749>10]

1732it [03:44,  2.87it/s, bound:704 nc: 34 ncall:5.0e+04 eff:3.4% logz=594699.09+/-0.78 dlogz:193.141>10]

1733it [03:45,  2.81it/s, bound:705 nc: 33 ncall:5.0e+04 eff:3.4% logz=594700.03+/-0.78 dlogz:192.597>10]

1734it [03:45,  2.90it/s, bound:705 nc: 30 ncall:5.1e+04 eff:3.4% logz=594702.35+/-0.80 dlogz:191.649>10]

1735it [03:45,  2.78it/s, bound:706 nc: 32 ncall:5.1e+04 eff:3.4% logz=594703.48+/-0.79 dlogz:189.319>10]

1736it [03:46,  2.79it/s, bound:706 nc: 31 ncall:5.1e+04 eff:3.4% logz=594707.70+/-0.81 dlogz:188.174>10]

1737it [03:46,  2.88it/s, bound:707 nc: 31 ncall:5.1e+04 eff:3.4% logz=594708.94+/-0.80 dlogz:183.939>10]

1738it [03:47,  2.15it/s, bound:707 nc: 69 ncall:5.1e+04 eff:3.4% logz=594709.76+/-0.79 dlogz:182.684>10]

1739it [03:47,  2.40it/s, bound:708 nc: 29 ncall:5.1e+04 eff:3.4% logz=594710.43+/-0.79 dlogz:181.853>10]

1740it [03:48,  2.42it/s, bound:708 nc: 35 ncall:5.1e+04 eff:3.4% logz=594711.07+/-0.78 dlogz:181.170>10]

1741it [03:48,  2.53it/s, bound:709 nc: 30 ncall:5.1e+04 eff:3.4% logz=594712.24+/-0.79 dlogz:180.522>10]

1742it [03:48,  2.85it/s, bound:709 nc: 21 ncall:5.1e+04 eff:3.4% logz=594713.22+/-0.79 dlogz:179.333>10]

1743it [03:49,  3.03it/s, bound:710 nc: 25 ncall:5.1e+04 eff:3.4% logz=594714.23+/-0.79 dlogz:178.349>10]

1744it [03:49,  2.80it/s, bound:710 nc: 34 ncall:5.1e+04 eff:3.4% logz=594715.12+/-0.79 dlogz:177.325>10]

1745it [03:49,  2.75it/s, bound:711 nc: 29 ncall:5.1e+04 eff:3.4% logz=594715.84+/-0.79 dlogz:176.423>10]

1746it [03:50,  2.41it/s, bound:711 nc: 47 ncall:5.1e+04 eff:3.4% logz=594716.37+/-0.78 dlogz:175.686>10]

1747it [03:50,  2.48it/s, bound:712 nc: 32 ncall:5.1e+04 eff:3.4% logz=594716.91+/-0.78 dlogz:175.141>10]

1748it [03:51,  2.53it/s, bound:712 nc: 34 ncall:5.1e+04 eff:3.4% logz=594718.36+/-0.80 dlogz:174.594>10]

1749it [03:51,  2.70it/s, bound:713 nc: 27 ncall:5.1e+04 eff:3.4% logz=594719.50+/-0.79 dlogz:173.129>10]

1750it [03:52,  1.90it/s, bound:713 nc: 76 ncall:5.1e+04 eff:3.4% logz=594720.54+/-0.79 dlogz:171.977>10]

1751it [03:52,  2.15it/s, bound:714 nc: 31 ncall:5.1e+04 eff:3.4% logz=594721.68+/-0.79 dlogz:170.926>10]

1752it [03:52,  2.31it/s, bound:714 nc: 35 ncall:5.1e+04 eff:3.4% logz=594722.57+/-0.79 dlogz:169.774>10]

1753it [03:53,  2.43it/s, bound:715 nc: 30 ncall:5.1e+04 eff:3.4% logz=594723.56+/-0.79 dlogz:168.872>10]

1754it [03:53,  2.49it/s, bound:715 nc: 35 ncall:5.1e+04 eff:3.4% logz=594724.60+/-0.79 dlogz:167.865>10]

1755it [03:54,  2.61it/s, bound:716 nc: 27 ncall:5.1e+04 eff:3.4% logz=594725.65+/-0.79 dlogz:166.820>10]

1756it [03:54,  2.61it/s, bound:716 nc: 33 ncall:5.1e+04 eff:3.4% logz=594726.86+/-0.80 dlogz:165.749>10]

1757it [03:54,  2.62it/s, bound:717 nc: 30 ncall:5.1e+04 eff:3.4% logz=594727.74+/-0.79 dlogz:164.527>10]

1758it [03:55,  2.60it/s, bound:717 nc: 35 ncall:5.1e+04 eff:3.4% logz=594728.49+/-0.79 dlogz:163.636>10]

1759it [03:55,  2.80it/s, bound:718 nc: 27 ncall:5.1e+04 eff:3.4% logz=594729.15+/-0.79 dlogz:162.876>10]

1760it [03:55,  2.93it/s, bound:718 nc: 27 ncall:5.1e+04 eff:3.4% logz=594729.74+/-0.79 dlogz:162.207>10]

1761it [03:56,  3.01it/s, bound:719 nc: 29 ncall:5.1e+04 eff:3.4% logz=594730.41+/-0.79 dlogz:161.596>10]

1762it [03:56,  2.89it/s, bound:719 nc: 35 ncall:5.1e+04 eff:3.4% logz=594731.11+/-0.79 dlogz:160.922>10]

1763it [03:56,  2.78it/s, bound:720 nc: 35 ncall:5.2e+04 eff:3.4% logz=594732.45+/-0.80 dlogz:160.207>10]

1764it [03:57,  2.20it/s, bound:720 nc: 61 ncall:5.2e+04 eff:3.4% logz=594733.33+/-0.79 dlogz:158.851>10]

1765it [03:57,  2.37it/s, bound:721 nc: 31 ncall:5.2e+04 eff:3.4% logz=594734.18+/-0.79 dlogz:157.963>10]

1766it [03:58,  2.45it/s, bound:721 nc: 35 ncall:5.2e+04 eff:3.4% logz=594737.48+/-0.81 dlogz:157.101>10]

1767it [03:58,  2.65it/s, bound:722 nc: 27 ncall:5.2e+04 eff:3.4% logz=594738.97+/-0.80 dlogz:153.787>10]

1768it [03:58,  2.79it/s, bound:722 nc: 29 ncall:5.2e+04 eff:3.4% logz=594741.21+/-0.81 dlogz:152.280>10]

1769it [03:59,  2.77it/s, bound:723 nc: 33 ncall:5.2e+04 eff:3.4% logz=594742.97+/-0.81 dlogz:150.031>10]

1770it [03:59,  2.81it/s, bound:723 nc: 30 ncall:5.2e+04 eff:3.4% logz=594743.96+/-0.80 dlogz:148.257>10]

1771it [04:00,  2.70it/s, bound:724 nc: 35 ncall:5.2e+04 eff:3.4% logz=594744.78+/-0.79 dlogz:147.260>10]

1772it [04:00,  2.70it/s, bound:724 nc: 35 ncall:5.2e+04 eff:3.4% logz=594746.18+/-0.80 dlogz:146.426>10]

1773it [04:00,  2.96it/s, bound:725 nc: 24 ncall:5.2e+04 eff:3.4% logz=594747.93+/-0.81 dlogz:145.015>10]

1774it [04:00,  2.95it/s, bound:725 nc: 30 ncall:5.2e+04 eff:3.4% logz=594749.65+/-0.81 dlogz:143.249>10]

1775it [04:01,  3.05it/s, bound:726 nc: 28 ncall:5.2e+04 eff:3.4% logz=594750.57+/-0.80 dlogz:141.518>10]

1776it [04:01,  2.91it/s, bound:726 nc: 34 ncall:5.2e+04 eff:3.4% logz=594751.32+/-0.79 dlogz:140.584>10]

1777it [04:02,  2.82it/s, bound:727 nc: 34 ncall:5.2e+04 eff:3.4% logz=594752.19+/-0.79 dlogz:139.821>10]

1778it [04:02,  2.86it/s, bound:727 nc: 30 ncall:5.2e+04 eff:3.4% logz=594753.57+/-0.80 dlogz:138.941>10]

1779it [04:02,  3.13it/s, bound:728 nc: 26 ncall:5.2e+04 eff:3.4% logz=594756.05+/-0.81 dlogz:137.543>10]

1780it [04:03,  2.90it/s, bound:728 nc: 31 ncall:5.2e+04 eff:3.4% logz=594757.57+/-0.81 dlogz:135.050>10]

1781it [04:03,  2.17it/s, bound:729 nc: 63 ncall:5.2e+04 eff:3.4% logz=594758.52+/-0.80 dlogz:133.526>10]

1782it [04:04,  2.56it/s, bound:730 nc: 21 ncall:5.2e+04 eff:3.4% logz=594759.11+/-0.79 dlogz:132.560>10]

1783it [04:04,  2.78it/s, bound:730 nc: 26 ncall:5.2e+04 eff:3.4% logz=594759.53+/-0.79 dlogz:131.958>10]

1784it [04:04,  2.78it/s, bound:730 nc: 33 ncall:5.2e+04 eff:3.4% logz=594760.12+/-0.79 dlogz:131.520>10]

1785it [04:05,  2.80it/s, bound:731 nc: 33 ncall:5.2e+04 eff:3.4% logz=594760.85+/-0.79 dlogz:130.918>10]

1786it [04:05,  2.78it/s, bound:731 nc: 34 ncall:5.2e+04 eff:3.4% logz=594761.55+/-0.79 dlogz:130.180>10]

1787it [04:06,  2.21it/s, bound:732 nc: 60 ncall:5.2e+04 eff:3.4% logz=594762.10+/-0.79 dlogz:129.463>10]

1788it [04:06,  2.29it/s, bound:733 nc: 35 ncall:5.2e+04 eff:3.4% logz=594762.84+/-0.79 dlogz:128.903>10]

1789it [04:06,  2.56it/s, bound:733 nc: 28 ncall:5.2e+04 eff:3.4% logz=594763.54+/-0.79 dlogz:128.151>10]

1790it [04:07,  2.63it/s, bound:734 nc: 30 ncall:5.2e+04 eff:3.4% logz=594764.20+/-0.79 dlogz:127.439>10]

1791it [04:07,  2.59it/s, bound:734 nc: 34 ncall:5.2e+04 eff:3.4% logz=594764.83+/-0.79 dlogz:126.770>10]

1792it [04:07,  2.65it/s, bound:735 nc: 32 ncall:5.2e+04 eff:3.4% logz=594766.10+/-0.80 dlogz:126.123>10]

1793it [04:08,  2.71it/s, bound:735 nc: 33 ncall:5.3e+04 eff:3.4% logz=594769.90+/-0.82 dlogz:124.840>10]

1794it [04:08,  2.74it/s, bound:736 nc: 34 ncall:5.3e+04 eff:3.4% logz=594771.90+/-0.81 dlogz:121.028>10]

1795it [04:08,  2.89it/s, bound:736 nc: 29 ncall:5.3e+04 eff:3.4% logz=594773.21+/-0.81 dlogz:126.949>10]

1796it [04:09,  3.10it/s, bound:737 nc: 25 ncall:5.3e+04 eff:3.4% logz=594774.03+/-0.80 dlogz:125.621>10]

1797it [04:09,  3.09it/s, bound:737 nc: 31 ncall:5.3e+04 eff:3.4% logz=594775.31+/-0.81 dlogz:124.786>10]

1798it [04:09,  2.96it/s, bound:738 nc: 34 ncall:5.3e+04 eff:3.4% logz=594776.37+/-0.80 dlogz:123.494>10]

1799it [04:10,  2.28it/s, bound:738 nc: 65 ncall:5.3e+04 eff:3.4% logz=594777.48+/-0.80 dlogz:122.421>10]

1800it [04:10,  2.45it/s, bound:739 nc: 31 ncall:5.3e+04 eff:3.4% logz=594778.28+/-0.80 dlogz:121.301>10]

1801it [04:11,  2.52it/s, bound:739 nc: 33 ncall:5.3e+04 eff:3.4% logz=594778.79+/-0.80 dlogz:120.493>10]

1802it [04:11,  2.52it/s, bound:740 nc: 35 ncall:5.3e+04 eff:3.4% logz=594779.19+/-0.79 dlogz:119.971>10]

1803it [04:11,  2.62it/s, bound:740 nc: 32 ncall:5.3e+04 eff:3.4% logz=594779.62+/-0.79 dlogz:119.551>10]

1804it [04:12,  2.78it/s, bound:741 nc: 34 ncall:5.3e+04 eff:3.4% logz=594780.00+/-0.79 dlogz:119.111>10]

1805it [04:12,  2.83it/s, bound:741 nc: 35 ncall:5.3e+04 eff:3.4% logz=594780.31+/-0.79 dlogz:118.724>10]

1806it [04:12,  3.19it/s, bound:742 nc: 20 ncall:5.3e+04 eff:3.4% logz=594780.62+/-0.79 dlogz:118.401>10]

1807it [04:13,  3.00it/s, bound:742 nc: 35 ncall:5.3e+04 eff:3.4% logz=594781.13+/-0.79 dlogz:118.079>10]

1808it [04:13,  3.39it/s, bound:743 nc: 23 ncall:5.3e+04 eff:3.4% logz=594781.82+/-0.79 dlogz:117.555>10]

1809it [04:14,  2.42it/s, bound:743 nc: 62 ncall:5.3e+04 eff:3.4% logz=594783.00+/-0.80 dlogz:116.855>10]

1810it [04:14,  2.10it/s, bound:744 nc: 59 ncall:5.3e+04 eff:3.4% logz=594784.70+/-0.81 dlogz:115.660>10]

1811it [04:15,  1.90it/s, bound:745 nc: 59 ncall:5.3e+04 eff:3.4% logz=594785.76+/-0.81 dlogz:113.948>10]

1812it [04:15,  2.11it/s, bound:746 nc: 34 ncall:5.3e+04 eff:3.4% logz=594786.47+/-0.80 dlogz:179.131>10]

1813it [04:16,  2.28it/s, bound:746 nc: 35 ncall:5.3e+04 eff:3.4% logz=594787.06+/-0.80 dlogz:178.412>10]

1814it [04:16,  2.45it/s, bound:747 nc: 31 ncall:5.3e+04 eff:3.4% logz=594787.60+/-0.80 dlogz:177.804>10]

1815it [04:16,  2.65it/s, bound:747 nc: 35 ncall:5.3e+04 eff:3.4% logz=594787.99+/-0.79 dlogz:177.255>10]

1816it [04:16,  2.83it/s, bound:748 nc: 26 ncall:5.3e+04 eff:3.4% logz=594788.35+/-0.79 dlogz:176.848>10]

1817it [04:17,  2.96it/s, bound:748 nc: 28 ncall:5.3e+04 eff:3.4% logz=594788.66+/-0.79 dlogz:176.478>10]

1818it [04:17,  2.90it/s, bound:749 nc: 35 ncall:5.3e+04 eff:3.4% logz=594788.98+/-0.79 dlogz:176.154>10]

1819it [04:18,  2.89it/s, bound:749 nc: 33 ncall:5.3e+04 eff:3.4% logz=594789.48+/-0.79 dlogz:175.827>10]

1820it [04:18,  2.99it/s, bound:750 nc: 28 ncall:5.3e+04 eff:3.4% logz=594790.50+/-0.80 dlogz:175.309>10]

1821it [04:18,  2.97it/s, bound:750 nc: 31 ncall:5.4e+04 eff:3.4% logz=594791.40+/-0.80 dlogz:174.278>10]

1822it [04:19,  2.85it/s, bound:751 nc: 35 ncall:5.4e+04 eff:3.4% logz=594792.07+/-0.80 dlogz:173.367>10]

1823it [04:19,  2.88it/s, bound:751 nc: 34 ncall:5.4e+04 eff:3.4% logz=594792.62+/-0.80 dlogz:172.681>10]

1824it [04:19,  3.06it/s, bound:752 nc: 26 ncall:5.4e+04 eff:3.4% logz=594793.04+/-0.80 dlogz:172.123>10]

1825it [04:20,  2.92it/s, bound:752 nc: 35 ncall:5.4e+04 eff:3.4% logz=594793.49+/-0.79 dlogz:171.689>10]

1826it [04:20,  3.07it/s, bound:753 nc: 32 ncall:5.4e+04 eff:3.4% logz=594794.68+/-0.81 dlogz:171.232>10]

1827it [04:20,  3.00it/s, bound:753 nc: 35 ncall:5.4e+04 eff:3.4% logz=594795.50+/-0.80 dlogz:170.026>10]

1828it [04:21,  2.98it/s, bound:754 nc: 35 ncall:5.4e+04 eff:3.4% logz=594796.45+/-0.81 dlogz:169.190>10]

1829it [04:21,  3.03it/s, bound:754 nc: 28 ncall:5.4e+04 eff:3.4% logz=594797.19+/-0.80 dlogz:168.232>10]

1830it [04:21,  2.45it/s, bound:755 nc: 54 ncall:5.4e+04 eff:3.4% logz=594797.77+/-0.80 dlogz:167.482>10]

1831it [04:22,  2.63it/s, bound:756 nc: 25 ncall:5.4e+04 eff:3.4% logz=594798.28+/-0.80 dlogz:166.881>10]

1832it [04:22,  2.90it/s, bound:756 nc: 25 ncall:5.4e+04 eff:3.4% logz=594798.66+/-0.80 dlogz:166.358>10]

1833it [04:22,  2.77it/s, bound:757 nc: 35 ncall:5.4e+04 eff:3.4% logz=594799.37+/-0.80 dlogz:165.967>10]

1834it [04:23,  2.72it/s, bound:757 nc: 34 ncall:5.4e+04 eff:3.4% logz=594800.30+/-0.80 dlogz:165.249>10]

1835it [04:23,  2.81it/s, bound:758 nc: 29 ncall:5.4e+04 eff:3.4% logz=594801.03+/-0.80 dlogz:164.310>10]

1836it [04:23,  2.84it/s, bound:758 nc: 35 ncall:5.4e+04 eff:3.4% logz=594801.69+/-0.80 dlogz:163.567>10]

1837it [04:24,  2.79it/s, bound:759 nc: 33 ncall:5.4e+04 eff:3.4% logz=594802.25+/-0.80 dlogz:162.892>10]

1838it [04:24,  2.73it/s, bound:759 nc: 35 ncall:5.4e+04 eff:3.4% logz=594802.68+/-0.80 dlogz:162.319>10]

1839it [04:25,  2.73it/s, bound:760 nc: 35 ncall:5.4e+04 eff:3.4% logz=594803.01+/-0.80 dlogz:161.875>10]

1840it [04:25,  3.09it/s, bound:760 nc: 21 ncall:5.4e+04 eff:3.4% logz=594803.30+/-0.79 dlogz:161.530>10]

1841it [04:25,  3.02it/s, bound:761 nc: 35 ncall:5.4e+04 eff:3.4% logz=594805.93+/-0.83 dlogz:161.227>10]

1843it [04:25,  4.52it/s, bound:762 nc: 34 ncall:5.4e+04 eff:3.4% logz=594809.73+/-0.82 dlogz:156.262>10]

1845it [04:25,  6.03it/s, bound:763 nc: 34 ncall:5.4e+04 eff:3.4% logz=594811.72+/-0.81 dlogz:153.599>10]

1847it [04:26,  7.21it/s, bound:764 nc: 28 ncall:5.4e+04 eff:3.4% logz=594813.09+/-0.80 dlogz:151.849>10]

1849it [04:26,  8.43it/s, bound:765 nc: 22 ncall:5.4e+04 eff:3.4% logz=594813.75+/-0.80 dlogz:150.967>10]

1850it [04:26,  8.61it/s, bound:765 nc: 35 ncall:5.4e+04 eff:3.4% logz=594813.98+/-0.80 dlogz:150.666>10]

1852it [04:26,  9.62it/s, bound:766 nc: 27 ncall:5.4e+04 eff:3.4% logz=594814.90+/-0.80 dlogz:150.095>10]

1854it [04:26, 10.69it/s, bound:767 nc: 22 ncall:5.5e+04 eff:3.4% logz=594815.99+/-0.80 dlogz:148.856>10]

1856it [04:27,  9.46it/s, bound:768 nc: 68 ncall:5.5e+04 eff:3.4% logz=594817.25+/-0.80 dlogz:147.721>10]

1858it [04:27, 10.01it/s, bound:769 nc: 34 ncall:5.5e+04 eff:3.4% logz=594818.06+/-0.80 dlogz:146.640>10]

1860it [04:27,  9.99it/s, bound:770 nc: 35 ncall:5.5e+04 eff:3.4% logz=594819.77+/-0.81 dlogz:145.336>10]

1862it [04:27,  9.94it/s, bound:771 nc: 34 ncall:5.5e+04 eff:3.4% logz=594820.91+/-0.80 dlogz:143.884>10]

1864it [04:27,  8.63it/s, bound:772 nc: 65 ncall:5.5e+04 eff:3.4% logz=594821.83+/-0.80 dlogz:142.830>10]

1866it [04:28,  9.26it/s, bound:773 nc: 32 ncall:5.5e+04 eff:3.4% logz=594822.93+/-0.80 dlogz:141.867>10]

1867it [04:28,  9.33it/s, bound:774 nc: 35 ncall:5.5e+04 eff:3.4% logz=594823.35+/-0.80 dlogz:141.280>10]

1869it [04:28,  9.70it/s, bound:775 nc: 35 ncall:5.5e+04 eff:3.4% logz=594824.61+/-0.81 dlogz:140.397>10]

1871it [04:28,  9.76it/s, bound:776 nc: 35 ncall:5.5e+04 eff:3.4% logz=594825.83+/-0.81 dlogz:138.822>10]

1872it [04:28,  9.66it/s, bound:776 nc: 35 ncall:5.5e+04 eff:3.4% logz=594826.21+/-0.80 dlogz:138.313>10]

1873it [04:28,  9.53it/s, bound:777 nc: 35 ncall:5.5e+04 eff:3.4% logz=594826.72+/-0.80 dlogz:137.928>10]

1874it [04:28,  9.58it/s, bound:777 nc: 35 ncall:5.5e+04 eff:3.4% logz=594827.21+/-0.80 dlogz:137.402>10]

1876it [04:29,  9.99it/s, bound:778 nc: 34 ncall:5.5e+04 eff:3.4% logz=594829.38+/-0.81 dlogz:135.647>10]

1878it [04:29,  8.64it/s, bound:779 nc: 60 ncall:5.5e+04 eff:3.4% logz=594830.30+/-0.81 dlogz:134.126>10]

1880it [04:29,  9.11it/s, bound:780 nc: 35 ncall:5.5e+04 eff:3.4% logz=594830.94+/-0.80 dlogz:133.419>10]

1882it [04:29,  9.54it/s, bound:781 nc: 35 ncall:5.6e+04 eff:3.4% logz=594831.50+/-0.80 dlogz:132.823>10]

1883it [04:29,  8.52it/s, bound:782 nc: 53 ncall:5.6e+04 eff:3.4% logz=594832.01+/-0.80 dlogz:144.112>10]

1885it [04:30, 10.03it/s, bound:783 nc: 16 ncall:5.6e+04 eff:3.4% logz=594832.95+/-0.80 dlogz:143.061>10]

1887it [04:30,  9.12it/s, bound:784 nc: 25 ncall:5.6e+04 eff:3.4% logz=594833.83+/-0.80 dlogz:142.219>10]

1888it [04:30,  9.19it/s, bound:784 nc: 35 ncall:5.6e+04 eff:3.4% logz=594834.26+/-0.80 dlogz:141.726>10]

1889it [04:30,  9.32it/s, bound:785 nc: 35 ncall:5.6e+04 eff:3.4% logz=594834.58+/-0.80 dlogz:141.274>10]

1891it [04:30, 10.49it/s, bound:786 nc: 31 ncall:5.6e+04 eff:3.4% logz=594835.09+/-0.80 dlogz:140.687>10]

1893it [04:30, 10.22it/s, bound:787 nc: 34 ncall:5.6e+04 eff:3.4% logz=594835.82+/-0.80 dlogz:140.022>10]

1895it [04:31, 11.03it/s, bound:788 nc: 24 ncall:5.6e+04 eff:3.4% logz=594837.01+/-0.81 dlogz:139.292>10]

1897it [04:31,  9.83it/s, bound:788 nc: 65 ncall:5.6e+04 eff:3.4% logz=594838.28+/-0.81 dlogz:137.658>10]

1899it [04:31, 10.85it/s, bound:789 nc: 22 ncall:5.6e+04 eff:3.4% logz=594839.78+/-0.81 dlogz:136.401>10]

1901it [04:31,  9.49it/s, bound:791 nc: 35 ncall:5.6e+04 eff:3.4% logz=594841.06+/-0.81 dlogz:134.980>10]

1903it [04:32,  7.89it/s, bound:792 nc: 70 ncall:5.6e+04 eff:3.4% logz=594842.16+/-0.81 dlogz:133.779>10]

1904it [04:32,  8.18it/s, bound:793 nc: 35 ncall:5.6e+04 eff:3.4% logz=594842.66+/-0.81 dlogz:133.188>10]

1906it [04:32,  8.71it/s, bound:794 nc: 35 ncall:5.6e+04 eff:3.4% logz=594843.30+/-0.81 dlogz:132.319>10]

1907it [04:32,  7.84it/s, bound:794 nc: 56 ncall:5.6e+04 eff:3.4% logz=594843.54+/-0.80 dlogz:132.014>10]

1908it [04:32,  8.09it/s, bound:795 nc: 35 ncall:5.6e+04 eff:3.4% logz=594844.24+/-0.81 dlogz:131.758>10]

1909it [04:32,  8.43it/s, bound:795 nc: 35 ncall:5.6e+04 eff:3.4% logz=594844.93+/-0.81 dlogz:131.048>10]

1911it [04:32,  9.83it/s, bound:796 nc: 35 ncall:5.7e+04 eff:3.4% logz=594846.33+/-0.82 dlogz:129.578>10]

1913it [04:33,  9.85it/s, bound:797 nc: 35 ncall:5.7e+04 eff:3.4% logz=594847.38+/-0.81 dlogz:128.326>10]

1915it [04:33, 10.37it/s, bound:798 nc: 28 ncall:5.7e+04 eff:3.4% logz=594848.25+/-0.81 dlogz:127.416>10]

1917it [04:33,  8.38it/s, bound:799 nc: 77 ncall:5.7e+04 eff:3.4% logz=594848.98+/-0.81 dlogz:126.528>10]

1918it [04:33,  8.59it/s, bound:800 nc: 35 ncall:5.7e+04 eff:3.4% logz=594849.22+/-0.81 dlogz:126.199>10]

1919it [04:33,  7.30it/s, bound:800 nc: 70 ncall:5.7e+04 eff:3.4% logz=594849.43+/-0.81 dlogz:125.943>10]

1920it [04:34,  7.69it/s, bound:801 nc: 35 ncall:5.7e+04 eff:3.4% logz=594849.65+/-0.80 dlogz:125.727>10]

1921it [04:34,  6.67it/s, bound:801 nc: 70 ncall:5.7e+04 eff:3.4% logz=594849.90+/-0.80 dlogz:125.487>10]

1923it [04:34,  7.76it/s, bound:802 nc: 35 ncall:5.7e+04 eff:3.4% logz=594850.67+/-0.81 dlogz:124.912>10]

1924it [04:34,  8.10it/s, bound:803 nc: 35 ncall:5.7e+04 eff:3.4% logz=594851.10+/-0.81 dlogz:124.430>10]

1925it [04:34,  7.72it/s, bound:803 nc: 48 ncall:5.7e+04 eff:3.4% logz=594851.41+/-0.81 dlogz:123.990>10]

1926it [04:34,  8.18it/s, bound:804 nc: 34 ncall:5.7e+04 eff:3.4% logz=594851.66+/-0.81 dlogz:123.669>10]

1927it [04:34,  8.60it/s, bound:804 nc: 35 ncall:5.7e+04 eff:3.4% logz=594851.87+/-0.81 dlogz:123.403>10]

1928it [04:34,  8.85it/s, bound:805 nc: 35 ncall:5.7e+04 eff:3.4% logz=594852.36+/-0.81 dlogz:123.182>10]

1930it [04:35, 10.03it/s, bound:806 nc: 25 ncall:5.7e+04 eff:3.4% logz=594853.43+/-0.81 dlogz:122.113>10]

1932it [04:35,  9.90it/s, bound:807 nc: 35 ncall:5.7e+04 eff:3.4% logz=594854.22+/-0.81 dlogz:121.128>10]

1934it [04:35,  9.90it/s, bound:808 nc: 34 ncall:5.7e+04 eff:3.4% logz=594854.81+/-0.81 dlogz:120.463>10]

1935it [04:35,  9.77it/s, bound:808 nc: 35 ncall:5.7e+04 eff:3.4% logz=594855.15+/-0.81 dlogz:120.161>10]

1936it [04:35,  9.62it/s, bound:809 nc: 29 ncall:5.7e+04 eff:3.4% logz=594855.45+/-0.81 dlogz:119.809>10]

1938it [04:35,  9.89it/s, bound:810 nc: 35 ncall:5.8e+04 eff:3.4% logz=594855.95+/-0.81 dlogz:119.224>10]

1939it [04:36,  8.01it/s, bound:810 nc: 69 ncall:5.8e+04 eff:3.4% logz=594856.18+/-0.81 dlogz:118.968>10]

1940it [04:36,  8.29it/s, bound:811 nc: 35 ncall:5.8e+04 eff:3.4% logz=594856.39+/-0.81 dlogz:118.727>10]

1941it [04:36,  8.58it/s, bound:811 nc: 35 ncall:5.8e+04 eff:3.4% logz=594856.62+/-0.81 dlogz:118.502>10]

1942it [04:36,  8.79it/s, bound:812 nc: 35 ncall:5.8e+04 eff:3.4% logz=594856.96+/-0.81 dlogz:118.260>10]

1943it [04:36,  9.02it/s, bound:812 nc: 34 ncall:5.8e+04 eff:3.4% logz=594857.40+/-0.81 dlogz:117.906>10]

1944it [04:36,  9.12it/s, bound:813 nc: 35 ncall:5.8e+04 eff:3.4% logz=594858.15+/-0.82 dlogz:117.451>10]

1945it [04:36,  9.23it/s, bound:813 nc: 35 ncall:5.8e+04 eff:3.4% logz=594858.79+/-0.82 dlogz:116.691>10]

1947it [04:36, 10.06it/s, bound:814 nc: 34 ncall:5.8e+04 eff:3.4% logz=594859.57+/-0.82 dlogz:115.595>10]

1949it [04:37, 10.53it/s, bound:815 nc: 30 ncall:5.8e+04 eff:3.4% logz=594860.11+/-0.81 dlogz:114.933>10]

1951it [04:37,  9.98it/s, bound:816 nc: 35 ncall:5.8e+04 eff:3.4% logz=594860.63+/-0.81 dlogz:114.406>10]

1952it [04:37,  9.91it/s, bound:817 nc: 35 ncall:5.8e+04 eff:3.4% logz=594860.88+/-0.81 dlogz:114.124>10]

1953it [04:37,  9.72it/s, bound:817 nc: 35 ncall:5.8e+04 eff:3.4% logz=594861.18+/-0.81 dlogz:113.863>10]

1955it [04:37,  8.13it/s, bound:818 nc: 70 ncall:5.8e+04 eff:3.4% logz=594861.96+/-0.81 dlogz:113.175>10]

1957it [04:38,  7.55it/s, bound:819 nc: 70 ncall:5.8e+04 eff:3.4% logz=594862.76+/-0.81 dlogz:112.319>10]

1959it [04:38,  8.29it/s, bound:820 nc: 35 ncall:5.8e+04 eff:3.4% logz=594863.50+/-0.81 dlogz:111.547>10]

1960it [04:38,  8.53it/s, bound:821 nc: 35 ncall:5.8e+04 eff:3.4% logz=594863.98+/-0.82 dlogz:111.159>10]

1961it [04:38,  8.72it/s, bound:821 nc: 35 ncall:5.8e+04 eff:3.4% logz=594864.83+/-0.82 dlogz:110.669>10]

1962it [04:38,  8.87it/s, bound:822 nc: 35 ncall:5.8e+04 eff:3.4% logz=594865.30+/-0.82 dlogz:109.806>10]

1963it [04:38,  8.99it/s, bound:822 nc: 35 ncall:5.8e+04 eff:3.4% logz=594865.73+/-0.82 dlogz:109.320>10]

1964it [04:39,  7.29it/s, bound:823 nc: 70 ncall:5.9e+04 eff:3.4% logz=594866.15+/-0.82 dlogz:108.880>10]

1965it [04:39,  7.77it/s, bound:824 nc: 35 ncall:5.9e+04 eff:3.4% logz=594866.55+/-0.82 dlogz:108.449>10]

1966it [04:39,  8.20it/s, bound:824 nc: 35 ncall:5.9e+04 eff:3.4% logz=594867.17+/-0.82 dlogz:108.029>10]

1968it [04:39,  9.15it/s, bound:825 nc: 35 ncall:5.9e+04 eff:3.4% logz=594868.07+/-0.82 dlogz:106.842>10]

1970it [04:39,  9.42it/s, bound:826 nc: 34 ncall:5.9e+04 eff:3.4% logz=594868.80+/-0.82 dlogz:106.177>10]

1971it [04:39,  9.44it/s, bound:827 nc: 35 ncall:5.9e+04 eff:3.4% logz=594869.67+/-0.83 dlogz:105.725>10]

1972it [04:39,  9.50it/s, bound:827 nc: 34 ncall:5.9e+04 eff:3.4% logz=594870.49+/-0.83 dlogz:104.841>10]

1974it [04:40, 10.43it/s, bound:828 nc: 29 ncall:5.9e+04 eff:3.4% logz=594871.96+/-0.83 dlogz:103.165>10]

1976it [04:40, 10.17it/s, bound:829 nc: 35 ncall:5.9e+04 eff:3.4% logz=594872.97+/-0.82 dlogz:101.981>10]

1978it [04:40, 10.85it/s, bound:830 nc: 22 ncall:5.9e+04 eff:3.4% logz=594873.84+/-0.82 dlogz:100.994>10]

1980it [04:40, 10.59it/s, bound:831 nc: 35 ncall:5.9e+04 eff:3.4% logz=594874.46+/-0.82 dlogz:100.232>10]

1982it [04:40,  8.79it/s, bound:832 nc: 70 ncall:5.9e+04 eff:3.3% logz=594875.47+/-0.82 dlogz:99.424>10]

1984it [04:41,  9.63it/s, bound:833 nc: 25 ncall:5.9e+04 eff:3.3% logz=594876.33+/-0.82 dlogz:98.443>10]

1986it [04:41,  7.48it/s, bound:835 nc: 99 ncall:5.9e+04 eff:3.3% logz=594876.96+/-0.82 dlogz:97.659>10]

1987it [04:41,  7.83it/s, bound:835 nc:  1 ncall:5.9e+04 eff:3.5% logz=594931.10+/-0.86 dlogz:41.210>10]

1988it [04:41,  8.19it/s, bound:836 nc: 35 ncall:5.9e+04 eff:3.3% logz=594877.55+/-0.82 dlogz:97.110>10]

1989it [04:41,  7.12it/s, bound:836 nc: 70 ncall:6.0e+04 eff:3.3% logz=594877.89+/-0.82 dlogz:96.743>10]

1990it [04:41,  7.60it/s, bound:837 nc: 35 ncall:6.0e+04 eff:3.3% logz=594878.36+/-0.82 dlogz:96.398>10]

1991it [04:42,  8.01it/s, bound:837 nc: 35 ncall:6.0e+04 eff:3.3% logz=594880.72+/-0.85 dlogz:95.916>10]

1992it [04:42,  8.38it/s, bound:838 nc: 35 ncall:6.0e+04 eff:3.3% logz=594881.81+/-0.84 dlogz:93.541>10]

1993it [04:42,  8.71it/s, bound:838 nc: 35 ncall:6.0e+04 eff:3.3% logz=594882.39+/-0.84 dlogz:92.441>10]

1994it [04:42,  8.90it/s, bound:839 nc: 35 ncall:6.0e+04 eff:3.3% logz=594882.78+/-0.83 dlogz:91.849>10]

1995it [04:42,  9.07it/s, bound:839 nc: 35 ncall:6.0e+04 eff:3.3% logz=594883.09+/-0.83 dlogz:91.437>10]

1997it [04:42,  9.37it/s, bound:840 nc: 34 ncall:6.0e+04 eff:3.3% logz=594884.63+/-0.83 dlogz:90.284>10]

1998it [04:42,  9.48it/s, bound:841 nc: 35 ncall:6.0e+04 eff:3.3% logz=594885.10+/-0.83 dlogz:89.555>10]

2000it [04:42,  9.94it/s, bound:842 nc: 31 ncall:6.0e+04 eff:3.3% logz=594885.82+/-0.83 dlogz:88.703>10]

2001it [04:43,  7.96it/s, bound:842 nc: 70 ncall:6.0e+04 eff:3.3% logz=594886.15+/-0.82 dlogz:88.332>10]

2003it [04:43,  8.76it/s, bound:843 nc: 35 ncall:6.0e+04 eff:3.3% logz=594886.80+/-0.82 dlogz:87.669>10]

2004it [04:43,  8.97it/s, bound:844 nc: 35 ncall:6.0e+04 eff:3.3% logz=594887.24+/-0.82 dlogz:87.314>10]

2005it [04:43,  9.16it/s, bound:844 nc: 35 ncall:6.0e+04 eff:3.3% logz=594887.69+/-0.83 dlogz:86.862>10]

2006it [04:43,  9.34it/s, bound:845 nc: 34 ncall:6.0e+04 eff:3.3% logz=594888.06+/-0.82 dlogz:86.391>10]

2007it [04:43,  9.45it/s, bound:845 nc: 35 ncall:6.0e+04 eff:3.3% logz=594888.35+/-0.82 dlogz:86.017>10]

2008it [04:43,  9.56it/s, bound:846 nc: 33 ncall:6.0e+04 eff:3.3% logz=594888.63+/-0.82 dlogz:85.707>10]

2009it [04:43,  9.62it/s, bound:846 nc: 35 ncall:6.0e+04 eff:3.3% logz=594888.93+/-0.82 dlogz:85.416>10]

2010it [04:44,  7.80it/s, bound:847 nc: 63 ncall:6.0e+04 eff:3.3% logz=594889.29+/-0.82 dlogz:85.101>10]

2011it [04:44,  8.30it/s, bound:848 nc: 35 ncall:6.0e+04 eff:3.3% logz=594889.73+/-0.82 dlogz:84.738>10]

2013it [04:44,  8.91it/s, bound:849 nc: 34 ncall:6.0e+04 eff:3.3% logz=594890.49+/-0.82 dlogz:83.837>10]

2014it [04:44,  9.11it/s, bound:849 nc: 34 ncall:6.0e+04 eff:3.3% logz=594890.74+/-0.82 dlogz:83.501>10]

2015it [04:44,  9.18it/s, bound:850 nc: 35 ncall:6.0e+04 eff:3.3% logz=594891.26+/-0.83 dlogz:83.238>10]

2016it [04:44,  9.27it/s, bound:850 nc: 35 ncall:6.1e+04 eff:3.3% logz=594891.76+/-0.83 dlogz:82.700>10]

2017it [04:44,  9.26it/s, bound:851 nc: 35 ncall:6.1e+04 eff:3.3% logz=594892.23+/-0.83 dlogz:82.185>10]

2018it [04:45,  9.36it/s, bound:851 nc: 35 ncall:6.1e+04 eff:3.3% logz=594892.63+/-0.83 dlogz:81.707>10]

2019it [04:45,  9.36it/s, bound:852 nc: 35 ncall:6.1e+04 eff:3.3% logz=594892.98+/-0.83 dlogz:81.296>10]

2020it [04:45,  9.47it/s, bound:852 nc: 35 ncall:6.1e+04 eff:3.3% logz=594893.29+/-0.83 dlogz:80.930>10]

2021it [04:45,  9.41it/s, bound:853 nc: 35 ncall:6.1e+04 eff:3.3% logz=594893.59+/-0.83 dlogz:80.607>10]

2022it [04:45,  9.48it/s, bound:853 nc: 35 ncall:6.1e+04 eff:3.3% logz=594893.86+/-0.82 dlogz:80.294>10]

2023it [04:45,  9.07it/s, bound:854 nc: 35 ncall:6.1e+04 eff:3.3% logz=594894.07+/-0.82 dlogz:80.018>10]

2024it [04:45,  9.08it/s, bound:854 nc: 35 ncall:6.1e+04 eff:3.3% logz=594894.27+/-0.82 dlogz:79.795>10]

2026it [04:45, 10.16it/s, bound:855 nc: 34 ncall:6.1e+04 eff:3.3% logz=594894.70+/-0.82 dlogz:79.346>10]

2027it [04:45,  9.54it/s, bound:856 nc: 35 ncall:6.1e+04 eff:3.3% logz=594894.90+/-0.82 dlogz:79.121>10]

2028it [04:46,  7.66it/s, bound:856 nc: 67 ncall:6.1e+04 eff:3.3% logz=594895.08+/-0.82 dlogz:78.910>10]

2029it [04:46,  8.06it/s, bound:857 nc: 35 ncall:6.1e+04 eff:3.3% logz=594895.26+/-0.82 dlogz:78.718>10]

2030it [04:46,  8.38it/s, bound:857 nc: 35 ncall:6.1e+04 eff:3.3% logz=594895.51+/-0.82 dlogz:78.526>10]

2031it [04:46,  6.79it/s, bound:858 nc: 70 ncall:6.1e+04 eff:3.3% logz=594895.81+/-0.82 dlogz:78.263>10]

2033it [04:46,  8.05it/s, bound:859 nc: 32 ncall:6.1e+04 eff:3.3% logz=594896.34+/-0.82 dlogz:77.672>10]

2034it [04:46,  8.34it/s, bound:860 nc: 35 ncall:6.1e+04 eff:3.3% logz=594896.65+/-0.82 dlogz:77.394>10]

2035it [04:47,  7.13it/s, bound:860 nc: 68 ncall:6.1e+04 eff:3.3% logz=594897.12+/-0.83 dlogz:77.073>10]

2036it [04:47,  7.69it/s, bound:861 nc: 35 ncall:6.1e+04 eff:3.3% logz=594897.56+/-0.83 dlogz:76.590>10]

2037it [04:47,  8.19it/s, bound:861 nc: 35 ncall:6.1e+04 eff:3.3% logz=594897.87+/-0.83 dlogz:76.138>10]

2039it [04:47,  9.54it/s, bound:862 nc: 23 ncall:6.1e+04 eff:3.3% logz=594898.53+/-0.83 dlogz:75.525>10]

2040it [04:47,  9.48it/s, bound:863 nc: 35 ncall:6.1e+04 eff:3.3% logz=594898.90+/-0.83 dlogz:75.131>10]

2041it [04:47,  9.55it/s, bound:863 nc: 34 ncall:6.1e+04 eff:3.3% logz=594899.22+/-0.83 dlogz:74.747>10]

2042it [04:47,  9.49it/s, bound:864 nc: 35 ncall:6.1e+04 eff:3.3% logz=594899.50+/-0.83 dlogz:74.421>10]

2043it [04:47,  9.53it/s, bound:864 nc: 35 ncall:6.2e+04 eff:3.3% logz=594899.74+/-0.83 dlogz:74.130>10]

2044it [04:47,  9.51it/s, bound:865 nc: 35 ncall:6.2e+04 eff:3.3% logz=594900.02+/-0.83 dlogz:73.876>10]

2045it [04:48,  9.52it/s, bound:865 nc: 35 ncall:6.2e+04 eff:3.3% logz=594900.31+/-0.83 dlogz:73.584>10]

2047it [04:48, 10.05it/s, bound:866 nc: 31 ncall:6.2e+04 eff:3.3% logz=594900.80+/-0.83 dlogz:73.009>10]

2048it [04:48,  9.90it/s, bound:867 nc: 35 ncall:6.2e+04 eff:3.3% logz=594901.06+/-0.83 dlogz:72.761>10]

2050it [04:48, 10.79it/s, bound:868 nc: 33 ncall:6.2e+04 eff:3.3% logz=594901.49+/-0.83 dlogz:72.249>10]

2052it [04:48, 10.22it/s, bound:869 nc: 35 ncall:6.2e+04 eff:3.3% logz=594902.06+/-0.83 dlogz:71.753>10]

2054it [04:48, 10.75it/s, bound:870 nc: 23 ncall:6.2e+04 eff:3.3% logz=594902.62+/-0.83 dlogz:71.138>10]

2056it [04:49, 10.58it/s, bound:871 nc: 31 ncall:6.2e+04 eff:3.3% logz=594903.12+/-0.83 dlogz:70.595>10]

2058it [04:49,  8.99it/s, bound:872 nc: 61 ncall:6.2e+04 eff:3.3% logz=594903.52+/-0.83 dlogz:70.105>10]

2059it [04:49,  9.10it/s, bound:873 nc: 35 ncall:6.2e+04 eff:3.3% logz=594903.70+/-0.83 dlogz:69.903>10]

2060it [04:49,  9.21it/s, bound:873 nc: 35 ncall:6.2e+04 eff:3.3% logz=594903.96+/-0.83 dlogz:69.710>10]

2061it [04:49,  9.30it/s, bound:874 nc: 35 ncall:6.2e+04 eff:3.3% logz=594904.30+/-0.83 dlogz:69.437>10]

2062it [04:49,  9.44it/s, bound:874 nc: 35 ncall:6.2e+04 eff:3.3% logz=594904.73+/-0.83 dlogz:69.090>10]

2063it [04:49,  9.37it/s, bound:875 nc: 32 ncall:6.2e+04 eff:3.3% logz=594905.16+/-0.83 dlogz:68.650>10]

2064it [04:50,  7.97it/s, bound:875 nc: 61 ncall:6.2e+04 eff:3.3% logz=594905.54+/-0.83 dlogz:68.203>10]

2065it [04:50,  7.35it/s, bound:876 nc: 53 ncall:6.2e+04 eff:3.3% logz=594905.88+/-0.83 dlogz:67.817>10]

2067it [04:50,  8.31it/s, bound:877 nc: 35 ncall:6.2e+04 eff:3.3% logz=594906.49+/-0.83 dlogz:67.150>10]

2068it [04:50,  7.47it/s, bound:878 nc: 59 ncall:6.2e+04 eff:3.3% logz=594906.79+/-0.83 dlogz:66.830>10]

2069it [04:50,  7.93it/s, bound:879 nc: 35 ncall:6.2e+04 eff:3.3% logz=594907.06+/-0.83 dlogz:66.515>10]

2070it [04:50,  8.16it/s, bound:879 nc: 35 ncall:6.3e+04 eff:3.3% logz=594907.44+/-0.83 dlogz:66.230>10]

2072it [04:51,  8.96it/s, bound:880 nc: 35 ncall:6.3e+04 eff:3.3% logz=594908.02+/-0.83 dlogz:65.514>10]

2073it [04:51,  7.57it/s, bound:881 nc: 67 ncall:6.3e+04 eff:3.3% logz=594908.23+/-0.83 dlogz:65.237>10]

2075it [04:51,  8.42it/s, bound:882 nc: 35 ncall:6.3e+04 eff:3.3% logz=594908.59+/-0.83 dlogz:64.817>10]

2076it [04:51,  8.70it/s, bound:883 nc: 35 ncall:6.3e+04 eff:3.3% logz=594908.76+/-0.83 dlogz:64.623>10]

2078it [04:51,  9.28it/s, bound:884 nc: 35 ncall:6.3e+04 eff:3.3% logz=594909.09+/-0.83 dlogz:64.261>10]

2080it [04:51,  9.57it/s, bound:885 nc: 35 ncall:6.3e+04 eff:3.3% logz=594909.43+/-0.83 dlogz:63.908>10]

2081it [04:52,  9.54it/s, bound:885 nc: 35 ncall:6.3e+04 eff:3.3% logz=594909.66+/-0.83 dlogz:63.723>10]

2082it [04:52,  9.62it/s, bound:886 nc: 35 ncall:6.3e+04 eff:3.3% logz=594909.91+/-0.83 dlogz:63.485>10]

2084it [04:52,  9.87it/s, bound:887 nc: 34 ncall:6.3e+04 eff:3.3% logz=594910.37+/-0.83 dlogz:62.990>10]

2085it [04:52,  9.86it/s, bound:887 nc: 35 ncall:6.3e+04 eff:3.3% logz=594910.66+/-0.83 dlogz:62.733>10]

2086it [04:52,  9.77it/s, bound:888 nc: 35 ncall:6.3e+04 eff:3.3% logz=594910.99+/-0.83 dlogz:62.430>10]

2087it [04:52,  9.81it/s, bound:888 nc: 35 ncall:6.3e+04 eff:3.3% logz=594911.28+/-0.83 dlogz:62.092>10]

2088it [04:52,  9.86it/s, bound:889 nc: 35 ncall:6.3e+04 eff:3.3% logz=594911.53+/-0.83 dlogz:61.784>10]

2090it [04:52,  9.87it/s, bound:890 nc: 35 ncall:6.3e+04 eff:3.3% logz=594912.00+/-0.83 dlogz:61.271>10]

2092it [04:53, 10.03it/s, bound:891 nc: 35 ncall:6.3e+04 eff:3.3% logz=594912.41+/-0.83 dlogz:60.816>10]

2093it [04:53,  9.94it/s, bound:891 nc: 35 ncall:6.3e+04 eff:3.3% logz=594912.60+/-0.83 dlogz:60.597>10]

2094it [04:53,  9.87it/s, bound:892 nc: 35 ncall:6.3e+04 eff:3.3% logz=594912.79+/-0.83 dlogz:60.388>10]

2095it [04:53,  9.75it/s, bound:892 nc: 35 ncall:6.3e+04 eff:3.3% logz=594912.97+/-0.83 dlogz:60.192>10]

2096it [04:53,  9.71it/s, bound:893 nc: 35 ncall:6.3e+04 eff:3.3% logz=594913.13+/-0.83 dlogz:60.001>10]

2098it [04:53, 10.05it/s, bound:894 nc: 35 ncall:6.3e+04 eff:3.3% logz=594913.65+/-0.83 dlogz:59.575>10]

2099it [04:53,  9.94it/s, bound:894 nc: 35 ncall:6.4e+04 eff:3.3% logz=594914.07+/-0.84 dlogz:59.280>10]

2100it [04:53,  9.89it/s, bound:895 nc: 35 ncall:6.4e+04 eff:3.3% logz=594914.37+/-0.84 dlogz:58.847>10]

2102it [04:54, 10.12it/s, bound:896 nc: 32 ncall:6.4e+04 eff:3.3% logz=594915.00+/-0.84 dlogz:58.224>10]

2103it [04:54,  9.98it/s, bound:896 nc: 35 ncall:6.4e+04 eff:3.3% logz=594915.30+/-0.84 dlogz:57.879>10]

2104it [04:54,  9.92it/s, bound:897 nc: 34 ncall:6.4e+04 eff:3.3% logz=594915.65+/-0.84 dlogz:57.570>10]

2105it [04:54,  7.71it/s, bound:897 nc: 70 ncall:6.4e+04 eff:3.3% logz=594916.00+/-0.84 dlogz:57.202>10]

2107it [04:54,  8.78it/s, bound:898 nc: 35 ncall:6.4e+04 eff:3.3% logz=594916.53+/-0.84 dlogz:56.572>10]

2108it [04:54,  7.89it/s, bound:899 nc: 54 ncall:6.4e+04 eff:3.3% logz=594916.82+/-0.84 dlogz:56.288>10]

2109it [04:55,  8.20it/s, bound:900 nc: 35 ncall:6.4e+04 eff:3.3% logz=594917.09+/-0.84 dlogz:55.988>10]

2111it [04:55,  9.08it/s, bound:901 nc: 33 ncall:6.4e+04 eff:3.3% logz=594917.53+/-0.84 dlogz:55.451>10]

2112it [04:55,  9.23it/s, bound:901 nc: 35 ncall:6.4e+04 eff:3.3% logz=594917.78+/-0.84 dlogz:55.234>10]

2114it [04:55,  9.88it/s, bound:902 nc: 34 ncall:6.4e+04 eff:3.3% logz=594918.24+/-0.84 dlogz:54.711>10]

2115it [04:55,  8.03it/s, bound:903 nc: 70 ncall:6.4e+04 eff:3.3% logz=594918.44+/-0.84 dlogz:54.487>10]

2116it [04:55,  8.37it/s, bound:904 nc: 35 ncall:6.4e+04 eff:3.3% logz=594918.68+/-0.84 dlogz:54.274>10]

2117it [04:55,  8.61it/s, bound:904 nc: 35 ncall:6.4e+04 eff:3.3% logz=594918.92+/-0.84 dlogz:54.029>10]

2118it [04:56,  8.85it/s, bound:905 nc: 34 ncall:6.4e+04 eff:3.3% logz=594919.24+/-0.84 dlogz:53.774>10]

2119it [04:56,  8.98it/s, bound:905 nc: 35 ncall:6.4e+04 eff:3.3% logz=594919.61+/-0.84 dlogz:53.438>10]

2121it [04:56,  9.78it/s, bound:906 nc: 33 ncall:6.4e+04 eff:3.3% logz=594920.39+/-0.84 dlogz:52.641>10]

2123it [04:56, 10.89it/s, bound:907 nc: 30 ncall:6.4e+04 eff:3.3% logz=594920.95+/-0.84 dlogz:51.959>10]

2125it [04:56, 10.51it/s, bound:908 nc: 32 ncall:6.4e+04 eff:3.3% logz=594921.43+/-0.84 dlogz:51.407>10]

2127it [04:56, 10.47it/s, bound:909 nc: 31 ncall:6.5e+04 eff:3.3% logz=594921.83+/-0.84 dlogz:50.939>10]

2129it [04:57,  9.12it/s, bound:910 nc: 56 ncall:6.5e+04 eff:3.3% logz=594922.14+/-0.84 dlogz:50.563>10]

2130it [04:57,  7.87it/s, bound:911 nc: 65 ncall:6.5e+04 eff:3.3% logz=594922.31+/-0.84 dlogz:50.404>10]

2131it [04:57,  8.21it/s, bound:912 nc: 35 ncall:6.5e+04 eff:3.3% logz=594922.49+/-0.84 dlogz:50.226>10]

2132it [04:57,  8.39it/s, bound:912 nc: 35 ncall:6.5e+04 eff:3.3% logz=594922.65+/-0.84 dlogz:50.034>10]

2133it [04:57,  8.61it/s, bound:913 nc: 35 ncall:6.5e+04 eff:3.3% logz=594922.79+/-0.84 dlogz:49.859>10]

2134it [04:57,  8.81it/s, bound:913 nc: 35 ncall:6.5e+04 eff:3.3% logz=594922.92+/-0.84 dlogz:49.701>10]

2135it [04:57,  8.95it/s, bound:914 nc: 35 ncall:6.5e+04 eff:3.3% logz=594923.04+/-0.84 dlogz:49.560>10]

2137it [04:58,  9.85it/s, bound:915 nc: 34 ncall:6.5e+04 eff:3.3% logz=594923.26+/-0.83 dlogz:49.307>10]

2138it [04:58,  9.77it/s, bound:915 nc: 35 ncall:6.5e+04 eff:3.3% logz=594923.42+/-0.83 dlogz:49.181>10]

2140it [04:58,  9.94it/s, bound:916 nc: 35 ncall:6.5e+04 eff:3.3% logz=594923.80+/-0.84 dlogz:48.802>10]

2141it [04:58,  9.88it/s, bound:917 nc: 35 ncall:6.5e+04 eff:3.3% logz=594923.97+/-0.84 dlogz:48.610>10]

2142it [04:58,  9.82it/s, bound:917 nc: 35 ncall:6.5e+04 eff:3.3% logz=594924.14+/-0.84 dlogz:48.428>10]

2143it [04:58,  9.67it/s, bound:918 nc: 35 ncall:6.5e+04 eff:3.3% logz=594924.30+/-0.84 dlogz:48.244>10]

2145it [04:58,  9.77it/s, bound:919 nc: 35 ncall:6.5e+04 eff:3.3% logz=594924.62+/-0.84 dlogz:47.911>10]

2146it [04:58,  9.76it/s, bound:919 nc: 35 ncall:6.5e+04 eff:3.3% logz=594924.79+/-0.84 dlogz:47.728>10]

2147it [04:59,  9.66it/s, bound:920 nc: 35 ncall:6.5e+04 eff:3.3% logz=594924.94+/-0.84 dlogz:47.547>10]

2149it [04:59, 10.05it/s, bound:921 nc: 35 ncall:6.5e+04 eff:3.3% logz=594925.21+/-0.84 dlogz:47.227>10]

2150it [04:59,  9.99it/s, bound:921 nc: 34 ncall:6.5e+04 eff:3.3% logz=594925.33+/-0.84 dlogz:47.086>10]

2151it [04:59,  9.83it/s, bound:922 nc: 35 ncall:6.5e+04 eff:3.3% logz=594925.46+/-0.84 dlogz:46.950>10]

2152it [04:59,  9.77it/s, bound:922 nc: 35 ncall:6.5e+04 eff:3.3% logz=594925.59+/-0.84 dlogz:46.814>10]

2153it [04:59,  7.80it/s, bound:923 nc: 65 ncall:6.5e+04 eff:3.3% logz=594925.73+/-0.84 dlogz:53.853>10]

2154it [04:59,  8.20it/s, bound:924 nc: 35 ncall:6.6e+04 eff:3.3% logz=594925.86+/-0.84 dlogz:53.703>10]

2155it [05:00,  5.63it/s, bound:925 nc:105 ncall:6.6e+04 eff:3.3% logz=594925.99+/-0.84 dlogz:53.562>10]

2156it [05:00,  6.34it/s, bound:925 nc: 35 ncall:6.6e+04 eff:3.3% logz=594926.13+/-0.84 dlogz:53.419>10]

2157it [05:00,  7.03it/s, bound:926 nc: 35 ncall:6.6e+04 eff:3.3% logz=594926.26+/-0.84 dlogz:53.266>10]

2158it [05:00,  7.66it/s, bound:926 nc: 35 ncall:6.6e+04 eff:3.3% logz=594926.41+/-0.84 dlogz:53.123>10]

2159it [05:00,  8.12it/s, bound:927 nc: 35 ncall:6.6e+04 eff:3.3% logz=594926.59+/-0.84 dlogz:52.963>10]

2160it [05:00,  8.58it/s, bound:927 nc: 35 ncall:6.6e+04 eff:3.3% logz=594926.77+/-0.84 dlogz:52.770>10]

2162it [05:00,  9.53it/s, bound:928 nc: 35 ncall:6.6e+04 eff:3.3% logz=594927.09+/-0.84 dlogz:52.400>10]

2163it [05:01,  8.08it/s, bound:929 nc: 61 ncall:6.6e+04 eff:3.3% logz=594927.24+/-0.84 dlogz:52.230>10]

2165it [05:01,  8.85it/s, bound:930 nc: 34 ncall:6.6e+04 eff:3.3% logz=594927.54+/-0.84 dlogz:51.898>10]

2166it [05:01,  9.07it/s, bound:931 nc: 34 ncall:6.6e+04 eff:3.3% logz=594927.67+/-0.84 dlogz:51.742>10]

2167it [05:01,  9.22it/s, bound:931 nc: 35 ncall:6.6e+04 eff:3.3% logz=594927.79+/-0.84 dlogz:51.603>10]

2168it [05:01,  9.30it/s, bound:932 nc: 35 ncall:6.6e+04 eff:3.3% logz=594927.93+/-0.84 dlogz:51.470>10]

2170it [05:01,  9.81it/s, bound:933 nc: 35 ncall:6.6e+04 eff:3.3% logz=594928.30+/-0.84 dlogz:51.134>10]

2171it [05:01,  9.76it/s, bound:933 nc: 34 ncall:6.6e+04 eff:3.3% logz=594928.52+/-0.84 dlogz:50.926>10]

2173it [05:02, 10.06it/s, bound:934 nc: 33 ncall:6.6e+04 eff:3.3% logz=594928.98+/-0.84 dlogz:50.440>10]

2174it [05:02,  9.96it/s, bound:935 nc: 35 ncall:6.6e+04 eff:3.3% logz=594929.17+/-0.84 dlogz:50.201>10]

2176it [05:02, 10.38it/s, bound:936 nc: 30 ncall:6.6e+04 eff:3.3% logz=594929.47+/-0.84 dlogz:49.832>10]

2178it [05:02,  8.43it/s, bound:937 nc: 70 ncall:6.6e+04 eff:3.3% logz=594929.76+/-0.84 dlogz:49.525>10]

2179it [05:02,  8.69it/s, bound:938 nc: 35 ncall:6.6e+04 eff:3.3% logz=594929.94+/-0.84 dlogz:49.363>10]

2180it [05:02,  7.38it/s, bound:938 nc: 69 ncall:6.7e+04 eff:3.3% logz=594930.11+/-0.84 dlogz:61.030>10]

2182it [05:03,  8.26it/s, bound:939 nc: 35 ncall:6.7e+04 eff:3.3% logz=594930.44+/-0.84 dlogz:60.666>10]

2183it [05:03,  8.45it/s, bound:940 nc: 35 ncall:6.7e+04 eff:3.3% logz=594930.57+/-0.84 dlogz:60.496>10]

2184it [05:03,  8.67it/s, bound:940 nc: 35 ncall:6.7e+04 eff:3.3% logz=594930.71+/-0.84 dlogz:60.347>10]

2185it [05:03,  8.79it/s, bound:941 nc: 34 ncall:6.7e+04 eff:3.3% logz=594930.85+/-0.84 dlogz:60.196>10]

2186it [05:03,  8.94it/s, bound:941 nc: 35 ncall:6.7e+04 eff:3.3% logz=594931.00+/-0.84 dlogz:60.041>10]

2187it [05:03,  9.13it/s, bound:942 nc: 35 ncall:6.7e+04 eff:3.3% logz=594931.14+/-0.84 dlogz:59.884>10]

2189it [05:03,  9.50it/s, bound:943 nc: 32 ncall:6.7e+04 eff:3.3% logz=594931.54+/-0.84 dlogz:59.533>10]

2190it [05:04,  9.43it/s, bound:943 nc: 35 ncall:6.7e+04 eff:3.3% logz=594931.75+/-0.85 dlogz:59.303>10]

2191it [05:04,  9.30it/s, bound:944 nc: 34 ncall:6.7e+04 eff:3.3% logz=594931.95+/-0.85 dlogz:59.079>10]

2192it [05:04,  7.44it/s, bound:944 nc: 70 ncall:6.7e+04 eff:3.3% logz=594932.16+/-0.85 dlogz:58.867>10]

2193it [05:04,  7.92it/s, bound:945 nc: 35 ncall:6.7e+04 eff:3.3% logz=594932.36+/-0.85 dlogz:58.650>10]

2194it [05:04,  8.34it/s, bound:945 nc: 35 ncall:6.7e+04 eff:3.3% logz=594932.58+/-0.85 dlogz:58.440>10]

2195it [05:04,  6.84it/s, bound:946 nc: 69 ncall:6.7e+04 eff:3.3% logz=594932.81+/-0.85 dlogz:58.207>10]

2196it [05:04,  7.46it/s, bound:947 nc: 35 ncall:6.7e+04 eff:3.3% logz=594933.06+/-0.85 dlogz:57.963>10]

2197it [05:04,  8.00it/s, bound:947 nc: 35 ncall:6.7e+04 eff:3.3% logz=594933.40+/-0.85 dlogz:57.694>10]

2199it [05:05,  8.99it/s, bound:948 nc: 35 ncall:6.7e+04 eff:3.3% logz=594934.07+/-0.85 dlogz:56.981>10]

2200it [05:05,  9.12it/s, bound:949 nc: 35 ncall:6.7e+04 eff:3.3% logz=594934.36+/-0.86 dlogz:56.649>10]

2202it [05:05,  9.40it/s, bound:950 nc: 35 ncall:6.7e+04 eff:3.3% logz=594934.84+/-0.85 dlogz:56.084>10]

2203it [05:05,  9.44it/s, bound:950 nc: 35 ncall:6.7e+04 eff:3.3% logz=594935.12+/-0.85 dlogz:55.847>10]

2204it [05:05,  9.38it/s, bound:951 nc: 35 ncall:6.7e+04 eff:3.3% logz=594935.40+/-0.86 dlogz:55.554>10]

2206it [05:05,  9.92it/s, bound:952 nc: 34 ncall:6.8e+04 eff:3.3% logz=594935.95+/-0.86 dlogz:55.001>10]

2207it [05:05,  9.53it/s, bound:952 nc: 35 ncall:6.8e+04 eff:3.3% logz=594936.28+/-0.86 dlogz:54.683>10]

2208it [05:06,  9.14it/s, bound:953 nc: 35 ncall:6.8e+04 eff:3.3% logz=594936.56+/-0.86 dlogz:54.343>10]

2209it [05:06,  9.01it/s, bound:953 nc: 35 ncall:6.8e+04 eff:3.3% logz=594936.83+/-0.86 dlogz:54.047>10]

2210it [05:06,  9.24it/s, bound:954 nc: 34 ncall:6.8e+04 eff:3.3% logz=594937.06+/-0.86 dlogz:53.771>10]

2211it [05:06,  9.28it/s, bound:954 nc: 35 ncall:6.8e+04 eff:3.3% logz=594937.29+/-0.86 dlogz:53.522>10]

2212it [05:06,  9.26it/s, bound:955 nc: 35 ncall:6.8e+04 eff:3.3% logz=594937.50+/-0.86 dlogz:53.286>10]

2213it [05:06,  9.35it/s, bound:955 nc: 35 ncall:6.8e+04 eff:3.3% logz=594937.68+/-0.85 dlogz:53.062>10]

2214it [05:06,  9.38it/s, bound:956 nc: 35 ncall:6.8e+04 eff:3.3% logz=594937.87+/-0.85 dlogz:52.871>10]

2215it [05:06,  9.44it/s, bound:956 nc: 35 ncall:6.8e+04 eff:3.3% logz=594938.07+/-0.85 dlogz:52.667>10]

2216it [05:06,  9.55it/s, bound:957 nc: 35 ncall:6.8e+04 eff:3.3% logz=594938.25+/-0.85 dlogz:52.455>10]

2217it [05:07,  7.33it/s, bound:957 nc: 70 ncall:6.8e+04 eff:3.3% logz=594938.42+/-0.85 dlogz:52.257>10]

2218it [05:07,  7.84it/s, bound:958 nc: 35 ncall:6.8e+04 eff:3.3% logz=594938.56+/-0.85 dlogz:52.080>10]

2219it [05:07,  8.31it/s, bound:958 nc: 35 ncall:6.8e+04 eff:3.3% logz=594938.71+/-0.85 dlogz:51.922>10]

2220it [05:07,  8.60it/s, bound:959 nc: 35 ncall:6.8e+04 eff:3.3% logz=594938.84+/-0.85 dlogz:51.767>10]

2221it [05:07,  8.89it/s, bound:959 nc: 35 ncall:6.8e+04 eff:3.3% logz=594938.97+/-0.85 dlogz:51.615>10]

2222it [05:07,  9.01it/s, bound:960 nc: 35 ncall:6.8e+04 eff:3.3% logz=594939.10+/-0.85 dlogz:51.477>10]

2223it [05:08,  4.91it/s, bound:962 nc:138 ncall:6.8e+04 eff:3.3% logz=594939.23+/-0.85 dlogz:51.337>10]

2224it [05:08,  5.76it/s, bound:962 nc: 35 ncall:6.8e+04 eff:3.3% logz=594939.37+/-0.85 dlogz:51.192>10]

2226it [05:08,  7.38it/s, bound:963 nc: 30 ncall:6.8e+04 eff:3.3% logz=594939.68+/-0.85 dlogz:50.874>10]

2227it [05:08,  7.88it/s, bound:964 nc: 34 ncall:6.8e+04 eff:3.3% logz=594939.83+/-0.85 dlogz:50.704>10]

2229it [05:08,  8.70it/s, bound:965 nc: 35 ncall:6.8e+04 eff:3.3% logz=594940.09+/-0.85 dlogz:50.393>10]

2230it [05:08,  8.94it/s, bound:965 nc: 35 ncall:6.8e+04 eff:3.3% logz=594940.20+/-0.85 dlogz:50.258>10]

2231it [05:08,  9.02it/s, bound:966 nc: 35 ncall:6.9e+04 eff:3.3% logz=594940.35+/-0.85 dlogz:50.136>10]

2232it [05:09,  9.20it/s, bound:966 nc: 35 ncall:6.9e+04 eff:3.3% logz=594940.54+/-0.85 dlogz:49.973>10]

2233it [05:09,  9.30it/s, bound:967 nc: 35 ncall:6.9e+04 eff:3.3% logz=594940.73+/-0.85 dlogz:49.770>10]

2234it [05:09,  9.37it/s, bound:967 nc: 35 ncall:6.9e+04 eff:3.3% logz=594940.89+/-0.85 dlogz:49.573>10]

2235it [05:09,  9.23it/s, bound:968 nc: 35 ncall:6.9e+04 eff:3.3% logz=594941.05+/-0.85 dlogz:49.394>10]

2236it [05:09,  9.17it/s, bound:968 nc: 35 ncall:6.9e+04 eff:3.3% logz=594941.22+/-0.85 dlogz:49.219>10]

2237it [05:09,  9.22it/s, bound:969 nc: 35 ncall:6.9e+04 eff:3.3% logz=594941.38+/-0.85 dlogz:49.039>10]

2238it [05:09,  9.31it/s, bound:969 nc: 35 ncall:6.9e+04 eff:3.3% logz=594941.54+/-0.85 dlogz:48.867>10]

2239it [05:09,  9.31it/s, bound:970 nc: 35 ncall:6.9e+04 eff:3.3% logz=594941.72+/-0.85 dlogz:48.696>10]

2240it [05:09,  9.40it/s, bound:970 nc: 35 ncall:6.9e+04 eff:3.3% logz=594941.92+/-0.85 dlogz:48.502>10]

2242it [05:10,  9.97it/s, bound:971 nc: 35 ncall:6.9e+04 eff:3.3% logz=594942.24+/-0.85 dlogz:48.110>10]

2243it [05:10,  9.85it/s, bound:972 nc: 35 ncall:6.9e+04 eff:3.3% logz=594942.37+/-0.85 dlogz:47.949>10]

2244it [05:10,  9.77it/s, bound:972 nc: 35 ncall:6.9e+04 eff:3.3% logz=594942.49+/-0.85 dlogz:47.806>10]

2245it [05:10,  9.70it/s, bound:973 nc: 35 ncall:6.9e+04 eff:3.3% logz=594942.61+/-0.85 dlogz:47.671>10]

2246it [05:10,  9.56it/s, bound:973 nc: 35 ncall:6.9e+04 eff:3.3% logz=594942.73+/-0.85 dlogz:47.541>10]

2248it [05:10,  9.82it/s, bound:974 nc: 35 ncall:6.9e+04 eff:3.3% logz=594942.98+/-0.85 dlogz:47.278>10]

2250it [05:10,  9.95it/s, bound:975 nc: 35 ncall:6.9e+04 eff:3.3% logz=594943.27+/-0.85 dlogz:46.964>10]

2252it [05:11, 10.37it/s, bound:976 nc: 35 ncall:6.9e+04 eff:3.3% logz=594943.58+/-0.85 dlogz:46.656>10]

2254it [05:11, 10.10it/s, bound:977 nc: 35 ncall:6.9e+04 eff:3.3% logz=594943.95+/-0.86 dlogz:46.287>10]

2256it [05:11, 10.13it/s, bound:978 nc: 35 ncall:6.9e+04 eff:3.3% logz=594944.30+/-0.86 dlogz:45.903>10]

2258it [05:11, 10.22it/s, bound:979 nc: 28 ncall:6.9e+04 eff:3.3% logz=594944.71+/-0.86 dlogz:45.499>10]

2260it [05:11, 10.36it/s, bound:980 nc: 28 ncall:6.9e+04 eff:3.3% logz=594945.06+/-0.86 dlogz:45.093>10]

2262it [05:12, 10.10it/s, bound:981 nc: 35 ncall:7.0e+04 eff:3.3% logz=594945.40+/-0.86 dlogz:44.718>10]

2264it [05:12,  9.88it/s, bound:982 nc: 35 ncall:7.0e+04 eff:3.3% logz=594945.72+/-0.86 dlogz:44.357>10]

2266it [05:12,  9.93it/s, bound:983 nc: 35 ncall:7.0e+04 eff:3.3% logz=594946.00+/-0.86 dlogz:44.033>10]

2267it [05:12,  9.76it/s, bound:984 nc: 35 ncall:7.0e+04 eff:3.3% logz=594946.13+/-0.86 dlogz:43.884>10]

2268it [05:12,  9.72it/s, bound:984 nc: 35 ncall:7.0e+04 eff:3.3% logz=594946.25+/-0.86 dlogz:43.745>10]

2269it [05:12,  9.56it/s, bound:985 nc: 35 ncall:7.0e+04 eff:3.3% logz=594946.36+/-0.86 dlogz:43.615>10]

2271it [05:12,  9.69it/s, bound:986 nc: 31 ncall:7.0e+04 eff:3.3% logz=594946.57+/-0.86 dlogz:43.375>10]

2273it [05:13,  9.70it/s, bound:987 nc: 35 ncall:7.0e+04 eff:3.3% logz=594946.78+/-0.86 dlogz:43.138>10]

2274it [05:13,  9.72it/s, bound:987 nc: 35 ncall:7.0e+04 eff:3.3% logz=594946.89+/-0.86 dlogz:43.026>10]

2275it [05:13,  9.77it/s, bound:988 nc: 32 ncall:7.0e+04 eff:3.3% logz=594947.09+/-0.86 dlogz:42.904>10]

2276it [05:13,  7.78it/s, bound:988 nc: 70 ncall:7.0e+04 eff:3.2% logz=594947.33+/-0.86 dlogz:42.688>10]

2278it [05:13,  8.60it/s, bound:989 nc: 34 ncall:7.0e+04 eff:3.2% logz=594947.71+/-0.86 dlogz:42.218>10]

2279it [05:13,  8.84it/s, bound:990 nc: 35 ncall:7.0e+04 eff:3.2% logz=594947.90+/-0.86 dlogz:42.032>10]

2280it [05:14,  9.07it/s, bound:990 nc: 35 ncall:7.0e+04 eff:3.2% logz=594948.20+/-0.86 dlogz:41.823>10]

2281it [05:14,  7.22it/s, bound:991 nc: 70 ncall:7.0e+04 eff:3.2% logz=594948.54+/-0.87 dlogz:41.518>10]

2282it [05:14,  7.77it/s, bound:992 nc: 35 ncall:7.0e+04 eff:3.2% logz=594948.83+/-0.87 dlogz:41.167>10]

2283it [05:14,  8.18it/s, bound:992 nc: 35 ncall:7.0e+04 eff:3.2% logz=594949.07+/-0.87 dlogz:41.439>10]

2285it [05:14,  8.74it/s, bound:993 nc: 35 ncall:7.0e+04 eff:3.2% logz=594949.44+/-0.87 dlogz:40.975>10]

2287it [05:14,  9.55it/s, bound:994 nc: 30 ncall:7.0e+04 eff:3.2% logz=594949.75+/-0.87 dlogz:40.613>10]

2288it [05:15,  7.78it/s, bound:995 nc: 70 ncall:7.1e+04 eff:3.2% logz=594949.89+/-0.86 dlogz:40.451>10]

2289it [05:15,  8.09it/s, bound:996 nc: 35 ncall:7.1e+04 eff:3.2% logz=594950.02+/-0.86 dlogz:40.298>10]

2290it [05:15,  8.44it/s, bound:996 nc: 35 ncall:7.1e+04 eff:3.2% logz=594950.14+/-0.86 dlogz:40.162>10]

2291it [05:15,  8.67it/s, bound:997 nc: 35 ncall:7.1e+04 eff:3.2% logz=594950.25+/-0.86 dlogz:40.032>10]

2292it [05:15,  7.13it/s, bound:997 nc: 70 ncall:7.1e+04 eff:3.2% logz=594950.35+/-0.86 dlogz:39.906>10]

2293it [05:15,  7.64it/s, bound:998 nc: 35 ncall:7.1e+04 eff:3.2% logz=594950.45+/-0.86 dlogz:39.791>10]

2294it [05:15,  8.07it/s, bound:998 nc: 35 ncall:7.1e+04 eff:3.2% logz=594950.55+/-0.86 dlogz:39.684>10]

2295it [05:15,  8.29it/s, bound:999 nc: 35 ncall:7.1e+04 eff:3.2% logz=594950.64+/-0.86 dlogz:39.567>10]

2296it [05:15,  8.66it/s, bound:999 nc: 35 ncall:7.1e+04 eff:3.2% logz=594950.74+/-0.86 dlogz:39.461>10]

2297it [05:16,  8.96it/s, bound:1000 nc: 35 ncall:7.1e+04 eff:3.2% logz=594950.85+/-0.86 dlogz:39.350>10]

2299it [05:16,  9.27it/s, bound:1001 nc: 35 ncall:7.1e+04 eff:3.2% logz=594951.06+/-0.86 dlogz:39.117>10]

2300it [05:16,  9.31it/s, bound:1001 nc: 35 ncall:7.1e+04 eff:3.2% logz=594951.20+/-0.86 dlogz:38.991>10]

2301it [05:16,  9.37it/s, bound:1002 nc: 35 ncall:7.1e+04 eff:3.2% logz=594951.34+/-0.86 dlogz:38.847>10]

2302it [05:16,  9.37it/s, bound:1002 nc: 35 ncall:7.1e+04 eff:3.2% logz=594951.48+/-0.86 dlogz:38.693>10]

2303it [05:16,  9.49it/s, bound:1003 nc: 35 ncall:7.1e+04 eff:3.2% logz=594951.62+/-0.86 dlogz:38.538>10]

2304it [05:16,  9.47it/s, bound:1003 nc: 35 ncall:7.1e+04 eff:3.2% logz=594951.75+/-0.86 dlogz:38.390>10]

2305it [05:16,  9.47it/s, bound:1004 nc: 35 ncall:7.1e+04 eff:3.2% logz=594951.94+/-0.86 dlogz:38.241>10]

2306it [05:17,  9.47it/s, bound:1004 nc: 35 ncall:7.1e+04 eff:3.2% logz=594952.15+/-0.86 dlogz:38.045>10]

2307it [05:17,  9.47it/s, bound:1005 nc: 35 ncall:7.1e+04 eff:3.2% logz=594952.35+/-0.87 dlogz:37.816>10]

2308it [05:17,  9.37it/s, bound:1005 nc: 35 ncall:7.1e+04 eff:3.2% logz=594952.54+/-0.87 dlogz:37.603>10]

2309it [05:17,  9.25it/s, bound:1006 nc: 35 ncall:7.1e+04 eff:3.2% logz=594952.70+/-0.87 dlogz:37.409>10]

2310it [05:17,  9.31it/s, bound:1006 nc: 35 ncall:7.1e+04 eff:3.2% logz=594952.87+/-0.87 dlogz:37.230>10]

2311it [05:17,  9.37it/s, bound:1007 nc: 35 ncall:7.1e+04 eff:3.2% logz=594953.04+/-0.87 dlogz:37.045>10]

2312it [05:17,  7.27it/s, bound:1007 nc: 70 ncall:7.1e+04 eff:3.2% logz=594953.19+/-0.87 dlogz:36.862>10]

2313it [05:17,  7.90it/s, bound:1008 nc: 33 ncall:7.1e+04 eff:3.2% logz=594953.34+/-0.87 dlogz:36.703>10]

2314it [05:17,  8.30it/s, bound:1008 nc: 35 ncall:7.2e+04 eff:3.2% logz=594953.48+/-0.87 dlogz:36.545>10]

2315it [05:18,  6.82it/s, bound:1009 nc: 70 ncall:7.2e+04 eff:3.2% logz=594953.62+/-0.87 dlogz:36.387>10]

2317it [05:18,  8.02it/s, bound:1010 nc: 35 ncall:7.2e+04 eff:3.2% logz=594953.90+/-0.87 dlogz:36.082>10]

2318it [05:18,  8.39it/s, bound:1011 nc: 35 ncall:7.2e+04 eff:3.2% logz=594954.04+/-0.87 dlogz:35.929>10]

2319it [05:18,  6.88it/s, bound:1011 nc: 70 ncall:7.2e+04 eff:3.2% logz=594954.17+/-0.87 dlogz:35.777>10]

2320it [05:18,  7.41it/s, bound:1012 nc: 35 ncall:7.2e+04 eff:3.2% logz=594954.30+/-0.87 dlogz:35.640>10]

2321it [05:18,  7.87it/s, bound:1012 nc: 35 ncall:7.2e+04 eff:3.2% logz=594954.43+/-0.87 dlogz:35.491>10]

2322it [05:19,  8.25it/s, bound:1013 nc: 35 ncall:7.2e+04 eff:3.2% logz=594954.55+/-0.87 dlogz:35.356>10]

2323it [05:19,  8.64it/s, bound:1013 nc: 35 ncall:7.2e+04 eff:3.2% logz=594954.69+/-0.87 dlogz:35.215>10]

2324it [05:19,  8.93it/s, bound:1014 nc: 35 ncall:7.2e+04 eff:3.2% logz=594954.82+/-0.87 dlogz:35.066>10]

2325it [05:19,  9.15it/s, bound:1014 nc: 35 ncall:7.2e+04 eff:3.2% logz=594954.95+/-0.87 dlogz:34.925>10]

2327it [05:19,  9.80it/s, bound:1015 nc: 29 ncall:7.2e+04 eff:3.2% logz=594955.25+/-0.87 dlogz:34.621>10]

2328it [05:19,  9.65it/s, bound:1016 nc: 35 ncall:7.2e+04 eff:3.2% logz=594955.39+/-0.87 dlogz:34.455>10]

2330it [05:19,  9.85it/s, bound:1017 nc: 35 ncall:7.2e+04 eff:3.2% logz=594955.67+/-0.87 dlogz:34.161>10]

2331it [05:19,  9.76it/s, bound:1017 nc: 35 ncall:7.2e+04 eff:3.2% logz=594955.82+/-0.87 dlogz:33.998>10]

2332it [05:20,  7.67it/s, bound:1018 nc: 70 ncall:7.2e+04 eff:3.2% logz=594955.95+/-0.87 dlogz:33.837>10]

2333it [05:20,  7.99it/s, bound:1019 nc: 35 ncall:7.2e+04 eff:3.2% logz=594956.07+/-0.87 dlogz:33.692>10]

2334it [05:20,  8.34it/s, bound:1019 nc: 35 ncall:7.2e+04 eff:3.2% logz=594956.19+/-0.87 dlogz:33.559>10]

2335it [05:20,  8.30it/s, bound:1020 nc: 35 ncall:7.2e+04 eff:3.2% logz=594956.30+/-0.87 dlogz:33.432>10]

2336it [05:20,  8.59it/s, bound:1020 nc: 35 ncall:7.2e+04 eff:3.2% logz=594956.45+/-0.87 dlogz:33.307>10]

2337it [05:20,  8.83it/s, bound:1021 nc: 35 ncall:7.2e+04 eff:3.2% logz=594956.64+/-0.87 dlogz:33.147>10]

2339it [05:20,  9.33it/s, bound:1022 nc: 35 ncall:7.2e+04 eff:3.2% logz=594957.00+/-0.87 dlogz:32.746>10]

2340it [05:21,  9.34it/s, bound:1022 nc: 35 ncall:7.3e+04 eff:3.2% logz=594957.16+/-0.87 dlogz:32.556>10]

2341it [05:21,  7.48it/s, bound:1023 nc: 70 ncall:7.3e+04 eff:3.2% logz=594957.30+/-0.87 dlogz:32.385>10]

2342it [05:21,  7.97it/s, bound:1024 nc: 35 ncall:7.3e+04 eff:3.2% logz=594957.42+/-0.87 dlogz:32.236>10]

2343it [05:21,  8.23it/s, bound:1024 nc: 35 ncall:7.3e+04 eff:3.2% logz=594957.54+/-0.87 dlogz:32.102>10]

2344it [05:21,  8.61it/s, bound:1025 nc: 35 ncall:7.3e+04 eff:3.2% logz=594957.67+/-0.87 dlogz:31.972>10]

2345it [05:21,  8.85it/s, bound:1025 nc: 35 ncall:7.3e+04 eff:3.2% logz=594957.81+/-0.87 dlogz:31.829>10]

2346it [05:21,  7.14it/s, bound:1026 nc: 70 ncall:7.3e+04 eff:3.2% logz=594957.95+/-0.87 dlogz:31.671>10]

2347it [05:21,  7.73it/s, bound:1027 nc: 35 ncall:7.3e+04 eff:3.2% logz=594958.09+/-0.87 dlogz:31.518>10]

2348it [05:22,  8.21it/s, bound:1027 nc: 35 ncall:7.3e+04 eff:3.2% logz=594958.21+/-0.87 dlogz:31.369>10]

2349it [05:22,  8.64it/s, bound:1028 nc: 35 ncall:7.3e+04 eff:3.2% logz=594958.33+/-0.87 dlogz:31.237>10]

2350it [05:22,  8.99it/s, bound:1028 nc: 35 ncall:7.3e+04 eff:3.2% logz=594958.46+/-0.87 dlogz:31.101>10]

2351it [05:22,  9.07it/s, bound:1029 nc: 35 ncall:7.3e+04 eff:3.2% logz=594958.60+/-0.87 dlogz:30.958>10]

2352it [05:22,  7.22it/s, bound:1029 nc: 70 ncall:7.3e+04 eff:3.2% logz=594958.74+/-0.87 dlogz:30.814>10]

2353it [05:22,  7.84it/s, bound:1030 nc: 35 ncall:7.3e+04 eff:3.2% logz=594958.90+/-0.87 dlogz:30.659>10]

2355it [05:23,  6.10it/s, bound:1032 nc:105 ncall:7.3e+04 eff:3.2% logz=594959.26+/-0.87 dlogz:30.290>10]

2356it [05:23,  6.66it/s, bound:1032 nc: 35 ncall:7.3e+04 eff:3.2% logz=594959.41+/-0.87 dlogz:30.103>10]

2357it [05:23,  7.18it/s, bound:1033 nc: 35 ncall:7.3e+04 eff:3.2% logz=594959.56+/-0.87 dlogz:29.933>10]

2358it [05:23,  7.70it/s, bound:1033 nc: 35 ncall:7.3e+04 eff:3.2% logz=594959.70+/-0.87 dlogz:29.776>10]

2359it [05:23,  8.16it/s, bound:1034 nc: 35 ncall:7.3e+04 eff:3.2% logz=594959.83+/-0.87 dlogz:29.623>10]

2360it [05:23,  6.76it/s, bound:1034 nc: 70 ncall:7.3e+04 eff:3.2% logz=594959.95+/-0.87 dlogz:29.482>10]

2362it [05:23,  8.05it/s, bound:1035 nc: 35 ncall:7.3e+04 eff:3.2% logz=594960.19+/-0.87 dlogz:29.209>10]

2363it [05:24,  8.33it/s, bound:1036 nc: 35 ncall:7.4e+04 eff:3.2% logz=594960.31+/-0.87 dlogz:29.079>10]

2364it [05:24,  8.59it/s, bound:1036 nc: 35 ncall:7.4e+04 eff:3.2% logz=594960.43+/-0.87 dlogz:28.953>10]

2365it [05:24,  8.80it/s, bound:1037 nc: 35 ncall:7.4e+04 eff:3.2% logz=594960.55+/-0.87 dlogz:28.823>10]

2366it [05:24,  9.06it/s, bound:1037 nc: 35 ncall:7.4e+04 eff:3.2% logz=594960.68+/-0.87 dlogz:28.684>10]

2367it [05:24,  7.26it/s, bound:1038 nc: 70 ncall:7.4e+04 eff:3.2% logz=594960.81+/-0.87 dlogz:28.542>10]

2368it [05:24,  7.78it/s, bound:1039 nc: 35 ncall:7.4e+04 eff:3.2% logz=594960.94+/-0.87 dlogz:28.402>10]

2369it [05:24,  8.18it/s, bound:1039 nc: 35 ncall:7.4e+04 eff:3.2% logz=594961.07+/-0.87 dlogz:28.259>10]

2370it [05:24,  8.60it/s, bound:1040 nc: 35 ncall:7.4e+04 eff:3.2% logz=594961.18+/-0.87 dlogz:28.118>10]

2371it [05:24,  8.87it/s, bound:1040 nc: 35 ncall:7.4e+04 eff:3.2% logz=594961.29+/-0.87 dlogz:27.991>10]

2372it [05:25,  9.14it/s, bound:1041 nc: 31 ncall:7.4e+04 eff:3.2% logz=594961.42+/-0.87 dlogz:27.869>10]

2374it [05:25,  9.50it/s, bound:1042 nc: 34 ncall:7.4e+04 eff:3.2% logz=594961.67+/-0.87 dlogz:27.585>10]

2375it [05:25,  9.53it/s, bound:1042 nc: 35 ncall:7.4e+04 eff:3.2% logz=594961.78+/-0.87 dlogz:27.450>10]

2376it [05:25,  9.48it/s, bound:1043 nc: 35 ncall:7.4e+04 eff:3.2% logz=594961.88+/-0.87 dlogz:27.328>10]

2377it [05:25,  9.52it/s, bound:1043 nc: 35 ncall:7.4e+04 eff:3.2% logz=594961.98+/-0.87 dlogz:27.214>10]

2378it [05:25,  9.49it/s, bound:1044 nc: 35 ncall:7.4e+04 eff:3.2% logz=594962.07+/-0.87 dlogz:27.105>10]

2379it [05:25,  7.33it/s, bound:1044 nc: 70 ncall:7.4e+04 eff:3.2% logz=594962.15+/-0.87 dlogz:27.003>10]

2380it [05:26,  6.62it/s, bound:1045 nc: 61 ncall:7.4e+04 eff:3.2% logz=594962.24+/-0.87 dlogz:26.908>10]

2381it [05:26,  7.29it/s, bound:1046 nc: 35 ncall:7.4e+04 eff:3.2% logz=594962.33+/-0.87 dlogz:26.811>10]

2382it [05:26,  6.26it/s, bound:1046 nc: 70 ncall:7.4e+04 eff:3.2% logz=594962.44+/-0.87 dlogz:26.703>10]

2383it [05:26,  6.98it/s, bound:1047 nc: 35 ncall:7.4e+04 eff:3.2% logz=594962.53+/-0.87 dlogz:26.589>10]

2384it [05:26,  7.61it/s, bound:1047 nc: 35 ncall:7.4e+04 eff:3.2% logz=594962.63+/-0.87 dlogz:26.480>10]

2385it [05:26,  8.08it/s, bound:1048 nc: 35 ncall:7.4e+04 eff:3.2% logz=594962.74+/-0.87 dlogz:26.367>10]

2386it [05:26,  6.68it/s, bound:1048 nc: 70 ncall:7.4e+04 eff:3.2% logz=594962.84+/-0.87 dlogz:26.250>10]

2387it [05:27,  7.39it/s, bound:1049 nc: 35 ncall:7.5e+04 eff:3.2% logz=594962.94+/-0.87 dlogz:26.134>10]

2388it [05:27,  7.89it/s, bound:1049 nc: 35 ncall:7.5e+04 eff:3.2% logz=594963.03+/-0.87 dlogz:26.022>10]

2389it [05:27,  8.17it/s, bound:1050 nc: 35 ncall:7.5e+04 eff:3.2% logz=594963.12+/-0.87 dlogz:25.920>10]

2390it [05:27,  8.59it/s, bound:1050 nc: 35 ncall:7.5e+04 eff:3.2% logz=594963.22+/-0.87 dlogz:25.818>10]

2391it [05:27,  8.80it/s, bound:1051 nc: 35 ncall:7.5e+04 eff:3.2% logz=594963.32+/-0.87 dlogz:25.708>10]

2392it [05:27,  9.00it/s, bound:1051 nc: 35 ncall:7.5e+04 eff:3.2% logz=594963.41+/-0.87 dlogz:25.596>10]

2393it [05:27,  9.21it/s, bound:1052 nc: 35 ncall:7.5e+04 eff:3.2% logz=594963.50+/-0.87 dlogz:25.488>10]

2394it [05:27,  9.37it/s, bound:1052 nc: 35 ncall:7.5e+04 eff:3.2% logz=594963.60+/-0.87 dlogz:25.387>10]

2395it [05:27,  9.46it/s, bound:1053 nc: 35 ncall:7.5e+04 eff:3.2% logz=594963.70+/-0.87 dlogz:25.279>10]

2396it [05:27,  9.33it/s, bound:1053 nc: 35 ncall:7.5e+04 eff:3.2% logz=594963.80+/-0.87 dlogz:25.165>10]

2397it [05:28,  9.37it/s, bound:1054 nc: 35 ncall:7.5e+04 eff:3.2% logz=594963.91+/-0.87 dlogz:25.051>10]

2398it [05:28,  9.51it/s, bound:1054 nc: 35 ncall:7.5e+04 eff:3.2% logz=594964.01+/-0.87 dlogz:24.930>10]

2399it [05:28,  9.59it/s, bound:1055 nc: 35 ncall:7.5e+04 eff:3.2% logz=594964.10+/-0.87 dlogz:24.819>10]

2400it [05:28,  9.56it/s, bound:1055 nc: 35 ncall:7.5e+04 eff:3.2% logz=594964.19+/-0.87 dlogz:24.713>10]

2401it [05:28,  9.58it/s, bound:1056 nc: 34 ncall:7.5e+04 eff:3.2% logz=594964.29+/-0.87 dlogz:24.612>10]

2402it [05:28,  9.62it/s, bound:1056 nc: 35 ncall:7.5e+04 eff:3.2% logz=594964.40+/-0.87 dlogz:24.501>10]

2403it [05:28,  9.55it/s, bound:1057 nc: 35 ncall:7.5e+04 eff:3.2% logz=594964.50+/-0.88 dlogz:24.379>10]

2404it [05:28,  9.53it/s, bound:1057 nc: 35 ncall:7.5e+04 eff:3.2% logz=594964.60+/-0.88 dlogz:24.262>10]

2405it [05:28,  9.48it/s, bound:1058 nc: 35 ncall:7.5e+04 eff:3.2% logz=594964.70+/-0.88 dlogz:24.149>10]

2406it [05:29,  9.51it/s, bound:1058 nc: 35 ncall:7.5e+04 eff:3.2% logz=594964.80+/-0.88 dlogz:24.038>10]

2407it [05:29,  9.58it/s, bound:1059 nc: 35 ncall:7.5e+04 eff:3.2% logz=594964.89+/-0.88 dlogz:23.929>10]

2408it [05:29,  9.56it/s, bound:1059 nc: 35 ncall:7.5e+04 eff:3.2% logz=594964.97+/-0.88 dlogz:23.826>10]

2409it [05:29,  9.58it/s, bound:1060 nc: 35 ncall:7.5e+04 eff:3.2% logz=594965.05+/-0.88 dlogz:23.729>10]

2410it [05:29,  9.68it/s, bound:1060 nc: 34 ncall:7.5e+04 eff:3.2% logz=594965.13+/-0.88 dlogz:23.638>10]

2411it [05:29,  9.63it/s, bound:1061 nc: 35 ncall:7.5e+04 eff:3.2% logz=594965.21+/-0.88 dlogz:23.546>10]

2412it [05:29,  9.67it/s, bound:1061 nc: 35 ncall:7.5e+04 eff:3.2% logz=594965.28+/-0.88 dlogz:23.457>10]

2413it [05:29,  9.61it/s, bound:1062 nc: 34 ncall:7.5e+04 eff:3.2% logz=594965.36+/-0.88 dlogz:23.369>10]

2414it [05:29,  9.54it/s, bound:1062 nc: 35 ncall:7.5e+04 eff:3.2% logz=594965.44+/-0.88 dlogz:23.278>10]

2415it [05:29,  9.48it/s, bound:1063 nc: 34 ncall:7.5e+04 eff:3.2% logz=594965.51+/-0.88 dlogz:23.189>10]

2416it [05:30,  9.24it/s, bound:1063 nc: 35 ncall:7.6e+04 eff:3.2% logz=594965.58+/-0.87 dlogz:23.106>10]

2417it [05:30,  9.23it/s, bound:1064 nc: 35 ncall:7.6e+04 eff:3.2% logz=594965.64+/-0.87 dlogz:23.027>10]

2418it [05:30,  9.29it/s, bound:1064 nc: 35 ncall:7.6e+04 eff:3.2% logz=594965.70+/-0.87 dlogz:22.952>10]

2419it [05:30,  9.42it/s, bound:1065 nc: 35 ncall:7.6e+04 eff:3.2% logz=594965.76+/-0.87 dlogz:22.879>10]

2420it [05:30,  7.30it/s, bound:1065 nc: 70 ncall:7.6e+04 eff:3.2% logz=594965.82+/-0.87 dlogz:22.809>10]

2421it [05:30,  7.86it/s, bound:1066 nc: 35 ncall:7.6e+04 eff:3.2% logz=594965.87+/-0.87 dlogz:22.737>10]

2422it [05:30,  8.21it/s, bound:1066 nc: 35 ncall:7.6e+04 eff:3.2% logz=594965.93+/-0.87 dlogz:22.665>10]

2423it [05:31,  6.74it/s, bound:1067 nc: 70 ncall:7.6e+04 eff:3.2% logz=594965.99+/-0.87 dlogz:22.595>10]

2424it [05:31,  7.33it/s, bound:1068 nc: 35 ncall:7.6e+04 eff:3.2% logz=594966.05+/-0.87 dlogz:22.527>10]

2425it [05:31,  7.79it/s, bound:1068 nc: 35 ncall:7.6e+04 eff:3.2% logz=594966.12+/-0.87 dlogz:22.449>10]

2426it [05:31,  8.21it/s, bound:1069 nc: 34 ncall:7.6e+04 eff:3.2% logz=594966.18+/-0.87 dlogz:22.375>10]

2427it [05:31,  8.44it/s, bound:1069 nc: 35 ncall:7.6e+04 eff:3.2% logz=594966.24+/-0.87 dlogz:22.302>10]

2428it [05:31,  6.83it/s, bound:1070 nc: 70 ncall:7.6e+04 eff:3.2% logz=594966.30+/-0.87 dlogz:22.226>10]

2429it [05:31,  7.37it/s, bound:1071 nc: 35 ncall:7.6e+04 eff:3.2% logz=594966.37+/-0.87 dlogz:22.149>10]

2430it [05:31,  7.97it/s, bound:1071 nc: 35 ncall:7.6e+04 eff:3.2% logz=594966.45+/-0.87 dlogz:22.071>10]

2431it [05:31,  8.41it/s, bound:1072 nc: 35 ncall:7.6e+04 eff:3.2% logz=594966.53+/-0.87 dlogz:21.983>10]

2432it [05:32,  8.75it/s, bound:1072 nc: 35 ncall:7.6e+04 eff:3.2% logz=594966.62+/-0.88 dlogz:21.885>10]

2433it [05:32,  8.99it/s, bound:1073 nc: 35 ncall:7.6e+04 eff:3.2% logz=594966.71+/-0.88 dlogz:21.785>10]

2434it [05:32,  9.08it/s, bound:1073 nc: 35 ncall:7.6e+04 eff:3.2% logz=594966.79+/-0.88 dlogz:21.685>10]

2435it [05:32,  9.04it/s, bound:1074 nc: 35 ncall:7.6e+04 eff:3.2% logz=594966.87+/-0.88 dlogz:21.587>10]

2436it [05:32,  7.11it/s, bound:1074 nc: 70 ncall:7.6e+04 eff:3.2% logz=594966.95+/-0.88 dlogz:21.493>10]

2437it [05:32,  7.68it/s, bound:1075 nc: 35 ncall:7.6e+04 eff:3.2% logz=594967.02+/-0.88 dlogz:21.403>10]

2438it [05:32,  6.46it/s, bound:1075 nc: 70 ncall:7.6e+04 eff:3.2% logz=594967.10+/-0.88 dlogz:21.317>10]

2439it [05:33,  7.15it/s, bound:1076 nc: 35 ncall:7.7e+04 eff:3.2% logz=594967.17+/-0.88 dlogz:21.234>10]

2440it [05:33,  7.72it/s, bound:1076 nc: 35 ncall:7.7e+04 eff:3.2% logz=594967.25+/-0.88 dlogz:21.144>10]

2441it [05:33,  8.21it/s, bound:1077 nc: 35 ncall:7.7e+04 eff:3.2% logz=594967.33+/-0.88 dlogz:21.051>10]

2442it [05:33,  8.62it/s, bound:1077 nc: 35 ncall:7.7e+04 eff:3.2% logz=594967.40+/-0.88 dlogz:20.963>10]

2443it [05:33,  8.83it/s, bound:1078 nc: 35 ncall:7.7e+04 eff:3.2% logz=594967.48+/-0.88 dlogz:20.876>10]

2444it [05:33,  7.08it/s, bound:1078 nc: 70 ncall:7.7e+04 eff:3.2% logz=594967.56+/-0.88 dlogz:20.784>10]

2445it [05:33,  7.66it/s, bound:1079 nc: 35 ncall:7.7e+04 eff:3.2% logz=594967.65+/-0.88 dlogz:20.690>10]

2446it [05:33,  8.05it/s, bound:1079 nc: 35 ncall:7.7e+04 eff:3.2% logz=594967.74+/-0.88 dlogz:20.593>10]

2447it [05:33,  8.47it/s, bound:1080 nc: 35 ncall:7.7e+04 eff:3.2% logz=594967.82+/-0.88 dlogz:20.493>10]

2448it [05:34,  8.73it/s, bound:1080 nc: 35 ncall:7.7e+04 eff:3.2% logz=594967.91+/-0.88 dlogz:20.394>10]

2449it [05:34,  8.88it/s, bound:1081 nc: 35 ncall:7.7e+04 eff:3.2% logz=594967.99+/-0.88 dlogz:20.296>10]

2451it [05:34,  9.27it/s, bound:1082 nc: 35 ncall:7.7e+04 eff:3.2% logz=594968.16+/-0.88 dlogz:20.104>10]

2452it [05:34,  9.40it/s, bound:1082 nc: 35 ncall:7.7e+04 eff:3.2% logz=594968.24+/-0.88 dlogz:20.009>10]

2453it [05:34,  9.49it/s, bound:1083 nc: 35 ncall:7.7e+04 eff:3.2% logz=594968.32+/-0.88 dlogz:19.915>10]

2454it [05:34,  9.52it/s, bound:1083 nc: 35 ncall:7.7e+04 eff:3.2% logz=594968.40+/-0.88 dlogz:19.823>10]

2455it [05:34,  9.59it/s, bound:1084 nc: 35 ncall:7.7e+04 eff:3.2% logz=594968.48+/-0.88 dlogz:19.729>10]

2456it [05:34,  9.68it/s, bound:1084 nc: 35 ncall:7.7e+04 eff:3.2% logz=594968.56+/-0.88 dlogz:19.637>10]

2457it [05:35,  9.76it/s, bound:1085 nc: 35 ncall:7.7e+04 eff:3.2% logz=594968.63+/-0.88 dlogz:19.548>10]

2459it [05:35, 10.21it/s, bound:1086 nc: 35 ncall:7.7e+04 eff:3.2% logz=594968.77+/-0.88 dlogz:19.546>10]

2461it [05:35, 10.07it/s, bound:1087 nc: 35 ncall:7.7e+04 eff:3.2% logz=594968.91+/-0.88 dlogz:19.383>10]

2463it [05:35,  9.97it/s, bound:1088 nc: 34 ncall:7.7e+04 eff:3.2% logz=594969.05+/-0.88 dlogz:19.220>10]

2464it [05:35,  9.90it/s, bound:1088 nc: 35 ncall:7.7e+04 eff:3.2% logz=594969.13+/-0.88 dlogz:19.133>10]

2465it [05:35,  9.85it/s, bound:1089 nc: 35 ncall:7.7e+04 eff:3.2% logz=594969.21+/-0.88 dlogz:19.044>10]

2466it [05:35,  9.69it/s, bound:1089 nc: 35 ncall:7.7e+04 eff:3.2% logz=594969.29+/-0.88 dlogz:18.955>10]

2467it [05:36,  9.49it/s, bound:1090 nc: 35 ncall:7.8e+04 eff:3.2% logz=594969.37+/-0.88 dlogz:18.862>10]

2468it [05:36,  9.48it/s, bound:1090 nc: 35 ncall:7.8e+04 eff:3.2% logz=594969.44+/-0.88 dlogz:18.768>10]

2469it [05:36,  9.56it/s, bound:1091 nc: 35 ncall:7.8e+04 eff:3.2% logz=594969.52+/-0.88 dlogz:18.680>10]

2471it [05:36,  9.85it/s, bound:1092 nc: 35 ncall:7.8e+04 eff:3.2% logz=594969.65+/-0.88 dlogz:18.514>10]

2472it [05:36,  9.83it/s, bound:1092 nc: 35 ncall:7.8e+04 eff:3.2% logz=594969.72+/-0.88 dlogz:18.434>10]

2473it [05:36,  7.63it/s, bound:1093 nc: 70 ncall:7.8e+04 eff:3.2% logz=594969.79+/-0.88 dlogz:18.351>10]

2474it [05:36,  8.07it/s, bound:1094 nc: 35 ncall:7.8e+04 eff:3.2% logz=594969.86+/-0.88 dlogz:18.267>10]

2475it [05:36,  8.28it/s, bound:1094 nc: 35 ncall:7.8e+04 eff:3.2% logz=594969.93+/-0.88 dlogz:18.187>10]

2476it [05:37,  8.63it/s, bound:1095 nc: 35 ncall:7.8e+04 eff:3.2% logz=594969.99+/-0.88 dlogz:18.110>10]

2477it [05:37,  8.90it/s, bound:1095 nc: 35 ncall:7.8e+04 eff:3.2% logz=594970.05+/-0.88 dlogz:18.037>10]

2478it [05:37,  9.10it/s, bound:1096 nc: 35 ncall:7.8e+04 eff:3.2% logz=594970.10+/-0.88 dlogz:17.966>10]

2479it [05:37,  9.26it/s, bound:1096 nc: 35 ncall:7.8e+04 eff:3.2% logz=594970.15+/-0.88 dlogz:17.899>10]

2480it [05:37,  9.21it/s, bound:1097 nc: 35 ncall:7.8e+04 eff:3.2% logz=594970.21+/-0.88 dlogz:17.833>10]

2481it [05:37,  9.38it/s, bound:1097 nc: 35 ncall:7.8e+04 eff:3.2% logz=594970.27+/-0.88 dlogz:17.764>10]

2482it [05:37,  9.41it/s, bound:1098 nc: 35 ncall:7.8e+04 eff:3.2% logz=594970.32+/-0.88 dlogz:17.694>10]

2483it [05:37,  9.43it/s, bound:1098 nc: 35 ncall:7.8e+04 eff:3.2% logz=594970.38+/-0.88 dlogz:17.626>10]

2484it [05:37,  9.53it/s, bound:1099 nc: 35 ncall:7.8e+04 eff:3.2% logz=594970.43+/-0.88 dlogz:17.560>10]

2485it [05:38,  9.46it/s, bound:1099 nc: 35 ncall:7.8e+04 eff:3.2% logz=594970.48+/-0.88 dlogz:17.494>10]

2486it [05:38,  9.49it/s, bound:1100 nc: 35 ncall:7.8e+04 eff:3.2% logz=594970.53+/-0.88 dlogz:17.429>10]

2487it [05:38,  9.48it/s, bound:1100 nc: 35 ncall:7.8e+04 eff:3.2% logz=594970.58+/-0.88 dlogz:17.367>10]

2488it [05:38,  9.27it/s, bound:1101 nc: 35 ncall:7.8e+04 eff:3.2% logz=594970.64+/-0.88 dlogz:17.303>10]

2489it [05:38,  7.25it/s, bound:1101 nc: 70 ncall:7.8e+04 eff:3.2% logz=594970.70+/-0.88 dlogz:17.235>10]

2490it [05:38,  7.82it/s, bound:1102 nc: 35 ncall:7.8e+04 eff:3.2% logz=594970.75+/-0.88 dlogz:17.165>10]

2491it [05:38,  8.17it/s, bound:1102 nc: 35 ncall:7.8e+04 eff:3.2% logz=594970.82+/-0.88 dlogz:17.096>10]

2492it [05:38,  8.57it/s, bound:1103 nc: 35 ncall:7.8e+04 eff:3.2% logz=594970.89+/-0.88 dlogz:17.018>10]

2493it [05:39,  5.62it/s, bound:1104 nc:105 ncall:7.9e+04 eff:3.2% logz=594970.96+/-0.88 dlogz:16.933>10]

2494it [05:39,  6.36it/s, bound:1104 nc: 35 ncall:7.9e+04 eff:3.2% logz=594971.02+/-0.88 dlogz:16.853>10]

2495it [05:39,  7.02it/s, bound:1105 nc: 35 ncall:7.9e+04 eff:3.2% logz=594971.09+/-0.88 dlogz:16.775>10]

2496it [05:39,  7.64it/s, bound:1105 nc: 35 ncall:7.9e+04 eff:3.2% logz=594971.15+/-0.88 dlogz:16.698>10]

2497it [05:39,  8.01it/s, bound:1106 nc: 35 ncall:7.9e+04 eff:3.2% logz=594971.22+/-0.88 dlogz:16.621>10]

2498it [05:39,  8.40it/s, bound:1106 nc: 35 ncall:7.9e+04 eff:3.2% logz=594971.28+/-0.88 dlogz:16.544>10]

2499it [05:39,  8.67it/s, bound:1107 nc: 35 ncall:7.9e+04 eff:3.2% logz=594971.35+/-0.88 dlogz:16.467>10]

2500it [05:39,  8.95it/s, bound:1107 nc: 35 ncall:7.9e+04 eff:3.2% logz=594971.42+/-0.88 dlogz:16.390>10]

2501it [05:40,  8.98it/s, bound:1108 nc: 35 ncall:7.9e+04 eff:3.2% logz=594971.48+/-0.88 dlogz:16.310>10]

2502it [05:40,  9.08it/s, bound:1108 nc: 35 ncall:7.9e+04 eff:3.2% logz=594971.55+/-0.89 dlogz:16.228>10]

2503it [05:40,  9.17it/s, bound:1109 nc: 35 ncall:7.9e+04 eff:3.2% logz=594971.61+/-0.89 dlogz:16.151>10]

2504it [05:40,  9.38it/s, bound:1109 nc: 35 ncall:7.9e+04 eff:3.2% logz=594971.67+/-0.89 dlogz:16.076>10]

2505it [05:40,  9.47it/s, bound:1110 nc: 35 ncall:7.9e+04 eff:3.2% logz=594971.73+/-0.89 dlogz:16.005>10]

2506it [05:40,  9.47it/s, bound:1110 nc: 35 ncall:7.9e+04 eff:3.2% logz=594971.79+/-0.89 dlogz:15.932>10]

2507it [05:40,  9.26it/s, bound:1111 nc: 35 ncall:7.9e+04 eff:3.2% logz=594971.85+/-0.89 dlogz:15.858>10]

2508it [05:40,  9.38it/s, bound:1111 nc: 35 ncall:7.9e+04 eff:3.2% logz=594971.91+/-0.89 dlogz:15.787>10]

2509it [05:40,  9.41it/s, bound:1112 nc: 35 ncall:7.9e+04 eff:3.2% logz=594971.97+/-0.89 dlogz:15.718>10]

2510it [05:41,  9.28it/s, bound:1112 nc: 35 ncall:7.9e+04 eff:3.2% logz=594972.02+/-0.89 dlogz:15.648>10]

2511it [05:41,  9.30it/s, bound:1113 nc: 35 ncall:7.9e+04 eff:3.2% logz=594972.08+/-0.89 dlogz:15.578>10]

2512it [05:41,  9.23it/s, bound:1113 nc: 35 ncall:7.9e+04 eff:3.2% logz=594972.13+/-0.89 dlogz:15.511>10]

2513it [05:41,  9.33it/s, bound:1114 nc: 35 ncall:7.9e+04 eff:3.2% logz=594972.18+/-0.89 dlogz:15.446>10]

2514it [05:41,  9.23it/s, bound:1114 nc: 35 ncall:7.9e+04 eff:3.2% logz=594972.23+/-0.89 dlogz:15.382>10]

2515it [05:41,  9.14it/s, bound:1115 nc: 35 ncall:7.9e+04 eff:3.2% logz=594972.28+/-0.89 dlogz:15.320>10]

2516it [05:41,  9.26it/s, bound:1115 nc: 35 ncall:7.9e+04 eff:3.2% logz=594972.33+/-0.89 dlogz:15.260>10]

2517it [05:41,  5.85it/s, bound:1117 nc:105 ncall:7.9e+04 eff:3.2% logz=594972.38+/-0.89 dlogz:15.198>10]

2518it [05:42,  6.67it/s, bound:1117 nc: 34 ncall:8.0e+04 eff:3.2% logz=594972.44+/-0.89 dlogz:15.130>10]

2519it [05:42,  7.22it/s, bound:1118 nc: 35 ncall:8.0e+04 eff:3.2% logz=594972.50+/-0.89 dlogz:15.062>10]

2520it [05:42,  7.75it/s, bound:1118 nc: 35 ncall:8.0e+04 eff:3.2% logz=594972.55+/-0.89 dlogz:14.994>10]

2521it [05:42,  8.14it/s, bound:1119 nc: 35 ncall:8.0e+04 eff:3.2% logz=594972.60+/-0.89 dlogz:14.929>10]

2522it [05:42,  8.37it/s, bound:1119 nc: 35 ncall:8.0e+04 eff:3.2% logz=594972.65+/-0.89 dlogz:14.865>10]

2523it [05:42,  8.68it/s, bound:1120 nc: 35 ncall:8.0e+04 eff:3.2% logz=594972.69+/-0.89 dlogz:14.804>10]

2524it [05:42,  8.93it/s, bound:1120 nc: 35 ncall:8.0e+04 eff:3.2% logz=594972.74+/-0.89 dlogz:14.745>10]

2525it [05:42,  8.99it/s, bound:1121 nc: 35 ncall:8.0e+04 eff:3.2% logz=594972.78+/-0.89 dlogz:14.688>10]

2526it [05:42,  9.15it/s, bound:1121 nc: 35 ncall:8.0e+04 eff:3.2% logz=594972.83+/-0.89 dlogz:14.632>10]

2527it [05:43,  9.15it/s, bound:1122 nc: 35 ncall:8.0e+04 eff:3.2% logz=594972.87+/-0.89 dlogz:14.577>10]

2528it [05:43,  9.24it/s, bound:1122 nc: 35 ncall:8.0e+04 eff:3.2% logz=594972.91+/-0.89 dlogz:14.523>10]

2529it [05:43,  9.39it/s, bound:1123 nc: 35 ncall:8.0e+04 eff:3.2% logz=594972.95+/-0.89 dlogz:14.469>10]

2530it [05:43,  9.49it/s, bound:1123 nc: 35 ncall:8.0e+04 eff:3.2% logz=594972.99+/-0.89 dlogz:14.415>10]

2531it [05:43,  9.47it/s, bound:1124 nc: 35 ncall:8.0e+04 eff:3.2% logz=594973.04+/-0.89 dlogz:14.360>10]

2532it [05:43,  9.57it/s, bound:1124 nc: 35 ncall:8.0e+04 eff:3.2% logz=594973.11+/-0.89 dlogz:14.295>10]

2533it [05:43,  7.32it/s, bound:1125 nc: 70 ncall:8.0e+04 eff:3.2% logz=594973.17+/-0.89 dlogz:14.220>10]

2534it [05:43,  7.87it/s, bound:1126 nc: 35 ncall:8.0e+04 eff:3.2% logz=594973.23+/-0.89 dlogz:14.147>10]

2536it [05:44,  8.68it/s, bound:1127 nc: 35 ncall:8.0e+04 eff:3.2% logz=594973.33+/-0.89 dlogz:14.011>10]

2538it [05:44,  7.83it/s, bound:1128 nc: 69 ncall:8.0e+04 eff:3.2% logz=594973.43+/-0.89 dlogz:16.613>10]

2539it [05:44,  6.89it/s, bound:1129 nc: 70 ncall:8.0e+04 eff:3.2% logz=594973.49+/-0.89 dlogz:16.551>10]

2540it [05:44,  7.37it/s, bound:1130 nc: 35 ncall:8.0e+04 eff:3.2% logz=594973.54+/-0.89 dlogz:16.487>10]

2541it [05:44,  7.88it/s, bound:1130 nc: 35 ncall:8.0e+04 eff:3.2% logz=594973.59+/-0.89 dlogz:16.422>10]

2543it [05:45,  7.29it/s, bound:1131 nc: 70 ncall:8.1e+04 eff:3.2% logz=594973.69+/-0.89 dlogz:16.298>10]

2544it [05:45,  7.74it/s, bound:1132 nc: 35 ncall:8.1e+04 eff:3.2% logz=594973.75+/-0.89 dlogz:16.233>10]

2545it [05:45,  8.12it/s, bound:1132 nc: 35 ncall:8.1e+04 eff:3.2% logz=594973.80+/-0.89 dlogz:16.164>10]

2546it [05:45,  8.54it/s, bound:1133 nc: 35 ncall:8.1e+04 eff:3.2% logz=594973.86+/-0.89 dlogz:16.096>10]

2547it [05:45,  8.80it/s, bound:1133 nc: 35 ncall:8.1e+04 eff:3.2% logz=594973.92+/-0.89 dlogz:16.026>10]

2548it [05:45,  9.03it/s, bound:1134 nc: 35 ncall:8.1e+04 eff:3.2% logz=594973.98+/-0.89 dlogz:15.953>10]

2549it [05:45,  9.15it/s, bound:1134 nc: 35 ncall:8.1e+04 eff:3.2% logz=594974.04+/-0.89 dlogz:15.881>10]

2550it [05:45,  9.19it/s, bound:1135 nc: 35 ncall:8.1e+04 eff:3.2% logz=594974.09+/-0.89 dlogz:15.813>10]

2551it [05:45,  9.36it/s, bound:1135 nc: 35 ncall:8.1e+04 eff:3.2% logz=594974.14+/-0.89 dlogz:15.747>10]

2552it [05:46,  7.36it/s, bound:1136 nc: 70 ncall:8.1e+04 eff:3.2% logz=594974.19+/-0.89 dlogz:15.682>10]

2553it [05:46,  7.89it/s, bound:1137 nc: 35 ncall:8.1e+04 eff:3.2% logz=594974.24+/-0.89 dlogz:15.620>10]

2554it [05:46,  8.35it/s, bound:1137 nc: 35 ncall:8.1e+04 eff:3.2% logz=594974.30+/-0.89 dlogz:15.557>10]

2555it [05:46,  6.77it/s, bound:1138 nc: 70 ncall:8.1e+04 eff:3.2% logz=594974.36+/-0.89 dlogz:15.486>10]

2556it [05:46,  7.38it/s, bound:1139 nc: 35 ncall:8.1e+04 eff:3.2% logz=594974.41+/-0.89 dlogz:15.416>10]

2557it [05:46,  7.99it/s, bound:1139 nc: 35 ncall:8.1e+04 eff:3.2% logz=594974.47+/-0.89 dlogz:15.346>10]

2558it [05:46,  8.45it/s, bound:1140 nc: 35 ncall:8.1e+04 eff:3.2% logz=594974.53+/-0.89 dlogz:15.275>10]

2559it [05:46,  8.77it/s, bound:1140 nc: 35 ncall:8.1e+04 eff:3.2% logz=594974.59+/-0.89 dlogz:15.204>10]

2560it [05:47,  8.96it/s, bound:1141 nc: 35 ncall:8.1e+04 eff:3.2% logz=594974.64+/-0.89 dlogz:15.136>10]

2561it [05:47,  9.14it/s, bound:1141 nc: 35 ncall:8.1e+04 eff:3.2% logz=594974.70+/-0.89 dlogz:15.069>10]

2562it [05:47,  9.18it/s, bound:1142 nc: 35 ncall:8.1e+04 eff:3.2% logz=594974.75+/-0.89 dlogz:15.001>10]

2563it [05:47,  9.23it/s, bound:1142 nc: 35 ncall:8.1e+04 eff:3.2% logz=594974.80+/-0.89 dlogz:14.935>10]

2564it [05:47,  9.20it/s, bound:1143 nc: 35 ncall:8.1e+04 eff:3.2% logz=594974.85+/-0.89 dlogz:14.871>10]

2565it [05:47,  9.36it/s, bound:1143 nc: 35 ncall:8.1e+04 eff:3.2% logz=594974.90+/-0.89 dlogz:14.808>10]

2566it [05:47,  9.50it/s, bound:1144 nc: 35 ncall:8.1e+04 eff:3.2% logz=594974.95+/-0.89 dlogz:14.748>10]

2567it [05:47,  9.63it/s, bound:1144 nc: 35 ncall:8.1e+04 eff:3.2% logz=594975.00+/-0.89 dlogz:14.688>10]

2568it [05:47,  9.49it/s, bound:1145 nc: 35 ncall:8.1e+04 eff:3.2% logz=594975.05+/-0.89 dlogz:14.627>10]

2569it [05:48,  9.52it/s, bound:1145 nc: 35 ncall:8.1e+04 eff:3.2% logz=594975.09+/-0.89 dlogz:14.565>10]

2570it [05:48,  9.53it/s, bound:1146 nc: 35 ncall:8.2e+04 eff:3.2% logz=594975.14+/-0.89 dlogz:14.505>10]

2571it [05:48,  7.35it/s, bound:1146 nc: 70 ncall:8.2e+04 eff:3.2% logz=594975.19+/-0.89 dlogz:14.446>10]

2572it [05:48,  7.90it/s, bound:1147 nc: 35 ncall:8.2e+04 eff:3.2% logz=594975.23+/-0.89 dlogz:14.389>10]

2573it [05:48,  8.35it/s, bound:1147 nc: 35 ncall:8.2e+04 eff:3.2% logz=594975.27+/-0.89 dlogz:14.333>10]

2574it [05:48,  8.67it/s, bound:1148 nc: 35 ncall:8.2e+04 eff:3.2% logz=594975.31+/-0.89 dlogz:14.278>10]

2575it [05:48,  8.91it/s, bound:1148 nc: 35 ncall:8.2e+04 eff:3.2% logz=594975.36+/-0.89 dlogz:14.223>10]

2576it [05:48,  9.18it/s, bound:1149 nc: 35 ncall:8.2e+04 eff:3.1% logz=594975.40+/-0.89 dlogz:14.167>10]

2578it [05:49,  9.42it/s, bound:1150 nc: 35 ncall:8.2e+04 eff:3.1% logz=594975.50+/-0.89 dlogz:14.050>10]

2579it [05:49,  9.49it/s, bound:1150 nc: 35 ncall:8.2e+04 eff:3.1% logz=594975.54+/-0.89 dlogz:13.991>10]

2580it [05:49,  9.54it/s, bound:1151 nc: 35 ncall:8.2e+04 eff:3.1% logz=594975.59+/-0.89 dlogz:13.932>10]

2581it [05:49,  9.58it/s, bound:1151 nc: 35 ncall:8.2e+04 eff:3.1% logz=594975.63+/-0.89 dlogz:13.874>10]

2582it [05:49,  9.55it/s, bound:1152 nc: 35 ncall:8.2e+04 eff:3.1% logz=594975.68+/-0.89 dlogz:13.817>10]

2583it [05:49,  9.61it/s, bound:1152 nc: 35 ncall:8.2e+04 eff:3.1% logz=594975.72+/-0.89 dlogz:13.762>10]

2584it [05:49,  9.61it/s, bound:1153 nc: 35 ncall:8.2e+04 eff:3.1% logz=594975.76+/-0.89 dlogz:13.709>10]

2585it [05:49,  9.65it/s, bound:1153 nc: 35 ncall:8.2e+04 eff:3.1% logz=594975.79+/-0.89 dlogz:13.657>10]

2586it [05:49,  9.52it/s, bound:1154 nc: 35 ncall:8.2e+04 eff:3.1% logz=594975.83+/-0.89 dlogz:13.606>10]

2587it [05:50,  9.64it/s, bound:1154 nc: 35 ncall:8.2e+04 eff:3.1% logz=594975.87+/-0.89 dlogz:13.556>10]

2588it [05:50,  9.63it/s, bound:1155 nc: 35 ncall:8.2e+04 eff:3.1% logz=594975.91+/-0.89 dlogz:13.507>10]

2589it [05:50,  9.66it/s, bound:1155 nc: 35 ncall:8.2e+04 eff:3.1% logz=594975.95+/-0.89 dlogz:13.454>10]

2590it [05:50,  9.53it/s, bound:1156 nc: 35 ncall:8.2e+04 eff:3.1% logz=594976.00+/-0.89 dlogz:13.399>10]

2591it [05:50,  9.48it/s, bound:1156 nc: 35 ncall:8.2e+04 eff:3.1% logz=594976.05+/-0.90 dlogz:13.340>10]

2592it [05:50,  9.47it/s, bound:1157 nc: 35 ncall:8.2e+04 eff:3.1% logz=594976.11+/-0.90 dlogz:13.273>10]

2593it [05:50,  9.51it/s, bound:1157 nc: 35 ncall:8.2e+04 eff:3.1% logz=594976.17+/-0.90 dlogz:13.203>10]

2594it [05:50,  9.59it/s, bound:1158 nc: 35 ncall:8.2e+04 eff:3.1% logz=594976.22+/-0.90 dlogz:13.136>10]

2595it [05:50,  9.37it/s, bound:1158 nc: 35 ncall:8.2e+04 eff:3.1% logz=594976.27+/-0.90 dlogz:13.071>10]

2596it [05:50,  9.51it/s, bound:1159 nc: 35 ncall:8.2e+04 eff:3.1% logz=594976.33+/-0.90 dlogz:13.005>10]

2597it [05:51,  9.56it/s, bound:1159 nc: 35 ncall:8.3e+04 eff:3.1% logz=594976.38+/-0.90 dlogz:12.939>10]

2598it [05:51,  9.45it/s, bound:1160 nc: 35 ncall:8.3e+04 eff:3.1% logz=594976.43+/-0.90 dlogz:12.876>10]

2599it [05:51,  7.52it/s, bound:1160 nc: 70 ncall:8.3e+04 eff:3.1% logz=594976.48+/-0.90 dlogz:12.812>10]

2600it [05:51,  6.50it/s, bound:1161 nc: 70 ncall:8.3e+04 eff:3.1% logz=594976.53+/-0.90 dlogz:14.460>10]

2601it [05:51,  7.23it/s, bound:1162 nc: 35 ncall:8.3e+04 eff:3.1% logz=594976.58+/-0.90 dlogz:14.398>10]

2602it [05:51,  7.81it/s, bound:1162 nc: 35 ncall:8.3e+04 eff:3.1% logz=594976.64+/-0.90 dlogz:14.333>10]

2603it [05:51,  6.63it/s, bound:1163 nc: 70 ncall:8.3e+04 eff:3.1% logz=594976.69+/-0.90 dlogz:14.265>10]

2604it [05:52,  7.36it/s, bound:1164 nc: 35 ncall:8.3e+04 eff:3.1% logz=594976.74+/-0.90 dlogz:14.198>10]

2606it [05:52,  8.41it/s, bound:1165 nc: 35 ncall:8.3e+04 eff:3.1% logz=594976.84+/-0.90 dlogz:14.070>10]

2607it [05:52,  8.60it/s, bound:1165 nc: 35 ncall:8.3e+04 eff:3.1% logz=594976.90+/-0.90 dlogz:14.007>10]

2608it [05:52,  8.83it/s, bound:1166 nc: 35 ncall:8.3e+04 eff:3.1% logz=594976.95+/-0.90 dlogz:13.940>10]

2610it [05:52,  9.33it/s, bound:1167 nc: 35 ncall:8.3e+04 eff:3.1% logz=594977.05+/-0.90 dlogz:13.813>10]

2611it [05:52,  9.47it/s, bound:1167 nc: 35 ncall:8.3e+04 eff:3.1% logz=594977.11+/-0.90 dlogz:13.750>10]

2613it [05:53,  8.07it/s, bound:1168 nc: 70 ncall:8.3e+04 eff:3.1% logz=594977.22+/-0.90 dlogz:13.610>10]

2614it [05:53,  8.37it/s, bound:1169 nc: 35 ncall:8.3e+04 eff:3.1% logz=594977.27+/-0.90 dlogz:13.543>10]

2615it [05:53,  8.68it/s, bound:1169 nc: 35 ncall:8.3e+04 eff:3.1% logz=594977.33+/-0.90 dlogz:13.478>10]

2616it [05:53,  8.97it/s, bound:1170 nc: 35 ncall:8.3e+04 eff:3.1% logz=594977.38+/-0.90 dlogz:13.413>10]

2617it [05:53,  9.19it/s, bound:1170 nc: 35 ncall:8.3e+04 eff:3.1% logz=594977.43+/-0.90 dlogz:13.345>10]

2618it [05:53,  9.19it/s, bound:1171 nc: 35 ncall:8.3e+04 eff:3.1% logz=594977.49+/-0.90 dlogz:13.280>10]

2619it [05:53,  9.20it/s, bound:1171 nc: 35 ncall:8.3e+04 eff:3.1% logz=594977.54+/-0.90 dlogz:13.216>10]

2620it [05:53,  9.26it/s, bound:1172 nc: 35 ncall:8.3e+04 eff:3.1% logz=594977.59+/-0.90 dlogz:13.152>10]

2621it [05:53,  9.31it/s, bound:1172 nc: 35 ncall:8.3e+04 eff:3.1% logz=594977.64+/-0.90 dlogz:13.088>10]

2622it [05:54,  9.23it/s, bound:1173 nc: 35 ncall:8.4e+04 eff:3.1% logz=594977.68+/-0.90 dlogz:13.027>10]

2623it [05:54,  9.29it/s, bound:1173 nc: 35 ncall:8.4e+04 eff:3.1% logz=594977.73+/-0.90 dlogz:12.968>10]

2624it [05:54,  9.17it/s, bound:1174 nc: 35 ncall:8.4e+04 eff:3.1% logz=594977.77+/-0.90 dlogz:12.911>10]

2625it [05:54,  9.26it/s, bound:1174 nc: 35 ncall:8.4e+04 eff:3.1% logz=594977.82+/-0.90 dlogz:12.855>10]

2626it [05:54,  9.17it/s, bound:1175 nc: 35 ncall:8.4e+04 eff:3.1% logz=594977.86+/-0.90 dlogz:12.799>10]

2627it [05:54,  5.92it/s, bound:1176 nc:105 ncall:8.4e+04 eff:3.1% logz=594977.90+/-0.90 dlogz:12.744>10]

2628it [05:54,  6.64it/s, bound:1176 nc: 35 ncall:8.4e+04 eff:3.1% logz=594977.94+/-0.90 dlogz:12.689>10]

2629it [05:54,  7.33it/s, bound:1177 nc: 35 ncall:8.4e+04 eff:3.1% logz=594977.98+/-0.90 dlogz:12.635>10]

2630it [05:55,  7.88it/s, bound:1177 nc: 35 ncall:8.4e+04 eff:3.1% logz=594978.03+/-0.90 dlogz:12.582>10]

2631it [05:55,  8.27it/s, bound:1178 nc: 35 ncall:8.4e+04 eff:3.1% logz=594978.07+/-0.90 dlogz:12.528>10]

2632it [05:55,  8.65it/s, bound:1178 nc: 35 ncall:8.4e+04 eff:3.1% logz=594978.11+/-0.90 dlogz:12.474>10]

2633it [05:55,  8.68it/s, bound:1179 nc: 35 ncall:8.4e+04 eff:3.1% logz=594978.15+/-0.90 dlogz:12.422>10]

2634it [05:55,  9.00it/s, bound:1179 nc: 35 ncall:8.4e+04 eff:3.1% logz=594978.18+/-0.90 dlogz:13.211>10]

2635it [05:55,  7.18it/s, bound:1180 nc: 70 ncall:8.4e+04 eff:3.1% logz=594978.22+/-0.90 dlogz:13.160>10]

2636it [05:55,  6.22it/s, bound:1181 nc: 70 ncall:8.4e+04 eff:3.1% logz=594978.26+/-0.90 dlogz:13.111>10]

2637it [05:56,  6.91it/s, bound:1182 nc: 35 ncall:8.4e+04 eff:3.1% logz=594978.29+/-0.90 dlogz:13.062>10]

2638it [05:56,  6.09it/s, bound:1182 nc: 70 ncall:8.4e+04 eff:3.1% logz=594978.33+/-0.90 dlogz:13.012>10]

2639it [05:56,  6.80it/s, bound:1183 nc: 35 ncall:8.4e+04 eff:3.1% logz=594978.37+/-0.90 dlogz:12.963>10]

2640it [05:56,  7.40it/s, bound:1183 nc: 35 ncall:8.4e+04 eff:3.1% logz=594978.41+/-0.90 dlogz:12.913>10]

2641it [05:56,  7.88it/s, bound:1184 nc: 35 ncall:8.4e+04 eff:3.1% logz=594978.45+/-0.90 dlogz:12.860>10]

2642it [05:56,  8.37it/s, bound:1184 nc: 35 ncall:8.4e+04 eff:3.1% logz=594978.50+/-0.90 dlogz:12.805>10]

2643it [05:56,  8.69it/s, bound:1185 nc: 35 ncall:8.4e+04 eff:3.1% logz=594978.54+/-0.90 dlogz:12.749>10]

2644it [05:56,  8.99it/s, bound:1185 nc: 35 ncall:8.4e+04 eff:3.1% logz=594978.58+/-0.90 dlogz:12.694>10]

2645it [05:56,  9.13it/s, bound:1186 nc: 35 ncall:8.5e+04 eff:3.1% logz=594978.62+/-0.90 dlogz:12.639>10]

2646it [05:57,  9.30it/s, bound:1186 nc: 35 ncall:8.5e+04 eff:3.1% logz=594978.67+/-0.90 dlogz:12.584>10]

2647it [05:57,  9.39it/s, bound:1187 nc: 35 ncall:8.5e+04 eff:3.1% logz=594978.71+/-0.90 dlogz:12.528>10]

2648it [05:57,  9.49it/s, bound:1187 nc: 35 ncall:8.5e+04 eff:3.1% logz=594978.76+/-0.90 dlogz:12.471>10]

2649it [05:57,  9.33it/s, bound:1188 nc: 35 ncall:8.5e+04 eff:3.1% logz=594978.80+/-0.90 dlogz:12.415>10]

2650it [05:57,  9.14it/s, bound:1188 nc: 35 ncall:8.5e+04 eff:3.1% logz=594978.84+/-0.90 dlogz:12.358>10]

2651it [05:57,  9.21it/s, bound:1189 nc: 35 ncall:8.5e+04 eff:3.1% logz=594978.89+/-0.90 dlogz:12.302>10]

2652it [05:57,  9.30it/s, bound:1189 nc: 35 ncall:8.5e+04 eff:3.1% logz=594978.93+/-0.90 dlogz:12.247>10]

2653it [05:57,  9.24it/s, bound:1190 nc: 35 ncall:8.5e+04 eff:3.1% logz=594978.97+/-0.90 dlogz:12.193>10]

2655it [05:58,  9.39it/s, bound:1191 nc: 35 ncall:8.5e+04 eff:3.1% logz=594979.06+/-0.91 dlogz:12.081>10]

2656it [05:58,  9.38it/s, bound:1191 nc: 35 ncall:8.5e+04 eff:3.1% logz=594979.10+/-0.91 dlogz:12.026>10]

2657it [05:58,  9.49it/s, bound:1192 nc: 35 ncall:8.5e+04 eff:3.1% logz=594979.14+/-0.91 dlogz:11.972>10]

2658it [05:58,  9.47it/s, bound:1192 nc: 35 ncall:8.5e+04 eff:3.1% logz=594979.19+/-0.91 dlogz:11.916>10]

2659it [05:58,  9.47it/s, bound:1193 nc: 35 ncall:8.5e+04 eff:3.1% logz=594979.23+/-0.91 dlogz:11.859>10]

2660it [05:58,  9.60it/s, bound:1193 nc: 35 ncall:8.5e+04 eff:3.1% logz=594979.28+/-0.91 dlogz:11.799>10]

2661it [05:58,  9.59it/s, bound:1194 nc: 35 ncall:8.5e+04 eff:3.1% logz=594979.33+/-0.91 dlogz:11.739>10]

2662it [05:58,  9.65it/s, bound:1194 nc: 35 ncall:8.5e+04 eff:3.1% logz=594979.38+/-0.91 dlogz:11.678>10]

2663it [05:58,  9.57it/s, bound:1195 nc: 35 ncall:8.5e+04 eff:3.1% logz=594979.44+/-0.91 dlogz:11.614>10]

2664it [05:58,  9.49it/s, bound:1195 nc: 35 ncall:8.5e+04 eff:3.1% logz=594979.49+/-0.91 dlogz:11.548>10]

2665it [05:59,  7.30it/s, bound:1196 nc: 70 ncall:8.5e+04 eff:3.1% logz=594979.54+/-0.91 dlogz:11.483>10]

2666it [05:59,  7.85it/s, bound:1197 nc: 35 ncall:8.5e+04 eff:3.1% logz=594979.59+/-0.91 dlogz:11.417>10]

2667it [05:59,  8.29it/s, bound:1197 nc: 35 ncall:8.5e+04 eff:3.1% logz=594979.64+/-0.91 dlogz:11.354>10]

2668it [05:59,  8.64it/s, bound:1198 nc: 35 ncall:8.5e+04 eff:3.1% logz=594979.69+/-0.91 dlogz:11.291>10]

2669it [05:59,  8.57it/s, bound:1198 nc: 35 ncall:8.5e+04 eff:3.1% logz=594979.74+/-0.91 dlogz:11.231>10]

2670it [05:59,  8.71it/s, bound:1199 nc: 35 ncall:8.5e+04 eff:3.1% logz=594979.78+/-0.91 dlogz:11.172>10]

2671it [05:59,  8.84it/s, bound:1199 nc: 35 ncall:8.5e+04 eff:3.1% logz=594979.83+/-0.91 dlogz:11.112>10]

2672it [05:59,  8.94it/s, bound:1200 nc: 35 ncall:8.5e+04 eff:3.1% logz=594979.87+/-0.91 dlogz:11.054>10]

2673it [06:00,  5.69it/s, bound:1201 nc:105 ncall:8.6e+04 eff:3.1% logz=594979.91+/-0.91 dlogz:10.999>10]

2674it [06:00,  6.50it/s, bound:1201 nc: 35 ncall:8.6e+04 eff:3.1% logz=594979.95+/-0.91 dlogz:10.945>10]

2675it [06:00,  7.16it/s, bound:1202 nc: 35 ncall:8.6e+04 eff:3.1% logz=594979.99+/-0.91 dlogz:10.894>10]

2676it [06:00,  7.79it/s, bound:1202 nc: 35 ncall:8.6e+04 eff:3.1% logz=594980.04+/-0.91 dlogz:10.841>10]

2677it [06:00,  8.27it/s, bound:1203 nc: 35 ncall:8.6e+04 eff:3.1% logz=594980.08+/-0.91 dlogz:10.787>10]

2678it [06:00,  8.57it/s, bound:1203 nc: 35 ncall:8.6e+04 eff:3.1% logz=594980.11+/-0.91 dlogz:10.734>10]

2679it [06:00,  8.79it/s, bound:1204 nc: 35 ncall:8.6e+04 eff:3.1% logz=594980.15+/-0.91 dlogz:10.683>10]

2680it [06:01,  7.06it/s, bound:1204 nc: 70 ncall:8.6e+04 eff:3.1% logz=594980.19+/-0.91 dlogz:10.632>10]

2681it [06:01,  7.71it/s, bound:1205 nc: 35 ncall:8.6e+04 eff:3.1% logz=594980.23+/-0.91 dlogz:10.581>10]

2682it [06:01,  8.23it/s, bound:1205 nc: 35 ncall:8.6e+04 eff:3.1% logz=594980.27+/-0.91 dlogz:10.530>10]

2683it [06:01,  6.79it/s, bound:1206 nc: 70 ncall:8.6e+04 eff:3.1% logz=594980.30+/-0.91 dlogz:10.480>10]

2684it [06:01,  7.39it/s, bound:1207 nc: 35 ncall:8.6e+04 eff:3.1% logz=594980.34+/-0.91 dlogz:10.431>10]

2685it [06:01,  7.88it/s, bound:1207 nc: 35 ncall:8.6e+04 eff:3.1% logz=594980.38+/-0.91 dlogz:10.382>10]

2686it [06:01,  8.38it/s, bound:1208 nc: 35 ncall:8.6e+04 eff:3.1% logz=594980.41+/-0.91 dlogz:10.333>10]

2687it [06:01,  8.75it/s, bound:1208 nc: 35 ncall:8.6e+04 eff:3.1% logz=594980.45+/-0.91 dlogz:10.285>10]

2688it [06:02,  8.99it/s, bound:1209 nc: 35 ncall:8.6e+04 eff:3.1% logz=594980.48+/-0.91 dlogz:10.237>10]

2689it [06:02,  9.17it/s, bound:1209 nc: 35 ncall:8.6e+04 eff:3.1% logz=594980.52+/-0.91 dlogz:10.191>10]

2690it [06:02,  9.36it/s, bound:1210 nc: 35 ncall:8.6e+04 eff:3.1% logz=594980.55+/-0.91 dlogz:10.145>10]

2692it [06:02,  9.63it/s, bound:1211 nc: 35 ncall:8.6e+04 eff:3.1% logz=594980.62+/-0.91 dlogz:10.055>10]

2693it [06:02,  9.68it/s, bound:1211 nc: 35 ncall:8.6e+04 eff:3.1% logz=594980.66+/-0.91 dlogz:10.005>10]

12:13 bilby INFO    : Written checkpoint file C:\Users\雷畅\Documents\Codex\2026-05-19\files-mentioned-by-the-user-2026\task5-lisa-taiji\results\task5_subtask2\task_five_day_samples/task_five_day_resume.pickle

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

C:\Users\雷畅\Documents\Codex\2026-05-19\files-mentioned-by-the-user-2026\task5-lisa-taiji\.venv-tdc\Lib\site-packages\dynesty\plotting.py:179: RuntimeWarning: overflow encountered in exp
  data = [nlive, np.exp(logl), np.exp(logwt), np.exp(logz)]
C:\Users\雷畅\Documents\Codex\2026-05-19\files-mentioned-by-the-user-2026\task5-lisa-taiji\.venv-tdc\Lib\site-packages\dynesty\plotting.py:203: RuntimeWarning: overflow encountered in exp
  zspan = (0., 1.05 * np.exp(logz[-1] + 3. * logzerr[-1]))
12:13 bilby WARNING : Axis limits cannot be NaN or Inf

12:13 bilby WARNING : Failed to create dynesty run plot at checkpoint

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

2693it [06:05,  7.37it/s, bound:1211 nc:  1 ncall:8.6e+04 eff:3.2% logz=594987.21+/-1.21 dlogz:0.314>10]

12:13 bilby INFO    : Sampling time: 0:06:02.054722

12:13 bilby INFO    : Summary of results:
nsamples: 2773
ln_noise_evidence:    nan
ln_evidence: 594987.215 +/-  1.207
ln_bayes_factor:    nan +/-  1.207

Corner plot skipped for task_five_day: latex was not able to process the following string:
b'lp'

Here is the full command invocation and its output:

latex -interaction=nonstopmode -halt-on-error -no-shell-escape file.tex




It seems that this is a fresh TeX installation.
Please finish the setup before proceeding.
For more information, visit:
https://miktex.org/howto/install-miktex-win

## 15. Baseline vs Modified-Window Comparison

In [18]:
def compare_summaries(baseline_summary: pd.DataFrame, five_day_summary: pd.DataFrame) -> pd.DataFrame:
    base = baseline_summary.add_prefix("baseline_").rename(columns={"baseline_parameter": "parameter"})
    five = five_day_summary.add_prefix("five_day_").rename(columns={"five_day_parameter": "parameter"})
    merged = pd.merge(base, five, on="parameter", how="outer")
    merged["ci90_width_ratio_5day_over_baseline"] = merged["five_day_ci90_width"] / merged["baseline_ci90_width"]
    return merged

comparison = pd.DataFrame(columns=["parameter", "baseline_median", "baseline_ci90_low", "baseline_ci90_high", "baseline_ci90_width", "five_day_median", "five_day_ci90_low", "five_day_ci90_high", "five_day_ci90_width", "ci90_width_ratio_5day_over_baseline"])
if baseline_summary is not None and five_day_summary is not None:
    comparison = compare_summaries(baseline_summary, five_day_summary)
    comparison.to_csv(RESULT_DIR / "baseline_vs_five_day_parameter_summary.csv", index=False)
display(comparison)

,parameter,baseline_median,baseline_ci90_low,baseline_ci90_high,baseline_ci90_width,five_day_median,five_day_ci90_low,five_day_ci90_high,five_day_ci90_width,ci90_width_ratio_5day_over_baseline
0,chirp_mass,2.997516e+06,2.993429e+06,3.000388e+06,6959.688954,2.996323e+06,2.992731e+06,2.999212e+06,6481.294575,0.931262
1,inclination,1.255885e+00,1.254123e+00,1.257701e+00,0.003578,1.245462e+00,1.243054e+00,1.250119e+00,0.007065,1.974557
2,latitude,3.370419e-01,1.852256e-01,4.770673e-01,0.291842,4.120530e-02,-9.000469e-03,1.927181e-01,0.201719,0.691192
3,longitude,4.623415e+00,4.594708e+00,4.830994e+00,0.236286,5.243276e+00,5.115388e+00,5.337964e+00,0.222576,0.941974
4,luminosity_distance,4.557960e+04,4.366821e+04,4.833878e+04,4670.570367,4.297836e+04,4.207266e+04,4.524219e+04,3169.529069,0.678617
5,mass_ratio,2.508190e-01,2.492233e-01,2.528901e-01,0.003667,2.529343e-01,2.504243e-01,2.534655e-01,0.003041,0.829377
6,psi,2.507504e+00,2.481981e+00,2.581387e+00,0.099406,1.154878e+00,1.098161e+00,1.202226e+00,0.104065,1.046867
7,reference_phase,4.439838e+00,4.438546e+00,4.443605e+00,0.005059,6.010211e+00,6.000537e+00,6.011279e+00,0.010742,2.123416
8,reference_time,2.499763e+01,2.499760e+01,2.499763e+01,0.000033,2.499761e+01,2.499760e+01,2.499763e+01,0.000031,0.918779
9,spin_1z,3.929042e-01,3.773597e-01,4.009393e-01,0.023580,3.788991e-01,3.731182e-01,3.909897e-01,0.017871,0.757922
10,spin_2z,6.190036e-01,5.988439e-01,6.885128e-01,0.089669,6.884872e-01,6.411833e-01,7.116992e-01,0.070516,0.786404

## 16. Taiji-Frame Sky Position Plot

In [19]:
def plot_taiji_frame_position(result, label: str, filename: str) -> None:
    num_sample = len(result.posterior["longitude"])
    longitude_TJ = np.zeros(num_sample)
    latitude_TJ = np.zeros(num_sample)
    for i in range(num_sample):
        lon, lat, _ = SSBPosToDetectorFrame(lon_ssb=result.posterior["longitude"][i], lat_ssb=result.posterior["latitude"][i], psi_ssb=result.posterior["psi"][i], orbit_time_SI=injected_parameters["coalescence_time"]*DAY, orbit=orbit)
        longitude_TJ[i] = lon % TWOPI
        latitude_TJ[i] = lat
    plt.figure(figsize=(5.2, 4.4))
    plt.hist2d(x=longitude_TJ, y=latitude_TJ, bins=50)
    plt.xlabel("longitude (rad)")
    plt.ylabel("latitude (rad)")
    plt.title(label)
    save_current_figure(filename)

if baseline_result is not None:
    plot_taiji_frame_position(baseline_result, "baseline Taiji-frame sky position", "09_baseline_taiji_frame_sky.png")
if five_day_result is not None:
    plot_taiji_frame_position(five_day_result, "five-day Taiji-frame sky position", "10_five_day_taiji_frame_sky.png")
if baseline_result is None and five_day_result is None:
    print("Sky-position plots waiting for sampler results.")

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

Saved: figures\task5_subtask2\09_baseline_taiji_frame_sky.png

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

findfont: Generic family 'serif' not found because none of the following families were found: Computer Modern Roman

Saved: figures\task5_subtask2\10_five_day_taiji_frame_sky.png

## 17. Result Manifest for README

In [20]:
manifest = {
    "baseline_timeseries": "figures/task5_subtask2/01_baseline_timeseries.png",
    "baseline_frequency_psd": "figures/task5_subtask2/02_baseline_frequency_psd.png",
    "baseline_reconstruction_direct": "figures/task5_subtask2/03_baseline_reconstruction_direct.png",
    "baseline_reconstruction_reflected": "figures/task5_subtask2/04_baseline_reconstruction_reflected.png",
    "five_day_timeseries": "figures/task5_subtask2/05_five_day_timeseries.png",
    "five_day_frequency_psd": "figures/task5_subtask2/06_five_day_frequency_psd.png",
    "five_day_reconstruction_direct": "figures/task5_subtask2/07_five_day_reconstruction_direct.png",
    "five_day_reconstruction_reflected": "figures/task5_subtask2/08_five_day_reconstruction_reflected.png",
    "baseline_taiji_frame_sky": "figures/task5_subtask2/09_baseline_taiji_frame_sky.png",
    "five_day_taiji_frame_sky": "figures/task5_subtask2/10_five_day_taiji_frame_sky.png",
    "comparison_table": "results/task5_subtask2/baseline_vs_five_day_parameter_summary.csv",
}
save_json(manifest, "manifest.json")
print(json.dumps(manifest, indent=2, ensure_ascii=False))

Saved: results\task5_subtask2\manifest.json
{
  "baseline_timeseries": "figures/task5_subtask2/01_baseline_timeseries.png",
  "baseline_frequency_psd": "figures/task5_subtask2/02_baseline_frequency_psd.png",
  "baseline_reconstruction_direct": "figures/task5_subtask2/03_baseline_reconstruction_direct.png",
  "baseline_reconstruction_reflected": "figures/task5_subtask2/04_baseline_reconstruction_reflected.png",
  "five_day_timeseries": "figures/task5_subtask2/05_five_day_timeseries.png",
  "five_day_frequency_psd": "figures/task5_subtask2/06_five_day_frequency_psd.png",
  "five_day_reconstruction_direct": "figures/task5_subtask2/07_five_day_reconstruction_direct.png",
  "five_day_reconstruction_reflected": "figures/task5_subtask2/08_five_day_reconstruction_reflected.png",
  "baseline_taiji_frame_sky": "figures/task5_subtask2/09_baseline_taiji_frame_sky.png",
  "five_day_taiji_frame_sky": "figures/task5_subtask2/10_five_day_taiji_frame_sky.png",
  "comparison_table": "results/task5_subtask2/baseline_vs_five_day_parameter_summary.csv"
}

## 18. Final Discussion Notes

Complete this section after the full runs finish.

Report these points in the README:

1. Whether official Example 4 was reproduced.
2. Baseline window: `tc - 2.5 days` to `tc + 2.5 days`.
3. Modified task window: `tc - 4 days` to `tc + 1 day`.
4. Whether the modified window changes search parameters, reconstruction residuals, Fisher estimates, or posterior credible intervals.
5. Which parameters improve most and which remain degenerate or multimodal.
6. Limitations: idealized single-bright-MBHB assumption, simplified noise treatment, possible multimodality, and local Windows environment constraints.

Conclusion draft:

- Baseline reproduction: TODO after TDC data and sampler run.
- Modified 5-day run: TODO after TDC data and sampler run.
- Quantitative posterior comparison: TODO after both posterior summaries are generated.